// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_fields.sql

package sqlcgen

import (
	"context"
	"time"
)

const weaveActivateField = `-- name: WeaveActivateField :exec
UPDATE weave_fields
SET deprecated = false, updated_at = NOW()
WHERE id = $1
`

// Reverses Deprecate. The field becomes available for new connections
// again.
func (q *Queries) WeaveActivateField(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveActivateField, id)
	return err
}

const weaveCountFields = `-- name: WeaveCountFields :one
SELECT COUNT(*) FROM weave_fields
WHERE project_id = $1::text
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR system_name ILIKE '%' || $2::text || '%'
       OR COALESCE(semantic_id, '') ILIKE '%' || $2::text || '%'
       OR COALESCE(ontology_path, '') ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR status = $3::text)
  AND ($4::text = '' OR EXISTS
       (SELECT 1 FROM weave_field_overrides fo WHERE fo.field_id =
       weave_fields.id AND fo.entity_type IN ('model','collection') AND
       fo.entity_id = $4))
`

type WeaveCountFieldsParams struct {
	ProjectID string `json:"project_id"`
	Search    string `json:"search"`
	Status    string `json:"status"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) WeaveCountFields(ctx context.Context, arg WeaveCountFieldsParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountFields,
		arg.ProjectID,
		arg.Search,
		arg.Status,
		arg.OwnerID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveCreateField = `-- name: WeaveCreateField :one
INSERT INTO weave_fields (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id,
    ontology_scope, ontology_path, path_elements,
    expected_value_type, examples,
    staging_id
) VALUES (
    $1, NOW(), NOW(), $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13
) RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, ontology_scope, ontology_path, path_elements, expected_value_type, examples, staging_id, deprecated, version_number, subfield_paths
`

type WeaveCreateFieldParams struct {
	ID                string  `json:"id"`
	SemanticID        *string `json:"semantic_id"`
	SystemName        *string `json:"system_name"`
	UiName            []byte  `json:"ui_name"`
	Description       []byte  `json:"description"`
	Status            string  `json:"status"`
	ProjectID         string  `json:"project_id"`
	OntologyScope     []byte  `json:"ontology_scope"`
	OntologyPath      *string `json:"ontology_path"`
	PathElements      []byte  `json:"path_elements"`
	ExpectedValueType *string `json:"expected_value_type"`
	Examples          []byte  `json:"examples"`
	StagingID         *int64  `json:"staging_id"`
}

func (q *Queries) WeaveCreateField(ctx context.Context, arg WeaveCreateFieldParams) (WeaveField, error) {
	row := q.db.QueryRow(ctx, weaveCreateField,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.OntologyScope,
		arg.OntologyPath,
		arg.PathElements,
		arg.ExpectedValueType,
		arg.Examples,
		arg.StagingID,
	)
	var i WeaveField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.OntologyPath,
		&i.PathElements,
		&i.ExpectedValueType,
		&i.Examples,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.SubfieldPaths,
	)
	return i, err
}

const weaveDeleteField = `-- name: WeaveDeleteField :exec
DELETE FROM weave_fields WHERE id = $1
`

func (q *Queries) WeaveDeleteField(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteField, id)
	return err
}

const weaveDeprecateField = `-- name: WeaveDeprecateField :exec
UPDATE weave_fields
SET deprecated = true, updated_at = NOW()
WHERE id = $1
`

// Soft-retires a field. Existing references stay intact; pickers stop
// offering it for new connections.
func (q *Queries) WeaveDeprecateField(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeprecateField, id)
	return err
}

const weaveFieldIsInUse = `-- name: WeaveFieldIsInUse :one
SELECT EXISTS (
    SELECT 1 FROM weave_field_overrides
    WHERE field_id = $1
      AND project_id = $2
      AND entity_type IN ('model', 'collection')
    LIMIT 1
)::bool
`

type WeaveFieldIsInUseParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
}

// Returns true when the field is referenced by any non-base override
// (entity_type IN ('model','collection')). The base override row
// (entity_type=”) is the field's own intrinsic state and does NOT
// count as in-use. Hot path: delete preflight + UI gating.
func (q *Queries) WeaveFieldIsInUse(ctx context.Context, arg WeaveFieldIsInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, weaveFieldIsInUse, arg.FieldID, arg.ProjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveFieldUsageCollections = `-- name: WeaveFieldUsageCollections :many
SELECT
    col.id                                                AS collection_id,
    col.system_name                                       AS collection_system_name,
    COALESCE(col.ui_name ->> 'en', col.system_name, '')   AS collection_name
FROM weave_field_overrides fo
JOIN weave_collections col ON col.id = fo.entity_id
WHERE fo.entity_type = 'collection'
  AND fo.field_id = $1
  AND fo.project_id = $2
ORDER BY collection_name
LIMIT 10
`

type WeaveFieldUsageCollectionsParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
}

type WeaveFieldUsageCollectionsRow struct {
	CollectionID         string  `json:"collection_id"`
	CollectionSystemName *string `json:"collection_system_name"`
	CollectionName       string  `json:"collection_name"`
}

// Returns up to 10 sample collections that reference this field.
func (q *Queries) WeaveFieldUsageCollections(ctx context.Context, arg WeaveFieldUsageCollectionsParams) ([]WeaveFieldUsageCollectionsRow, error) {
	rows, err := q.db.Query(ctx, weaveFieldUsageCollections, arg.FieldID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveFieldUsageCollectionsRow{}
	for rows.Next() {
		var i WeaveFieldUsageCollectionsRow
		if err := rows.Scan(&i.CollectionID, &i.CollectionSystemName, &i.CollectionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveFieldUsageCounts = `-- name: WeaveFieldUsageCounts :one
SELECT
    COUNT(*) FILTER (WHERE entity_type = 'model')      AS model_count,
    COUNT(*) FILTER (WHERE entity_type = 'collection') AS collection_count
FROM weave_field_overrides
WHERE field_id = $1
  AND project_id = $2
  AND entity_type IN ('model', 'collection')
`

type WeaveFieldUsageCountsParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
}

type WeaveFieldUsageCountsRow struct {
	ModelCount      int64 `json:"model_count"`
	CollectionCount int64 `json:"collection_count"`
}

// Returns model + collection adoption counts for usage stats display.
func (q *Queries) WeaveFieldUsageCounts(ctx context.Context, arg WeaveFieldUsageCountsParams) (WeaveFieldUsageCountsRow, error) {
	row := q.db.QueryRow(ctx, weaveFieldUsageCounts, arg.FieldID, arg.ProjectID)
	var i WeaveFieldUsageCountsRow
	err := row.Scan(&i.ModelCount, &i.CollectionCount)
	return i, err
}

const weaveFieldUsageModels = `-- name: WeaveFieldUsageModels :many
SELECT
    m.id                                              AS model_id,
    m.system_name                                     AS model_system_name,
    COALESCE(m.ui_name ->> 'en', m.system_name, '')   AS model_name
FROM weave_field_overrides fo
JOIN weave_models m ON m.id = fo.entity_id
WHERE fo.entity_type = 'model'
  AND fo.field_id = $1
  AND fo.project_id = $2
ORDER BY model_name
LIMIT 10
`

type WeaveFieldUsageModelsParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
}

type WeaveFieldUsageModelsRow struct {
	ModelID         string  `json:"model_id"`
	ModelSystemName *string `json:"model_system_name"`
	ModelName       string  `json:"model_name"`
}

// Returns up to 10 sample models that reference this field. Used for
// the 409 payload when delete is blocked.
func (q *Queries) WeaveFieldUsageModels(ctx context.Context, arg WeaveFieldUsageModelsParams) ([]WeaveFieldUsageModelsRow, error) {
	rows, err := q.db.Query(ctx, weaveFieldUsageModels, arg.FieldID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveFieldUsageModelsRow{}
	for rows.Next() {
		var i WeaveFieldUsageModelsRow
		if err := rows.Scan(&i.ModelID, &i.ModelSystemName, &i.ModelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveGetFieldByGlobalIdentifier = `-- name: WeaveGetFieldByGlobalIdentifier :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, ontology_scope, ontology_path, path_elements, expected_value_type, examples, staging_id, deprecated, version_number, subfield_paths FROM weave_fields
WHERE semantic_id = $1 OR id = $1
`

// Project-agnostic lookup for identifiers that are globally unique
// (semantic_id encodes the owning project prefix; id is a ULID). Used by
// restore to resolve a cross-project override reference (e.g. a vendored
// parent's override pointing at another vendored project's field). System
// names are project-scoped and deliberately excluded.
func (q *Queries) WeaveGetFieldByGlobalIdentifier(ctx context.Context, semanticID *string) (WeaveField, error) {
	row := q.db.QueryRow(ctx, weaveGetFieldByGlobalIdentifier, semanticID)
	var i WeaveField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.OntologyPath,
		&i.PathElements,
		&i.ExpectedValueType,
		&i.Examples,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.SubfieldPaths,
	)
	return i, err
}

const weaveGetFieldByID = `-- name: WeaveGetFieldByID :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, ontology_scope, ontology_path, path_elements, expected_value_type, examples, staging_id, deprecated, version_number, subfield_paths FROM weave_fields WHERE id = $1
`

func (q *Queries) WeaveGetFieldByID(ctx context.Context, id string) (WeaveField, error) {
	row := q.db.QueryRow(ctx, weaveGetFieldByID, id)
	var i WeaveField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.OntologyPath,
		&i.PathElements,
		&i.ExpectedValueType,
		&i.Examples,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.SubfieldPaths,
	)
	return i, err
}

const weaveGetFieldByIdentifier = `-- name: WeaveGetFieldByIdentifier :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, ontology_scope, ontology_path, path_elements, expected_value_type, examples, staging_id, deprecated, version_number, subfield_paths FROM weave_fields
WHERE (semantic_id = $1 OR system_name = $1 OR id = $1)
  AND project_id = $2
`

type WeaveGetFieldByIdentifierParams struct {
	SemanticID *string `json:"semantic_id"`
	ProjectID  string  `json:"project_id"`
}

func (q *Queries) WeaveGetFieldByIdentifier(ctx context.Context, arg WeaveGetFieldByIdentifierParams) (WeaveField, error) {
	row := q.db.QueryRow(ctx, weaveGetFieldByIdentifier, arg.SemanticID, arg.ProjectID)
	var i WeaveField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.OntologyPath,
		&i.PathElements,
		&i.ExpectedValueType,
		&i.Examples,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.SubfieldPaths,
	)
	return i, err
}

const weaveGetFieldCollections = `-- name: WeaveGetFieldCollections :many
SELECT
    col.id                                                AS collection_id,
    COALESCE(col.ui_name ->> 'en', col.system_name, '')   AS collection_name
FROM weave_field_overrides fo
JOIN weave_collections col ON col.id = fo.entity_id
WHERE fo.entity_type = 'collection' AND fo.field_id = $1
ORDER BY collection_name
`

type WeaveGetFieldCollectionsRow struct {
	CollectionID   string `json:"collection_id"`
	CollectionName string `json:"collection_name"`
}

// Returns collections that reference a field via weave_field_overrides
// (entity_type='collection').
func (q *Queries) WeaveGetFieldCollections(ctx context.Context, fieldID string) ([]WeaveGetFieldCollectionsRow, error) {
	rows, err := q.db.Query(ctx, weaveGetFieldCollections, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveGetFieldCollectionsRow{}
	for rows.Next() {
		var i WeaveGetFieldCollectionsRow
		if err := rows.Scan(&i.CollectionID, &i.CollectionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveGetFieldModels = `-- name: WeaveGetFieldModels :many
SELECT
    m.id                                              AS model_id,
    COALESCE(m.ui_name ->> 'en', m.system_name, '')   AS model_name
FROM weave_field_overrides fo
JOIN weave_models m ON m.id = fo.entity_id
WHERE fo.entity_type = 'model' AND fo.field_id = $1
ORDER BY model_name
`

type WeaveGetFieldModelsRow struct {
	ModelID   string `json:"model_id"`
	ModelName string `json:"model_name"`
}

// Returns models that reference a field via weave_field_overrides
// (entity_type='model'). Replaces the legacy model_fields junction.
func (q *Queries) WeaveGetFieldModels(ctx context.Context, fieldID string) ([]WeaveGetFieldModelsRow, error) {
	rows, err := q.db.Query(ctx, weaveGetFieldModels, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveGetFieldModelsRow{}
	for rows.Next() {
		var i WeaveGetFieldModelsRow
		if err := rows.Scan(&i.ModelID, &i.ModelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListFields = `-- name: WeaveListFields :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description,
       status, project_id, ontology_scope, ontology_path, path_elements,
       expected_value_type, examples, staging_id, deprecated, subfield_paths
FROM weave_fields
WHERE project_id = $1::text
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR system_name ILIKE '%' || $2::text || '%'
       OR COALESCE(semantic_id, '') ILIKE '%' || $2::text || '%'
       OR COALESCE(ontology_path, '') ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR status = $3::text)
  AND ($4::text = '' OR EXISTS
       (SELECT 1 FROM weave_field_overrides fo WHERE fo.field_id =
       weave_fields.id AND fo.entity_type IN ('model','collection') AND
       fo.entity_id = $4))
ORDER BY
    CASE WHEN $5::text = 'ui_name' AND NOT $6::boolean THEN ui_name->>'en' END ASC NULLS LAST,
    CASE WHEN $5::text = 'ui_name' AND $6::boolean THEN ui_name->>'en' END DESC NULLS LAST,
    CASE WHEN $5::text = 'name' AND NOT $6::boolean THEN system_name END ASC NULLS LAST,
    CASE WHEN $5::text = 'name' AND $6::boolean THEN system_name END DESC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND NOT $6::boolean THEN system_name END ASC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND $6::boolean THEN system_name END DESC NULLS LAST,
    CASE WHEN $5::text = 'updated_at' AND NOT $6::boolean THEN updated_at END ASC,
    CASE WHEN $5::text = 'updated_at' AND $6::boolean THEN updated_at END DESC,
    system_name ASC
LIMIT $8::integer OFFSET $7::integer
`

type WeaveListFieldsParams struct {
	ProjectID    string `json:"project_id"`
	Search       string `json:"search"`
	Status       string `json:"status"`
	OwnerID      string `json:"owner_id"`
	SortBy       string `json:"sort_by"`
	SortDesc     bool   `json:"sort_desc"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type WeaveListFieldsRow struct {
	ID                string    `json:"id"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	SemanticID        *string   `json:"semantic_id"`
	SystemName        *string   `json:"system_name"`
	UiName            []byte    `json:"ui_name"`
	Description       []byte    `json:"description"`
	Status            string    `json:"status"`
	ProjectID         string    `json:"project_id"`
	OntologyScope     []byte    `json:"ontology_scope"`
	OntologyPath      *string   `json:"ontology_path"`
	PathElements      []byte    `json:"path_elements"`
	ExpectedValueType *string   `json:"expected_value_type"`
	Examples          []byte    `json:"examples"`
	StagingID         *int64    `json:"staging_id"`
	Deprecated        bool      `json:"deprecated"`
	SubfieldPaths     []byte    `json:"subfield_paths"`
}

func (q *Queries) WeaveListFields(ctx context.Context, arg WeaveListFieldsParams) ([]WeaveListFieldsRow, error) {
	rows, err := q.db.Query(ctx, weaveListFields,
		arg.ProjectID,
		arg.Search,
		arg.Status,
		arg.OwnerID,
		arg.SortBy,
		arg.SortDesc,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListFieldsRow{}
	for rows.Next() {
		var i WeaveListFieldsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.OntologyPath,
			&i.PathElements,
			&i.ExpectedValueType,
			&i.Examples,
			&i.StagingID,
			&i.Deprecated,
			&i.SubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListReceiptFieldClosure = `-- name: WeaveListReceiptFieldClosure :many
WITH RECURSIVE walk(kind, id) AS (
    SELECT $2::text AS kind, $1::text AS id
  UNION
    SELECT nxt.kind, nxt.id
    FROM walk w
    JOIN weave_field_overrides o ON o.entity_type = w.kind AND o.entity_id = w.id
    JOIN weave_override_refs r ON r.override_id = o.id
    CROSS JOIN LATERAL (
      SELECT 'model'::text AS kind, m.id
      FROM weave_models m
      WHERE m.id = r.target_id AND r.ref_type = 'resource_model'
      UNION ALL
      SELECT 'collection'::text, c.id
      FROM weave_collections c
      WHERE c.id = r.target_id AND r.ref_type = 'collection_model'
    ) nxt
)
SELECT DISTINCT o.field_id
FROM walk w
JOIN weave_field_overrides o ON o.entity_type = w.kind AND o.entity_id = w.id
WHERE COALESCE(o.field_id, '') <> ''
ORDER BY o.field_id
`

type WeaveListReceiptFieldClosureParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// Returns every field used by any override anywhere in the
// model+collection transitive closure rooted at the receipt seed.
// Drives the per-receipt bill-of-materials. The closure walks the
// override-ref graph (same shape as the model/collection closure);
// the final SELECT pulls field_id out of every override row in the
// walked set.
//
// For a seed of kind 'field', the walker can't recurse (fields don't
// have override refs), so the closure is empty here — that edge case
// is handled at the handler level by short-circuiting with the seed
// field itself.
func (q *Queries) WeaveListReceiptFieldClosure(ctx context.Context, arg WeaveListReceiptFieldClosureParams) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveListReceiptFieldClosure, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var field_id string
		if err := rows.Scan(&field_id); err != nil {
			return nil, err
		}
		items = append(items, field_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListReceiptFieldDirect = `-- name: WeaveListReceiptFieldDirect :many
SELECT DISTINCT field_id
FROM weave_field_overrides
WHERE entity_type = $2::text
  AND entity_id = $1::text
  AND COALESCE(field_id, '') <> ''
`

type WeaveListReceiptFieldDirectParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// Direct (depth-1) field references from the receipt seed — every
// field used by an override attached directly to the seed entity.
// For a model seed this is the model's own field set; for a
// collection seed it's the collection's field set; for a field seed
// it's the field itself. Pairs with WeaveListReceiptFieldClosure for
// the direct-vs-transitive count split.
func (q *Queries) WeaveListReceiptFieldDirect(ctx context.Context, arg WeaveListReceiptFieldDirectParams) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveListReceiptFieldDirect, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var field_id string
		if err := rows.Scan(&field_id); err != nil {
			return nil, err
		}
		items = append(items, field_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListReferenceAdoptedFields = `-- name: WeaveListReferenceAdoptedFields :many
SELECT DISTINCT f.id, f.created_at, f.updated_at, f.semantic_id, f.system_name, f.ui_name, f.description, f.status, f.project_id, f.ontology_scope, f.ontology_path, f.path_elements, f.expected_value_type, f.examples, f.staging_id, f.deprecated, f.version_number, f.subfield_paths
FROM weave_fields f
JOIN weave_field_overrides o ON o.field_id = f.id
WHERE o.project_id = $1
  AND f.project_id <> $1
ORDER BY f.id
`

// Returns every field from another project that the current project's
// field overrides reference via field_id. Drives the
// "Adopted (by reference)" slice of the field list rule (adopt/adapt
// rollout plan, task 3b). Only counts overrides whose entity_type
// belongs to the current project (model or collection overrides
// locally authored).
func (q *Queries) WeaveListReferenceAdoptedFields(ctx context.Context, projectID string) ([]WeaveField, error) {
	rows, err := q.db.Query(ctx, weaveListReferenceAdoptedFields, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveField{}
	for rows.Next() {
		var i WeaveField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.OntologyPath,
			&i.PathElements,
			&i.ExpectedValueType,
			&i.Examples,
			&i.StagingID,
			&i.Deprecated,
			&i.VersionNumber,
			&i.SubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSetFieldSubfieldPaths = `-- name: WeaveSetFieldSubfieldPaths :exec
UPDATE weave_fields SET subfield_paths = $2, updated_at = NOW() WHERE id = $1
`

type WeaveSetFieldSubfieldPathsParams struct {
	ID            string `json:"id"`
	SubfieldPaths []byte `json:"subfield_paths"`
}

// Restore-only companion to WeaveCreateField/WeaveUpdateField, which do not
// carry the legacy subfield_paths column: git restore must round-trip it
// losslessly without widening the live create/update surface.
func (q *Queries) WeaveSetFieldSubfieldPaths(ctx context.Context, arg WeaveSetFieldSubfieldPathsParams) error {
	_, err := q.db.Exec(ctx, weaveSetFieldSubfieldPaths, arg.ID, arg.SubfieldPaths)
	return err
}

const weaveUpdateField = `-- name: WeaveUpdateField :one
UPDATE weave_fields SET
    updated_at = NOW(),
    ui_name = $2,
    description = $3,
    system_name = $4,
    status = $5,
    ontology_scope = $6,
    ontology_path = $7,
    path_elements = $8,
    expected_value_type = $9,
    examples = $10
WHERE id = $1
RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, ontology_scope, ontology_path, path_elements, expected_value_type, examples, staging_id, deprecated, version_number, subfield_paths
`

type WeaveUpdateFieldParams struct {
	ID                string  `json:"id"`
	UiName            []byte  `json:"ui_name"`
	Description       []byte  `json:"description"`
	SystemName        *string `json:"system_name"`
	Status            string  `json:"status"`
	OntologyScope     []byte  `json:"ontology_scope"`
	OntologyPath      *string `json:"ontology_path"`
	PathElements      []byte  `json:"path_elements"`
	ExpectedValueType *string `json:"expected_value_type"`
	Examples          []byte  `json:"examples"`
}

func (q *Queries) WeaveUpdateField(ctx context.Context, arg WeaveUpdateFieldParams) (WeaveField, error) {
	row := q.db.QueryRow(ctx, weaveUpdateField,
		arg.ID,
		arg.UiName,
		arg.Description,
		arg.SystemName,
		arg.Status,
		arg.OntologyScope,
		arg.OntologyPath,
		arg.PathElements,
		arg.ExpectedValueType,
		arg.Examples,
	)
	var i WeaveField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.OntologyPath,
		&i.PathElements,
		&i.ExpectedValueType,
		&i.Examples,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.SubfieldPaths,
	)
	return i, err
}

const weaveUpsertField = `-- name: WeaveUpsertField :one
INSERT INTO weave_fields (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id,
    ontology_scope, ontology_path, path_elements,
    expected_value_type, examples,
    staging_id, subfield_paths
) VALUES (
    $1, NOW(), NOW(), $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14
)
ON CONFLICT (id) DO UPDATE SET
    updated_at = NOW(),
    semantic_id = EXCLUDED.semantic_id,
    system_name = EXCLUDED.system_name,
    ui_name = EXCLUDED.ui_name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    project_id = EXCLUDED.project_id,
    ontology_scope = EXCLUDED.ontology_scope,
    ontology_path = EXCLUDED.ontology_path,
    path_elements = EXCLUDED.path_elements,
    expected_value_type = EXCLUDED.expected_value_type,
    examples = EXCLUDED.examples,
    staging_id = EXCLUDED.staging_id,
    subfield_paths = EXCLUDED.subfield_paths
RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, ontology_scope, ontology_path, path_elements, expected_value_type, examples, staging_id, deprecated, version_number, subfield_paths
`

type WeaveUpsertFieldParams struct {
	ID                string  `json:"id"`
	SemanticID        *string `json:"semantic_id"`
	SystemName        *string `json:"system_name"`
	UiName            []byte  `json:"ui_name"`
	Description       []byte  `json:"description"`
	Status            string  `json:"status"`
	ProjectID         string  `json:"project_id"`
	OntologyScope     []byte  `json:"ontology_scope"`
	OntologyPath      *string `json:"ontology_path"`
	PathElements      []byte  `json:"path_elements"`
	ExpectedValueType *string `json:"expected_value_type"`
	Examples          []byte  `json:"examples"`
	StagingID         *int64  `json:"staging_id"`
	SubfieldPaths     []byte  `json:"subfield_paths"`
}

func (q *Queries) WeaveUpsertField(ctx context.Context, arg WeaveUpsertFieldParams) (WeaveField, error) {
	row := q.db.QueryRow(ctx, weaveUpsertField,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.OntologyScope,
		arg.OntologyPath,
		arg.PathElements,
		arg.ExpectedValueType,
		arg.Examples,
		arg.StagingID,
		arg.SubfieldPaths,
	)
	var i WeaveField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.OntologyPath,
		&i.PathElements,
		&i.ExpectedValueType,
		&i.Examples,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.SubfieldPaths,
	)
	return i, err
}
