// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_field_ontology_refs.sql

package sqlcgen

import (
	"context"
)

const weaveCountFieldsUsingOntologyVersion = `-- name: WeaveCountFieldsUsingOntologyVersion :one
SELECT count(DISTINCT r.field_id)::bigint
FROM weave_field_ontology_refs r
WHERE r.project_id = $1
  AND (
    EXISTS (
      SELECT 1 FROM weave_ontology_classes c
      WHERE c.ontology_version_id = $2
        AND c.qname = r.qname
    )
    OR EXISTS (
      SELECT 1 FROM weave_ontology_properties p
      WHERE p.ontology_version_id = $2
        AND p.qname = r.qname
    )
  )
`

type WeaveCountFieldsUsingOntologyVersionParams struct {
	ProjectID         string `json:"project_id"`
	OntologyVersionID string `json:"ontology_version_id"`
}

// Used by pkg/weave/projectontologyversion.Service.Delete preflight.
// Returns the number of distinct fields in the project that reference
// a qname defined in the given ontology version.
func (q *Queries) WeaveCountFieldsUsingOntologyVersion(ctx context.Context, arg WeaveCountFieldsUsingOntologyVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountFieldsUsingOntologyVersion, arg.ProjectID, arg.OntologyVersionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveCountFieldsUsingQname = `-- name: WeaveCountFieldsUsingQname :one
SELECT count(DISTINCT field_id)::bigint
FROM weave_field_ontology_refs
WHERE project_id = $1 AND qname = $2
`

type WeaveCountFieldsUsingQnameParams struct {
	ProjectID string  `json:"project_id"`
	Qname     *string `json:"qname"`
}

func (q *Queries) WeaveCountFieldsUsingQname(ctx context.Context, arg WeaveCountFieldsUsingQnameParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountFieldsUsingQname, arg.ProjectID, arg.Qname)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveDeleteFieldOntologyRefs = `-- name: WeaveDeleteFieldOntologyRefs :exec
DELETE FROM weave_field_ontology_refs WHERE field_id = $1
`

// Bulk-delete refs for a single field. Field-slice rebuild flow:
//
//	tx.WeaveDeleteFieldOntologyRefs(field_id)
//	for each path element: tx.WeaveInsertFieldOntologyRef(...)
func (q *Queries) WeaveDeleteFieldOntologyRefs(ctx context.Context, fieldID string) error {
	_, err := q.db.Exec(ctx, weaveDeleteFieldOntologyRefs, fieldID)
	return err
}

const weaveFindFieldsUsingQname = `-- name: WeaveFindFieldsUsingQname :many
SELECT DISTINCT field_id
FROM weave_field_ontology_refs
WHERE project_id = $1 AND qname = $2
ORDER BY field_id ASC
LIMIT $3
`

type WeaveFindFieldsUsingQnameParams struct {
	ProjectID string  `json:"project_id"`
	Qname     *string `json:"qname"`
	Limit     int32   `json:"limit"`
}

// "Which fields in this project reference this qname?" — drives the
// reverse-lookup feature in the ontology explorer + unlink-preflight.
func (q *Queries) WeaveFindFieldsUsingQname(ctx context.Context, arg WeaveFindFieldsUsingQnameParams) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveFindFieldsUsingQname, arg.ProjectID, arg.Qname, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var field_id string
		if err := rows.Scan(&field_id); err != nil {
			return nil, err
		}
		items = append(items, field_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveInsertFieldOntologyRef = `-- name: WeaveInsertFieldOntologyRef :exec
INSERT INTO weave_field_ontology_refs (
    field_id, project_id, prefix, local_name, position, ref_kind
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (field_id, position) DO NOTHING
`

type WeaveInsertFieldOntologyRefParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
	Prefix    string `json:"prefix"`
	LocalName string `json:"local_name"`
	Position  int32  `json:"position"`
	RefKind   string `json:"ref_kind"`
}

func (q *Queries) WeaveInsertFieldOntologyRef(ctx context.Context, arg WeaveInsertFieldOntologyRefParams) error {
	_, err := q.db.Exec(ctx, weaveInsertFieldOntologyRef,
		arg.FieldID,
		arg.ProjectID,
		arg.Prefix,
		arg.LocalName,
		arg.Position,
		arg.RefKind,
	)
	return err
}

const weaveListFieldOntologyRefs = `-- name: WeaveListFieldOntologyRefs :many
SELECT field_id, project_id, prefix, local_name, qname, position, ref_kind FROM weave_field_ontology_refs
WHERE field_id = $1
ORDER BY position ASC
`

func (q *Queries) WeaveListFieldOntologyRefs(ctx context.Context, fieldID string) ([]WeaveFieldOntologyRef, error) {
	rows, err := q.db.Query(ctx, weaveListFieldOntologyRefs, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveFieldOntologyRef{}
	for rows.Next() {
		var i WeaveFieldOntologyRef
		if err := rows.Scan(
			&i.FieldID,
			&i.ProjectID,
			&i.Prefix,
			&i.LocalName,
			&i.Qname,
			&i.Position,
			&i.RefKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveOntologyUsageByProject = `-- name: WeaveOntologyUsageByProject :one
WITH path_steps AS (
    SELECT
        elem->>'prefix' AS prefix,
        elem->>'local_name' AS local_name,
        elem->>'type' AS step_type
    FROM weave_fields f,
         LATERAL jsonb_array_elements(coalesce(f.path_elements, '[]'::jsonb)) AS elem
    WHERE f.project_id = $1
      AND f.path_elements IS NOT NULL
), project_qnames AS (
    SELECT (prefix || ':' || local_name) AS qname, step_type AS kind
    FROM path_steps
    WHERE coalesce(prefix, '') <> '' AND coalesce(local_name, '') <> ''
    UNION
    SELECT (ontology_scope->>'prefix') || ':' || (ontology_scope->>'local_name') AS qname,
           'class'::text AS kind
    FROM weave_models
    WHERE project_id = $1
      AND ontology_scope ? 'prefix' AND ontology_scope ? 'local_name'
      AND coalesce(ontology_scope->>'prefix', '') <> ''
      AND coalesce(ontology_scope->>'local_name', '') <> ''
    UNION
    SELECT (ontology_scope->>'prefix') || ':' || (ontology_scope->>'local_name') AS qname,
           'class'::text AS kind
    FROM weave_collections
    WHERE project_id = $1
      AND ontology_scope ? 'prefix' AND ontology_scope ? 'local_name'
      AND coalesce(ontology_scope->>'prefix', '') <> ''
      AND coalesce(ontology_scope->>'local_name', '') <> ''
    UNION
    SELECT (ontology_scope->>'prefix') || ':' || (ontology_scope->>'local_name') AS qname,
           'class'::text AS kind
    FROM weave_fields
    WHERE project_id = $1
      AND ontology_scope ? 'prefix' AND ontology_scope ? 'local_name'
      AND coalesce(ontology_scope->>'prefix', '') <> ''
      AND coalesce(ontology_scope->>'local_name', '') <> ''
)
SELECT
    (
        SELECT count(DISTINCT c.qname)::bigint
        FROM weave_ontology_classes c
        WHERE c.ontology_version_id = $2
          AND c.qname IN (SELECT qname FROM project_qnames)
    ) AS classes_used,
    (
        SELECT count(DISTINCT p.qname)::bigint
        FROM weave_ontology_properties p
        WHERE p.ontology_version_id = $2
          AND p.qname IN (SELECT qname FROM project_qnames)
    ) AS properties_used
`

type WeaveOntologyUsageByProjectParams struct {
	ProjectID         string `json:"project_id"`
	OntologyVersionID string `json:"ontology_version_id"`
}

type WeaveOntologyUsageByProjectRow struct {
	ClassesUsed    int64 `json:"classes_used"`
	PropertiesUsed int64 `json:"properties_used"`
}

// "How many distinct classes/properties from this ontology version are
// referenced by this project?" Drives the "Deployed Ontologies" card on
// the project overview.
//
// Walks every field's path_elements JSONB array directly so the count
// reflects every class and property the project actually traverses, not
// just root scope classes. Used to read from weave_field_ontology_refs
// (a materialised projection of the same data) but that table was
// never populated by the field write path, so properties always read
// as zero. Reading path_elements inline keeps the count
// correct without depending on a materialisation step.
//
// "Referenced" combines:
//  1. every step of every field's path_elements (class or property)
//  2. entity scope classes — the ontology_scope on each model /
//     collection / field row, so a class set as a collection's main
//     scope but never traversed by a field still counts.
func (q *Queries) WeaveOntologyUsageByProject(ctx context.Context, arg WeaveOntologyUsageByProjectParams) (WeaveOntologyUsageByProjectRow, error) {
	row := q.db.QueryRow(ctx, weaveOntologyUsageByProject, arg.ProjectID, arg.OntologyVersionID)
	var i WeaveOntologyUsageByProjectRow
	err := row.Scan(&i.ClassesUsed, &i.PropertiesUsed)
	return i, err
}

const weaveSampleFieldsUsingOntologyVersion = `-- name: WeaveSampleFieldsUsingOntologyVersion :many
SELECT DISTINCT r.field_id, r.qname
FROM weave_field_ontology_refs r
WHERE r.project_id = $1
  AND (
    EXISTS (
      SELECT 1 FROM weave_ontology_classes c
      WHERE c.ontology_version_id = $2
        AND c.qname = r.qname
    )
    OR EXISTS (
      SELECT 1 FROM weave_ontology_properties p
      WHERE p.ontology_version_id = $2
        AND p.qname = r.qname
    )
  )
ORDER BY r.field_id ASC
LIMIT $3
`

type WeaveSampleFieldsUsingOntologyVersionParams struct {
	ProjectID         string `json:"project_id"`
	OntologyVersionID string `json:"ontology_version_id"`
	Limit             int32  `json:"limit"`
}

type WeaveSampleFieldsUsingOntologyVersionRow struct {
	FieldID string  `json:"field_id"`
	Qname   *string `json:"qname"`
}

// Sample field IDs that block an unlink (return up to N for the 409
// response payload). Used by the unlink-preflight to show which fields
// reference qnames defined in the version being unlinked.
func (q *Queries) WeaveSampleFieldsUsingOntologyVersion(ctx context.Context, arg WeaveSampleFieldsUsingOntologyVersionParams) ([]WeaveSampleFieldsUsingOntologyVersionRow, error) {
	rows, err := q.db.Query(ctx, weaveSampleFieldsUsingOntologyVersion, arg.ProjectID, arg.OntologyVersionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveSampleFieldsUsingOntologyVersionRow{}
	for rows.Next() {
		var i WeaveSampleFieldsUsingOntologyVersionRow
		if err := rows.Scan(&i.FieldID, &i.Qname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
