// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_ontology_families.sql

package sqlcgen

import (
	"context"
)

const weaveCountOntologiesInFamily = `-- name: WeaveCountOntologiesInFamily :one
SELECT count(*)::bigint FROM weave_ontologies WHERE family_id = $1
`

func (q *Queries) WeaveCountOntologiesInFamily(ctx context.Context, familyID *string) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountOntologiesInFamily, familyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveCreateOntologyFamily = `-- name: WeaveCreateOntologyFamily :one
INSERT INTO weave_ontology_families (
    id, slug, name, description, parent_family_id,
    homepage_url, icon, display_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, name, description, parent_family_id, homepage_url, icon, display_order, created_at, updated_at
`

type WeaveCreateOntologyFamilyParams struct {
	ID             string  `json:"id"`
	Slug           string  `json:"slug"`
	Name           string  `json:"name"`
	Description    []byte  `json:"description"`
	ParentFamilyID *string `json:"parent_family_id"`
	HomepageUrl    *string `json:"homepage_url"`
	Icon           *string `json:"icon"`
	DisplayOrder   int64   `json:"display_order"`
}

func (q *Queries) WeaveCreateOntologyFamily(ctx context.Context, arg WeaveCreateOntologyFamilyParams) (WeaveOntologyFamily, error) {
	row := q.db.QueryRow(ctx, weaveCreateOntologyFamily,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ParentFamilyID,
		arg.HomepageUrl,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i WeaveOntologyFamily
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentFamilyID,
		&i.HomepageUrl,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveDeleteOntologyFamily = `-- name: WeaveDeleteOntologyFamily :exec
DELETE FROM weave_ontology_families WHERE id = $1
`

func (q *Queries) WeaveDeleteOntologyFamily(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteOntologyFamily, id)
	return err
}

const weaveGetOntologyFamilyByID = `-- name: WeaveGetOntologyFamilyByID :one
SELECT id, slug, name, description, parent_family_id, homepage_url, icon, display_order, created_at, updated_at FROM weave_ontology_families WHERE id = $1
`

func (q *Queries) WeaveGetOntologyFamilyByID(ctx context.Context, id string) (WeaveOntologyFamily, error) {
	row := q.db.QueryRow(ctx, weaveGetOntologyFamilyByID, id)
	var i WeaveOntologyFamily
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentFamilyID,
		&i.HomepageUrl,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveGetOntologyFamilyBySlug = `-- name: WeaveGetOntologyFamilyBySlug :one
SELECT id, slug, name, description, parent_family_id, homepage_url, icon, display_order, created_at, updated_at FROM weave_ontology_families WHERE slug = $1
`

func (q *Queries) WeaveGetOntologyFamilyBySlug(ctx context.Context, slug string) (WeaveOntologyFamily, error) {
	row := q.db.QueryRow(ctx, weaveGetOntologyFamilyBySlug, slug)
	var i WeaveOntologyFamily
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentFamilyID,
		&i.HomepageUrl,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveListChildOntologyFamilies = `-- name: WeaveListChildOntologyFamilies :many
SELECT id, slug, name, description, parent_family_id, homepage_url, icon, display_order, created_at, updated_at FROM weave_ontology_families
WHERE parent_family_id = $1
ORDER BY display_order ASC, name ASC
`

func (q *Queries) WeaveListChildOntologyFamilies(ctx context.Context, parentFamilyID *string) ([]WeaveOntologyFamily, error) {
	rows, err := q.db.Query(ctx, weaveListChildOntologyFamilies, parentFamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyFamily{}
	for rows.Next() {
		var i WeaveOntologyFamily
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ParentFamilyID,
			&i.HomepageUrl,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOntologyFamilies = `-- name: WeaveListOntologyFamilies :many
SELECT id, slug, name, description, parent_family_id, homepage_url, icon, display_order, created_at, updated_at FROM weave_ontology_families
ORDER BY display_order ASC, name ASC
`

func (q *Queries) WeaveListOntologyFamilies(ctx context.Context) ([]WeaveOntologyFamily, error) {
	rows, err := q.db.Query(ctx, weaveListOntologyFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyFamily{}
	for rows.Next() {
		var i WeaveOntologyFamily
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ParentFamilyID,
			&i.HomepageUrl,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListRootOntologyFamilies = `-- name: WeaveListRootOntologyFamilies :many
SELECT id, slug, name, description, parent_family_id, homepage_url, icon, display_order, created_at, updated_at FROM weave_ontology_families
WHERE parent_family_id IS NULL
ORDER BY display_order ASC, name ASC
`

func (q *Queries) WeaveListRootOntologyFamilies(ctx context.Context) ([]WeaveOntologyFamily, error) {
	rows, err := q.db.Query(ctx, weaveListRootOntologyFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyFamily{}
	for rows.Next() {
		var i WeaveOntologyFamily
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ParentFamilyID,
			&i.HomepageUrl,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveUpdateOntologyFamily = `-- name: WeaveUpdateOntologyFamily :one
UPDATE weave_ontology_families
SET slug = $2,
    name = $3,
    description = $4,
    parent_family_id = $5,
    homepage_url = $6,
    icon = $7,
    display_order = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, name, description, parent_family_id, homepage_url, icon, display_order, created_at, updated_at
`

type WeaveUpdateOntologyFamilyParams struct {
	ID             string  `json:"id"`
	Slug           string  `json:"slug"`
	Name           string  `json:"name"`
	Description    []byte  `json:"description"`
	ParentFamilyID *string `json:"parent_family_id"`
	HomepageUrl    *string `json:"homepage_url"`
	Icon           *string `json:"icon"`
	DisplayOrder   int64   `json:"display_order"`
}

func (q *Queries) WeaveUpdateOntologyFamily(ctx context.Context, arg WeaveUpdateOntologyFamilyParams) (WeaveOntologyFamily, error) {
	row := q.db.QueryRow(ctx, weaveUpdateOntologyFamily,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ParentFamilyID,
		arg.HomepageUrl,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i WeaveOntologyFamily
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentFamilyID,
		&i.HomepageUrl,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
