// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_namespace_bindings.sql

package sqlcgen

import (
	"context"
)

const weaveCreateUserNamespaceBinding = `-- name: WeaveCreateUserNamespaceBinding :one
INSERT INTO weave_namespace_bindings (
    id, project_id, prefix, namespace, weight, source, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, 'user', now(), now())
RETURNING id, created_at, updated_at, airtable_raw, airtable_context, airtable_ref, semantic_id, long_semantic_id, system_name, ui_name, description, uri, project_id, prefix, namespace, weight, source, ontology_id, version_number
`

type WeaveCreateUserNamespaceBindingParams struct {
	ID        string  `json:"id"`
	ProjectID *string `json:"project_id"`
	Prefix    string  `json:"prefix"`
	Namespace string  `json:"namespace"`
	Weight    int64   `json:"weight"`
}

// Caller generates the ULID id (matches BaseModel convention); sqlc sets source='user'.
func (q *Queries) WeaveCreateUserNamespaceBinding(ctx context.Context, arg WeaveCreateUserNamespaceBindingParams) (WeaveNamespaceBinding, error) {
	row := q.db.QueryRow(ctx, weaveCreateUserNamespaceBinding,
		arg.ID,
		arg.ProjectID,
		arg.Prefix,
		arg.Namespace,
		arg.Weight,
	)
	var i WeaveNamespaceBinding
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AirtableRaw,
		&i.AirtableContext,
		&i.AirtableRef,
		&i.SemanticID,
		&i.LongSemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Uri,
		&i.ProjectID,
		&i.Prefix,
		&i.Namespace,
		&i.Weight,
		&i.Source,
		&i.OntologyID,
		&i.VersionNumber,
	)
	return i, err
}

const weaveDeleteGlobalUserNamespaceBinding = `-- name: WeaveDeleteGlobalUserNamespaceBinding :exec
DELETE FROM weave_namespace_bindings
WHERE id = $1 AND source = 'user' AND (project_id IS NULL OR project_id = '')
`

func (q *Queries) WeaveDeleteGlobalUserNamespaceBinding(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteGlobalUserNamespaceBinding, id)
	return err
}

const weaveDeleteUserNamespaceBinding = `-- name: WeaveDeleteUserNamespaceBinding :exec
DELETE FROM weave_namespace_bindings
WHERE id = $1 AND project_id = $2 AND source = 'user'
`

type WeaveDeleteUserNamespaceBindingParams struct {
	ID        string  `json:"id"`
	ProjectID *string `json:"project_id"`
}

// Only deletes rows where source='user'; system rows are unaffected.
func (q *Queries) WeaveDeleteUserNamespaceBinding(ctx context.Context, arg WeaveDeleteUserNamespaceBindingParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteUserNamespaceBinding, arg.ID, arg.ProjectID)
	return err
}

const weaveGetNamespaceBinding = `-- name: WeaveGetNamespaceBinding :one
SELECT id, created_at, updated_at, airtable_raw, airtable_context, airtable_ref, semantic_id, long_semantic_id, system_name, ui_name, description, uri, project_id, prefix, namespace, weight, source, ontology_id, version_number FROM weave_namespace_bindings
WHERE id = $1
`

func (q *Queries) WeaveGetNamespaceBinding(ctx context.Context, id string) (WeaveNamespaceBinding, error) {
	row := q.db.QueryRow(ctx, weaveGetNamespaceBinding, id)
	var i WeaveNamespaceBinding
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AirtableRaw,
		&i.AirtableContext,
		&i.AirtableRef,
		&i.SemanticID,
		&i.LongSemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Uri,
		&i.ProjectID,
		&i.Prefix,
		&i.Namespace,
		&i.Weight,
		&i.Source,
		&i.OntologyID,
		&i.VersionNumber,
	)
	return i, err
}

const weaveGlobalNamespaceBindingUsageByProject = `-- name: WeaveGlobalNamespaceBindingUsageByProject :many
WITH field_usage AS (
  SELECT
    f.project_id,
    COUNT(*)::bigint AS field_count
  FROM weave_fields f
  WHERE
    f.ontology_scope->>'prefix' = $1::text
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(f.path_elements, '[]'::jsonb)) pe
      WHERE pe->>'prefix' = $1::text
    )
  GROUP BY f.project_id
),
model_usage AS (
  SELECT
    m.project_id,
    COUNT(*)::bigint AS model_count
  FROM weave_models m
  WHERE m.ontology_scope->>'prefix' = $1::text
  GROUP BY m.project_id
),
collection_usage AS (
  SELECT
    c.project_id,
    COUNT(*)::bigint AS collection_count
  FROM weave_collections c
  WHERE c.ontology_scope->>'prefix' = $1::text
  GROUP BY c.project_id
)
SELECT
  p.id AS project_id,
  COALESCE(f.field_count, 0)::bigint AS field_count,
  COALESCE(m.model_count, 0)::bigint AS model_count,
  COALESCE(c.collection_count, 0)::bigint AS collection_count
FROM weave_projects p
LEFT JOIN field_usage f ON f.project_id = p.id
LEFT JOIN model_usage m ON m.project_id = p.id
LEFT JOIN collection_usage c ON c.project_id = p.id
WHERE COALESCE(f.field_count, 0) + COALESCE(m.model_count, 0) + COALESCE(c.collection_count, 0) > 0
ORDER BY
  (COALESCE(f.field_count, 0) + COALESCE(m.model_count, 0) + COALESCE(c.collection_count, 0)) DESC,
  p.id ASC
`

type WeaveGlobalNamespaceBindingUsageByProjectRow struct {
	ProjectID       string `json:"project_id"`
	FieldCount      int64  `json:"field_count"`
	ModelCount      int64  `json:"model_count"`
	CollectionCount int64  `json:"collection_count"`
}

func (q *Queries) WeaveGlobalNamespaceBindingUsageByProject(ctx context.Context, dollar_1 string) ([]WeaveGlobalNamespaceBindingUsageByProjectRow, error) {
	rows, err := q.db.Query(ctx, weaveGlobalNamespaceBindingUsageByProject, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveGlobalNamespaceBindingUsageByProjectRow{}
	for rows.Next() {
		var i WeaveGlobalNamespaceBindingUsageByProjectRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.FieldCount,
			&i.ModelCount,
			&i.CollectionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListGlobalNamespaceBindings = `-- name: WeaveListGlobalNamespaceBindings :many
SELECT id, created_at, updated_at, airtable_raw, airtable_context, airtable_ref, semantic_id, long_semantic_id, system_name, ui_name, description, uri, project_id, prefix, namespace, weight, source, ontology_id, version_number FROM weave_namespace_bindings
WHERE project_id IS NULL OR project_id = ''
ORDER BY weight ASC, prefix ASC
`

func (q *Queries) WeaveListGlobalNamespaceBindings(ctx context.Context) ([]WeaveNamespaceBinding, error) {
	rows, err := q.db.Query(ctx, weaveListGlobalNamespaceBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveNamespaceBinding{}
	for rows.Next() {
		var i WeaveNamespaceBinding
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AirtableRaw,
			&i.AirtableContext,
			&i.AirtableRef,
			&i.SemanticID,
			&i.LongSemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Uri,
			&i.ProjectID,
			&i.Prefix,
			&i.Namespace,
			&i.Weight,
			&i.Source,
			&i.OntologyID,
			&i.VersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListNamespaceBindings = `-- name: WeaveListNamespaceBindings :many
SELECT id, created_at, updated_at, airtable_raw, airtable_context, airtable_ref, semantic_id, long_semantic_id, system_name, ui_name, description, uri, project_id, prefix, namespace, weight, source, ontology_id, version_number FROM weave_namespace_bindings
WHERE project_id IS NULL OR project_id = '' OR project_id = $1
ORDER BY weight ASC, prefix ASC
`

// Returns global bindings (project_id IS NULL or empty string) plus rows
// belonging to the given project. Legacy seed data uses empty string for
// global; migration 022 added the column as nullable so newer rows may be NULL.
func (q *Queries) WeaveListNamespaceBindings(ctx context.Context, projectID *string) ([]WeaveNamespaceBinding, error) {
	rows, err := q.db.Query(ctx, weaveListNamespaceBindings, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveNamespaceBinding{}
	for rows.Next() {
		var i WeaveNamespaceBinding
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AirtableRaw,
			&i.AirtableContext,
			&i.AirtableRef,
			&i.SemanticID,
			&i.LongSemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Uri,
			&i.ProjectID,
			&i.Prefix,
			&i.Namespace,
			&i.Weight,
			&i.Source,
			&i.OntologyID,
			&i.VersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weavePrefixNamespaceBindingExists = `-- name: WeavePrefixNamespaceBindingExists :one
SELECT EXISTS(
  SELECT 1 FROM weave_namespace_bindings
  WHERE prefix = $1 AND namespace = $2 AND id <> $3
)
`

type WeavePrefixNamespaceBindingExistsParams struct {
	Prefix    string `json:"prefix"`
	Namespace string `json:"namespace"`
	ID        string `json:"id"`
}

// Duplicate check aligned with the (prefix, namespace) unique index.
// Excludes the row being updated via the third parameter.
func (q *Queries) WeavePrefixNamespaceBindingExists(ctx context.Context, arg WeavePrefixNamespaceBindingExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, weavePrefixNamespaceBindingExists, arg.Prefix, arg.Namespace, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const weaveUpdateGlobalUserNamespaceBinding = `-- name: WeaveUpdateGlobalUserNamespaceBinding :one
UPDATE weave_namespace_bindings
SET prefix     = $2,
    namespace  = $3,
    weight     = $4,
    updated_at = now()
WHERE id = $1 AND source = 'user' AND (project_id IS NULL OR project_id = '')
RETURNING id, created_at, updated_at, airtable_raw, airtable_context, airtable_ref, semantic_id, long_semantic_id, system_name, ui_name, description, uri, project_id, prefix, namespace, weight, source, ontology_id, version_number
`

type WeaveUpdateGlobalUserNamespaceBindingParams struct {
	ID        string `json:"id"`
	Prefix    string `json:"prefix"`
	Namespace string `json:"namespace"`
	Weight    int64  `json:"weight"`
}

func (q *Queries) WeaveUpdateGlobalUserNamespaceBinding(ctx context.Context, arg WeaveUpdateGlobalUserNamespaceBindingParams) (WeaveNamespaceBinding, error) {
	row := q.db.QueryRow(ctx, weaveUpdateGlobalUserNamespaceBinding,
		arg.ID,
		arg.Prefix,
		arg.Namespace,
		arg.Weight,
	)
	var i WeaveNamespaceBinding
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AirtableRaw,
		&i.AirtableContext,
		&i.AirtableRef,
		&i.SemanticID,
		&i.LongSemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Uri,
		&i.ProjectID,
		&i.Prefix,
		&i.Namespace,
		&i.Weight,
		&i.Source,
		&i.OntologyID,
		&i.VersionNumber,
	)
	return i, err
}

const weaveUpdateUserNamespaceBinding = `-- name: WeaveUpdateUserNamespaceBinding :one
UPDATE weave_namespace_bindings
SET prefix     = $3,
    namespace  = $4,
    weight     = $5,
    updated_at = now()
WHERE id = $1 AND project_id = $2 AND source = 'user'
RETURNING id, created_at, updated_at, airtable_raw, airtable_context, airtable_ref, semantic_id, long_semantic_id, system_name, ui_name, description, uri, project_id, prefix, namespace, weight, source, ontology_id, version_number
`

type WeaveUpdateUserNamespaceBindingParams struct {
	ID        string  `json:"id"`
	ProjectID *string `json:"project_id"`
	Prefix    string  `json:"prefix"`
	Namespace string  `json:"namespace"`
	Weight    int64   `json:"weight"`
}

// Only affects rows where source='user'; system rows return 0 affected.
func (q *Queries) WeaveUpdateUserNamespaceBinding(ctx context.Context, arg WeaveUpdateUserNamespaceBindingParams) (WeaveNamespaceBinding, error) {
	row := q.db.QueryRow(ctx, weaveUpdateUserNamespaceBinding,
		arg.ID,
		arg.ProjectID,
		arg.Prefix,
		arg.Namespace,
		arg.Weight,
	)
	var i WeaveNamespaceBinding
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AirtableRaw,
		&i.AirtableContext,
		&i.AirtableRef,
		&i.SemanticID,
		&i.LongSemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Uri,
		&i.ProjectID,
		&i.Prefix,
		&i.Namespace,
		&i.Weight,
		&i.Source,
		&i.OntologyID,
		&i.VersionNumber,
	)
	return i, err
}
