// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_project_integrations.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const weaveProjectIntegrationDelete = `-- name: WeaveProjectIntegrationDelete :exec
DELETE FROM weave_project_integrations
WHERE project_id = $1 AND integration_id = $2 AND config_id = $3
`

type WeaveProjectIntegrationDeleteParams struct {
	ProjectID     string `json:"project_id"`
	IntegrationID string `json:"integration_id"`
	ConfigID      string `json:"config_id"`
}

func (q *Queries) WeaveProjectIntegrationDelete(ctx context.Context, arg WeaveProjectIntegrationDeleteParams) error {
	_, err := q.db.Exec(ctx, weaveProjectIntegrationDelete, arg.ProjectID, arg.IntegrationID, arg.ConfigID)
	return err
}

const weaveProjectIntegrationGet = `-- name: WeaveProjectIntegrationGet :one
SELECT project_id, integration_id, enabled, config, secret_ref, created_at, updated_at, config_id, label, managed_instance_id FROM weave_project_integrations
WHERE project_id = $1 AND integration_id = $2 AND config_id = $3
`

type WeaveProjectIntegrationGetParams struct {
	ProjectID     string `json:"project_id"`
	IntegrationID string `json:"integration_id"`
	ConfigID      string `json:"config_id"`
}

func (q *Queries) WeaveProjectIntegrationGet(ctx context.Context, arg WeaveProjectIntegrationGetParams) (WeaveProjectIntegration, error) {
	row := q.db.QueryRow(ctx, weaveProjectIntegrationGet, arg.ProjectID, arg.IntegrationID, arg.ConfigID)
	var i WeaveProjectIntegration
	err := row.Scan(
		&i.ProjectID,
		&i.IntegrationID,
		&i.Enabled,
		&i.Config,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigID,
		&i.Label,
		&i.ManagedInstanceID,
	)
	return i, err
}

const weaveProjectIntegrationUpsert = `-- name: WeaveProjectIntegrationUpsert :one
INSERT INTO weave_project_integrations
    (project_id, integration_id, config_id, label, enabled, config, secret_ref, managed_instance_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (project_id, integration_id, config_id) DO UPDATE SET
    label               = EXCLUDED.label,
    enabled             = EXCLUDED.enabled,
    config              = EXCLUDED.config,
    secret_ref          = EXCLUDED.secret_ref,
    managed_instance_id = EXCLUDED.managed_instance_id,
    updated_at          = NOW()
RETURNING project_id, integration_id, enabled, config, secret_ref, created_at, updated_at, config_id, label, managed_instance_id
`

type WeaveProjectIntegrationUpsertParams struct {
	ProjectID         string          `json:"project_id"`
	IntegrationID     string          `json:"integration_id"`
	ConfigID          string          `json:"config_id"`
	Label             string          `json:"label"`
	Enabled           bool            `json:"enabled"`
	Config            json.RawMessage `json:"config"`
	SecretRef         *string         `json:"secret_ref"`
	ManagedInstanceID *string         `json:"managed_instance_id"`
}

func (q *Queries) WeaveProjectIntegrationUpsert(ctx context.Context, arg WeaveProjectIntegrationUpsertParams) (WeaveProjectIntegration, error) {
	row := q.db.QueryRow(ctx, weaveProjectIntegrationUpsert,
		arg.ProjectID,
		arg.IntegrationID,
		arg.ConfigID,
		arg.Label,
		arg.Enabled,
		arg.Config,
		arg.SecretRef,
		arg.ManagedInstanceID,
	)
	var i WeaveProjectIntegration
	err := row.Scan(
		&i.ProjectID,
		&i.IntegrationID,
		&i.Enabled,
		&i.Config,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigID,
		&i.Label,
		&i.ManagedInstanceID,
	)
	return i, err
}

const weaveProjectIntegrationsListEnabledForProject = `-- name: WeaveProjectIntegrationsListEnabledForProject :many
SELECT project_id, integration_id, enabled, config, secret_ref, created_at, updated_at, config_id, label, managed_instance_id FROM weave_project_integrations
WHERE project_id = $1 AND enabled = TRUE
ORDER BY integration_id, config_id
`

func (q *Queries) WeaveProjectIntegrationsListEnabledForProject(ctx context.Context, projectID string) ([]WeaveProjectIntegration, error) {
	rows, err := q.db.Query(ctx, weaveProjectIntegrationsListEnabledForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveProjectIntegration{}
	for rows.Next() {
		var i WeaveProjectIntegration
		if err := rows.Scan(
			&i.ProjectID,
			&i.IntegrationID,
			&i.Enabled,
			&i.Config,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigID,
			&i.Label,
			&i.ManagedInstanceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveProjectIntegrationsListForIntegration = `-- name: WeaveProjectIntegrationsListForIntegration :many
SELECT project_id, integration_id, enabled, config, secret_ref, created_at, updated_at, config_id, label, managed_instance_id FROM weave_project_integrations
WHERE project_id = $1 AND integration_id = $2
ORDER BY config_id
`

type WeaveProjectIntegrationsListForIntegrationParams struct {
	ProjectID     string `json:"project_id"`
	IntegrationID string `json:"integration_id"`
}

func (q *Queries) WeaveProjectIntegrationsListForIntegration(ctx context.Context, arg WeaveProjectIntegrationsListForIntegrationParams) ([]WeaveProjectIntegration, error) {
	rows, err := q.db.Query(ctx, weaveProjectIntegrationsListForIntegration, arg.ProjectID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveProjectIntegration{}
	for rows.Next() {
		var i WeaveProjectIntegration
		if err := rows.Scan(
			&i.ProjectID,
			&i.IntegrationID,
			&i.Enabled,
			&i.Config,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigID,
			&i.Label,
			&i.ManagedInstanceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveProjectIntegrationsListForProject = `-- name: WeaveProjectIntegrationsListForProject :many
SELECT project_id, integration_id, enabled, config, secret_ref, created_at, updated_at, config_id, label, managed_instance_id FROM weave_project_integrations
WHERE project_id = $1
ORDER BY integration_id, config_id
`

func (q *Queries) WeaveProjectIntegrationsListForProject(ctx context.Context, projectID string) ([]WeaveProjectIntegration, error) {
	rows, err := q.db.Query(ctx, weaveProjectIntegrationsListForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveProjectIntegration{}
	for rows.Next() {
		var i WeaveProjectIntegration
		if err := rows.Scan(
			&i.ProjectID,
			&i.IntegrationID,
			&i.Enabled,
			&i.Config,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigID,
			&i.Label,
			&i.ManagedInstanceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
