// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_ontology_classes.sql

package sqlcgen

import (
	"context"
)

const weaveCountOntologyClassesByVersion = `-- name: WeaveCountOntologyClassesByVersion :one
SELECT count(*)::bigint
FROM weave_ontology_classes
WHERE ontology_version_id = $1
`

func (q *Queries) WeaveCountOntologyClassesByVersion(ctx context.Context, ontologyVersionID string) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountOntologyClassesByVersion, ontologyVersionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveCreateOntologyClass = `-- name: WeaveCreateOntologyClass :one
INSERT INTO weave_ontology_classes (
    id, ontology_version_id, prefix, local_name, uri, label, comment,
    natural_sort_key, source_module
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module
`

type WeaveCreateOntologyClassParams struct {
	ID                string  `json:"id"`
	OntologyVersionID string  `json:"ontology_version_id"`
	Prefix            string  `json:"prefix"`
	LocalName         string  `json:"local_name"`
	Uri               string  `json:"uri"`
	Label             []byte  `json:"label"`
	Comment           []byte  `json:"comment"`
	NaturalSortKey    string  `json:"natural_sort_key"`
	SourceModule      *string `json:"source_module"`
}

func (q *Queries) WeaveCreateOntologyClass(ctx context.Context, arg WeaveCreateOntologyClassParams) (WeaveOntologyClass, error) {
	row := q.db.QueryRow(ctx, weaveCreateOntologyClass,
		arg.ID,
		arg.OntologyVersionID,
		arg.Prefix,
		arg.LocalName,
		arg.Uri,
		arg.Label,
		arg.Comment,
		arg.NaturalSortKey,
		arg.SourceModule,
	)
	var i WeaveOntologyClass
	err := row.Scan(
		&i.ID,
		&i.OntologyVersionID,
		&i.Prefix,
		&i.LocalName,
		&i.Uri,
		&i.Qname,
		&i.Label,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NaturalSortKey,
		&i.SourceModule,
	)
	return i, err
}

const weaveDeleteOntologyClass = `-- name: WeaveDeleteOntologyClass :exec
DELETE FROM weave_ontology_classes WHERE id = $1
`

func (q *Queries) WeaveDeleteOntologyClass(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteOntologyClass, id)
	return err
}

const weaveDeleteOntologyClassesByVersion = `-- name: WeaveDeleteOntologyClassesByVersion :exec
DELETE FROM weave_ontology_classes WHERE ontology_version_id = $1
`

func (q *Queries) WeaveDeleteOntologyClassesByVersion(ctx context.Context, ontologyVersionID string) error {
	_, err := q.db.Exec(ctx, weaveDeleteOntologyClassesByVersion, ontologyVersionID)
	return err
}

const weaveGetOntologyClassByID = `-- name: WeaveGetOntologyClassByID :one
SELECT id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module FROM weave_ontology_classes WHERE id = $1
`

func (q *Queries) WeaveGetOntologyClassByID(ctx context.Context, id string) (WeaveOntologyClass, error) {
	row := q.db.QueryRow(ctx, weaveGetOntologyClassByID, id)
	var i WeaveOntologyClass
	err := row.Scan(
		&i.ID,
		&i.OntologyVersionID,
		&i.Prefix,
		&i.LocalName,
		&i.Uri,
		&i.Qname,
		&i.Label,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NaturalSortKey,
		&i.SourceModule,
	)
	return i, err
}

const weaveGetOntologyClassByQname = `-- name: WeaveGetOntologyClassByQname :one
SELECT id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module FROM weave_ontology_classes
WHERE ontology_version_id = $1 AND qname = $2
`

type WeaveGetOntologyClassByQnameParams struct {
	OntologyVersionID string  `json:"ontology_version_id"`
	Qname             *string `json:"qname"`
}

func (q *Queries) WeaveGetOntologyClassByQname(ctx context.Context, arg WeaveGetOntologyClassByQnameParams) (WeaveOntologyClass, error) {
	row := q.db.QueryRow(ctx, weaveGetOntologyClassByQname, arg.OntologyVersionID, arg.Qname)
	var i WeaveOntologyClass
	err := row.Scan(
		&i.ID,
		&i.OntologyVersionID,
		&i.Prefix,
		&i.LocalName,
		&i.Uri,
		&i.Qname,
		&i.Label,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NaturalSortKey,
		&i.SourceModule,
	)
	return i, err
}

const weaveGetOntologyClassByURI = `-- name: WeaveGetOntologyClassByURI :one
SELECT id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module FROM weave_ontology_classes
WHERE ontology_version_id = $1 AND uri = $2
`

type WeaveGetOntologyClassByURIParams struct {
	OntologyVersionID string `json:"ontology_version_id"`
	Uri               string `json:"uri"`
}

func (q *Queries) WeaveGetOntologyClassByURI(ctx context.Context, arg WeaveGetOntologyClassByURIParams) (WeaveOntologyClass, error) {
	row := q.db.QueryRow(ctx, weaveGetOntologyClassByURI, arg.OntologyVersionID, arg.Uri)
	var i WeaveOntologyClass
	err := row.Scan(
		&i.ID,
		&i.OntologyVersionID,
		&i.Prefix,
		&i.LocalName,
		&i.Uri,
		&i.Qname,
		&i.Label,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NaturalSortKey,
		&i.SourceModule,
	)
	return i, err
}

const weaveListClassesByVersions = `-- name: WeaveListClassesByVersions :many
SELECT id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module FROM weave_ontology_classes
WHERE ontology_version_id = ANY($1::text[])
ORDER BY ontology_version_id, qname
`

func (q *Queries) WeaveListClassesByVersions(ctx context.Context, dollar_1 []string) ([]WeaveOntologyClass, error) {
	rows, err := q.db.Query(ctx, weaveListClassesByVersions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyClass{}
	for rows.Next() {
		var i WeaveOntologyClass
		if err := rows.Scan(
			&i.ID,
			&i.OntologyVersionID,
			&i.Prefix,
			&i.LocalName,
			&i.Uri,
			&i.Qname,
			&i.Label,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NaturalSortKey,
			&i.SourceModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOntologyClassesByQnames = `-- name: WeaveListOntologyClassesByQnames :many
SELECT id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module FROM weave_ontology_classes
WHERE ontology_version_id = $1 AND qname = ANY($2::text[])
`

type WeaveListOntologyClassesByQnamesParams struct {
	OntologyVersionID string   `json:"ontology_version_id"`
	Column2           []string `json:"column_2"`
}

// Batch-load classes by qname within a version. Used by autocomplete to
// avoid N+1 lookups when materializing a path's class metadata.
func (q *Queries) WeaveListOntologyClassesByQnames(ctx context.Context, arg WeaveListOntologyClassesByQnamesParams) ([]WeaveOntologyClass, error) {
	rows, err := q.db.Query(ctx, weaveListOntologyClassesByQnames, arg.OntologyVersionID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyClass{}
	for rows.Next() {
		var i WeaveOntologyClass
		if err := rows.Scan(
			&i.ID,
			&i.OntologyVersionID,
			&i.Prefix,
			&i.LocalName,
			&i.Uri,
			&i.Qname,
			&i.Label,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NaturalSortKey,
			&i.SourceModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOntologyClassesByVersion = `-- name: WeaveListOntologyClassesByVersion :many
SELECT id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module FROM weave_ontology_classes
WHERE ontology_version_id = $1
ORDER BY natural_sort_key ASC, local_name ASC
`

func (q *Queries) WeaveListOntologyClassesByVersion(ctx context.Context, ontologyVersionID string) ([]WeaveOntologyClass, error) {
	rows, err := q.db.Query(ctx, weaveListOntologyClassesByVersion, ontologyVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyClass{}
	for rows.Next() {
		var i WeaveOntologyClass
		if err := rows.Scan(
			&i.ID,
			&i.OntologyVersionID,
			&i.Prefix,
			&i.LocalName,
			&i.Uri,
			&i.Qname,
			&i.Label,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NaturalSortKey,
			&i.SourceModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListSubclassesByQname = `-- name: WeaveListSubclassesByQname :many
SELECT c.id, c.ontology_version_id, c.prefix, c.local_name, c.uri, c.qname, c.label, c.comment, c.created_at, c.updated_at, c.natural_sort_key, c.source_module FROM weave_ontology_classes c
JOIN weave_ontology_relations r
  ON r.source_id = c.id
 AND r.source_kind = 'class'
 AND r.rel_type = 'subclass_of'
WHERE c.ontology_version_id = $1
  AND r.target_qname = $2
ORDER BY c.natural_sort_key ASC, c.local_name ASC
`

type WeaveListSubclassesByQnameParams struct {
	OntologyVersionID string `json:"ontology_version_id"`
	TargetQname       string `json:"target_qname"`
}

// Return classes that are direct subclasses of target_qname within
// a specific version. Drives autocomplete range expansion: P1's range
// is crm:E41_Appellation, but the dropdown should also offer
// crm:E33_E41_Linguistic_Appellation since it subclasses E41. Caller
// does breadth-first descent in Go for transitive coverage.
func (q *Queries) WeaveListSubclassesByQname(ctx context.Context, arg WeaveListSubclassesByQnameParams) ([]WeaveOntologyClass, error) {
	rows, err := q.db.Query(ctx, weaveListSubclassesByQname, arg.OntologyVersionID, arg.TargetQname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyClass{}
	for rows.Next() {
		var i WeaveOntologyClass
		if err := rows.Scan(
			&i.ID,
			&i.OntologyVersionID,
			&i.Prefix,
			&i.LocalName,
			&i.Uri,
			&i.Qname,
			&i.Label,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NaturalSortKey,
			&i.SourceModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSearchOntologyClasses = `-- name: WeaveSearchOntologyClasses :many
SELECT id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module FROM weave_ontology_classes
WHERE ontology_version_id = $1
  AND (
        local_name ILIKE '%' || $2 || '%'
     OR qname ILIKE '%' || $2 || '%'
     OR label::text ILIKE '%' || $2 || '%'
      )
ORDER BY
    CASE WHEN local_name ILIKE $2 || '%' THEN 0 ELSE 1 END,
    natural_sort_key ASC, local_name ASC
LIMIT $3
`

type WeaveSearchOntologyClassesParams struct {
	OntologyVersionID string  `json:"ontology_version_id"`
	Column2           *string `json:"column_2"`
	Limit             int32   `json:"limit"`
}

// Substring search over local_name, qname, and label JSONB values.
// Limited result set for autocomplete-style use.
func (q *Queries) WeaveSearchOntologyClasses(ctx context.Context, arg WeaveSearchOntologyClassesParams) ([]WeaveOntologyClass, error) {
	rows, err := q.db.Query(ctx, weaveSearchOntologyClasses, arg.OntologyVersionID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyClass{}
	for rows.Next() {
		var i WeaveOntologyClass
		if err := rows.Scan(
			&i.ID,
			&i.OntologyVersionID,
			&i.Prefix,
			&i.LocalName,
			&i.Uri,
			&i.Qname,
			&i.Label,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NaturalSortKey,
			&i.SourceModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveUpdateOntologyClass = `-- name: WeaveUpdateOntologyClass :one
UPDATE weave_ontology_classes
SET prefix = $2,
    local_name = $3,
    uri = $4,
    label = $5,
    comment = $6,
    natural_sort_key = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, ontology_version_id, prefix, local_name, uri, qname, label, comment, created_at, updated_at, natural_sort_key, source_module
`

type WeaveUpdateOntologyClassParams struct {
	ID             string `json:"id"`
	Prefix         string `json:"prefix"`
	LocalName      string `json:"local_name"`
	Uri            string `json:"uri"`
	Label          []byte `json:"label"`
	Comment        []byte `json:"comment"`
	NaturalSortKey string `json:"natural_sort_key"`
}

func (q *Queries) WeaveUpdateOntologyClass(ctx context.Context, arg WeaveUpdateOntologyClassParams) (WeaveOntologyClass, error) {
	row := q.db.QueryRow(ctx, weaveUpdateOntologyClass,
		arg.ID,
		arg.Prefix,
		arg.LocalName,
		arg.Uri,
		arg.Label,
		arg.Comment,
		arg.NaturalSortKey,
	)
	var i WeaveOntologyClass
	err := row.Scan(
		&i.ID,
		&i.OntologyVersionID,
		&i.Prefix,
		&i.LocalName,
		&i.Uri,
		&i.Qname,
		&i.Label,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NaturalSortKey,
		&i.SourceModule,
	)
	return i, err
}
