// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const weaveAPIKeyCreate = `-- name: WeaveAPIKeyCreate :one
INSERT INTO weave_api_keys (id, actor_id, name, key_hash, key_prefix, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at, revoked_at
`

type WeaveAPIKeyCreateParams struct {
	ID        string             `json:"id"`
	ActorID   string             `json:"actor_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) WeaveAPIKeyCreate(ctx context.Context, arg WeaveAPIKeyCreateParams) (WeaveApiKey, error) {
	row := q.db.QueryRow(ctx, weaveAPIKeyCreate,
		arg.ID,
		arg.ActorID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.ExpiresAt,
	)
	var i WeaveApiKey
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const weaveAPIKeyGetByHash = `-- name: WeaveAPIKeyGetByHash :one
SELECT id, actor_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at, revoked_at FROM weave_api_keys WHERE key_hash = $1
`

func (q *Queries) WeaveAPIKeyGetByHash(ctx context.Context, keyHash string) (WeaveApiKey, error) {
	row := q.db.QueryRow(ctx, weaveAPIKeyGetByHash, keyHash)
	var i WeaveApiKey
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const weaveAPIKeyList = `-- name: WeaveAPIKeyList :many
SELECT id, actor_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at, revoked_at FROM weave_api_keys ORDER BY created_at DESC
`

func (q *Queries) WeaveAPIKeyList(ctx context.Context) ([]WeaveApiKey, error) {
	rows, err := q.db.Query(ctx, weaveAPIKeyList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveApiKey{}
	for rows.Next() {
		var i WeaveApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveAPIKeyListByActor = `-- name: WeaveAPIKeyListByActor :many
SELECT id, actor_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at, revoked_at FROM weave_api_keys WHERE actor_id = $1 ORDER BY created_at DESC
`

func (q *Queries) WeaveAPIKeyListByActor(ctx context.Context, actorID string) ([]WeaveApiKey, error) {
	rows, err := q.db.Query(ctx, weaveAPIKeyListByActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveApiKey{}
	for rows.Next() {
		var i WeaveApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveAPIKeyRevoke = `-- name: WeaveAPIKeyRevoke :execrows
UPDATE weave_api_keys
SET revoked_at = now()
WHERE (id = $1 OR key_prefix = $1) AND revoked_at IS NULL
`

func (q *Queries) WeaveAPIKeyRevoke(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, weaveAPIKeyRevoke, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const weaveAPIKeyTouch = `-- name: WeaveAPIKeyTouch :exec
UPDATE weave_api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) WeaveAPIKeyTouch(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveAPIKeyTouch, id)
	return err
}
