// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const weaveActorCreatePerson = `-- name: WeaveActorCreatePerson :one
INSERT INTO weave_actors (id, type, display_name, system_name, slug, email)
VALUES ($1, 'person', $2, $3, $4, $5)
RETURNING id, display_name, slug, email
`

type WeaveActorCreatePersonParams struct {
	ID          string  `json:"id"`
	DisplayName string  `json:"display_name"`
	SystemName  *string `json:"system_name"`
	Slug        string  `json:"slug"`
	Email       *string `json:"email"`
}

type WeaveActorCreatePersonRow struct {
	ID          string  `json:"id"`
	DisplayName string  `json:"display_name"`
	Slug        string  `json:"slug"`
	Email       *string `json:"email"`
}

func (q *Queries) WeaveActorCreatePerson(ctx context.Context, arg WeaveActorCreatePersonParams) (WeaveActorCreatePersonRow, error) {
	row := q.db.QueryRow(ctx, weaveActorCreatePerson,
		arg.ID,
		arg.DisplayName,
		arg.SystemName,
		arg.Slug,
		arg.Email,
	)
	var i WeaveActorCreatePersonRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Slug,
		&i.Email,
	)
	return i, err
}

const weaveAuthBumpPermsVersion = `-- name: WeaveAuthBumpPermsVersion :exec
UPDATE weave_auth
SET perms_version = perms_version + 1, updated_at = NOW()
WHERE actor_id = $1
`

func (q *Queries) WeaveAuthBumpPermsVersion(ctx context.Context, actorID string) error {
	_, err := q.db.Exec(ctx, weaveAuthBumpPermsVersion, actorID)
	return err
}

const weaveAuthClearResetToken = `-- name: WeaveAuthClearResetToken :exec
UPDATE weave_auth
SET password_reset_token = NULL,
    password_reset_expires_at = NULL,
    updated_at = NOW()
WHERE actor_id = $1
`

func (q *Queries) WeaveAuthClearResetToken(ctx context.Context, actorID string) error {
	_, err := q.db.Exec(ctx, weaveAuthClearResetToken, actorID)
	return err
}

const weaveAuthCreate = `-- name: WeaveAuthCreate :one
INSERT INTO weave_auth (actor_id, password_hash, email_verified_at)
VALUES ($1, $2, $3)
RETURNING actor_id, password_hash, email_verified_at, password_reset_token, password_reset_expires_at, last_login_at, perms_version, created_at, updated_at
`

type WeaveAuthCreateParams struct {
	ActorID         string             `json:"actor_id"`
	PasswordHash    string             `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) WeaveAuthCreate(ctx context.Context, arg WeaveAuthCreateParams) (WeaveAuth, error) {
	row := q.db.QueryRow(ctx, weaveAuthCreate, arg.ActorID, arg.PasswordHash, arg.EmailVerifiedAt)
	var i WeaveAuth
	err := row.Scan(
		&i.ActorID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.PermsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveAuthDelete = `-- name: WeaveAuthDelete :exec
DELETE FROM weave_auth WHERE actor_id = $1
`

func (q *Queries) WeaveAuthDelete(ctx context.Context, actorID string) error {
	_, err := q.db.Exec(ctx, weaveAuthDelete, actorID)
	return err
}

const weaveAuthGetByActorID = `-- name: WeaveAuthGetByActorID :one
SELECT actor_id, password_hash, email_verified_at, password_reset_token, password_reset_expires_at, last_login_at, perms_version, created_at, updated_at FROM weave_auth WHERE actor_id = $1
`

func (q *Queries) WeaveAuthGetByActorID(ctx context.Context, actorID string) (WeaveAuth, error) {
	row := q.db.QueryRow(ctx, weaveAuthGetByActorID, actorID)
	var i WeaveAuth
	err := row.Scan(
		&i.ActorID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.PermsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveAuthGetByActorIDWithActor = `-- name: WeaveAuthGetByActorIDWithActor :one
SELECT a.actor_id, a.password_hash, a.email_verified_at, a.password_reset_token, a.password_reset_expires_at, a.last_login_at, a.perms_version, a.created_at, a.updated_at, wa.email, wa.slug, wa.display_name, wa.role AS actor_role
FROM weave_auth a
JOIN weave_actors wa ON wa.id = a.actor_id
WHERE a.actor_id = $1
`

type WeaveAuthGetByActorIDWithActorRow struct {
	ActorID                string             `json:"actor_id"`
	PasswordHash           string             `json:"password_hash"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	PasswordResetToken     *string            `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
	LastLoginAt            pgtype.Timestamptz `json:"last_login_at"`
	PermsVersion           int32              `json:"perms_version"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	Email                  *string            `json:"email"`
	Slug                   string             `json:"slug"`
	DisplayName            string             `json:"display_name"`
	ActorRole              string             `json:"actor_role"`
}

func (q *Queries) WeaveAuthGetByActorIDWithActor(ctx context.Context, actorID string) (WeaveAuthGetByActorIDWithActorRow, error) {
	row := q.db.QueryRow(ctx, weaveAuthGetByActorIDWithActor, actorID)
	var i WeaveAuthGetByActorIDWithActorRow
	err := row.Scan(
		&i.ActorID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.PermsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Slug,
		&i.DisplayName,
		&i.ActorRole,
	)
	return i, err
}

const weaveAuthGetByEmail = `-- name: WeaveAuthGetByEmail :one
SELECT a.actor_id, a.password_hash, a.email_verified_at, a.password_reset_token, a.password_reset_expires_at, a.last_login_at, a.perms_version, a.created_at, a.updated_at, wa.email, wa.slug, wa.display_name, wa.role AS actor_role
FROM weave_auth a
JOIN weave_actors wa ON wa.id = a.actor_id
WHERE wa.email = $1
`

type WeaveAuthGetByEmailRow struct {
	ActorID                string             `json:"actor_id"`
	PasswordHash           string             `json:"password_hash"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	PasswordResetToken     *string            `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
	LastLoginAt            pgtype.Timestamptz `json:"last_login_at"`
	PermsVersion           int32              `json:"perms_version"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	Email                  *string            `json:"email"`
	Slug                   string             `json:"slug"`
	DisplayName            string             `json:"display_name"`
	ActorRole              string             `json:"actor_role"`
}

func (q *Queries) WeaveAuthGetByEmail(ctx context.Context, email *string) (WeaveAuthGetByEmailRow, error) {
	row := q.db.QueryRow(ctx, weaveAuthGetByEmail, email)
	var i WeaveAuthGetByEmailRow
	err := row.Scan(
		&i.ActorID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.PermsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Slug,
		&i.DisplayName,
		&i.ActorRole,
	)
	return i, err
}

const weaveAuthGetByEmailOrSlug = `-- name: WeaveAuthGetByEmailOrSlug :one
SELECT a.actor_id, a.password_hash, a.email_verified_at, a.password_reset_token, a.password_reset_expires_at, a.last_login_at, a.perms_version, a.created_at, a.updated_at, wa.email, wa.slug, wa.display_name, wa.role AS actor_role
FROM weave_auth a
JOIN weave_actors wa ON wa.id = a.actor_id
WHERE wa.email = $1 OR wa.slug = $1
`

type WeaveAuthGetByEmailOrSlugRow struct {
	ActorID                string             `json:"actor_id"`
	PasswordHash           string             `json:"password_hash"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	PasswordResetToken     *string            `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
	LastLoginAt            pgtype.Timestamptz `json:"last_login_at"`
	PermsVersion           int32              `json:"perms_version"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	Email                  *string            `json:"email"`
	Slug                   string             `json:"slug"`
	DisplayName            string             `json:"display_name"`
	ActorRole              string             `json:"actor_role"`
}

// Used by Login: accepts either the user's email or their slug (username).
func (q *Queries) WeaveAuthGetByEmailOrSlug(ctx context.Context, email *string) (WeaveAuthGetByEmailOrSlugRow, error) {
	row := q.db.QueryRow(ctx, weaveAuthGetByEmailOrSlug, email)
	var i WeaveAuthGetByEmailOrSlugRow
	err := row.Scan(
		&i.ActorID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.PermsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Slug,
		&i.DisplayName,
		&i.ActorRole,
	)
	return i, err
}

const weaveAuthGetByResetToken = `-- name: WeaveAuthGetByResetToken :one
SELECT actor_id, password_hash, email_verified_at, password_reset_token, password_reset_expires_at, last_login_at, perms_version, created_at, updated_at FROM weave_auth
WHERE password_reset_token = $1
  AND password_reset_expires_at > NOW()
`

func (q *Queries) WeaveAuthGetByResetToken(ctx context.Context, passwordResetToken *string) (WeaveAuth, error) {
	row := q.db.QueryRow(ctx, weaveAuthGetByResetToken, passwordResetToken)
	var i WeaveAuth
	err := row.Scan(
		&i.ActorID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.PermsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveAuthMarkLogin = `-- name: WeaveAuthMarkLogin :exec
UPDATE weave_auth
SET last_login_at = NOW(), updated_at = NOW()
WHERE actor_id = $1
`

func (q *Queries) WeaveAuthMarkLogin(ctx context.Context, actorID string) error {
	_, err := q.db.Exec(ctx, weaveAuthMarkLogin, actorID)
	return err
}

const weaveAuthSetResetToken = `-- name: WeaveAuthSetResetToken :exec
UPDATE weave_auth
SET password_reset_token = $2,
    password_reset_expires_at = $3,
    updated_at = NOW()
WHERE actor_id = $1
`

type WeaveAuthSetResetTokenParams struct {
	ActorID                string             `json:"actor_id"`
	PasswordResetToken     *string            `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
}

func (q *Queries) WeaveAuthSetResetToken(ctx context.Context, arg WeaveAuthSetResetTokenParams) error {
	_, err := q.db.Exec(ctx, weaveAuthSetResetToken, arg.ActorID, arg.PasswordResetToken, arg.PasswordResetExpiresAt)
	return err
}

const weaveAuthUpdatePassword = `-- name: WeaveAuthUpdatePassword :exec
UPDATE weave_auth
SET password_hash = $2, updated_at = NOW()
WHERE actor_id = $1
`

type WeaveAuthUpdatePasswordParams struct {
	ActorID      string `json:"actor_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) WeaveAuthUpdatePassword(ctx context.Context, arg WeaveAuthUpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, weaveAuthUpdatePassword, arg.ActorID, arg.PasswordHash)
	return err
}
