// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_field_overrides.sql

package sqlcgen

import (
	"context"
	"time"
)

const weaveClosureOverrideOwner = `-- name: WeaveClosureOverrideOwner :one
SELECT entity_type, entity_id, field_id
FROM weave_field_overrides
WHERE id = $1
`

type WeaveClosureOverrideOwnerRow struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	FieldID    string `json:"field_id"`
}

// gitmaterializer closure(): resolves a change_log "override" entry's
// entity_id (a weave_field_overrides.id) to its owning model/collection, or
// (entity_type ”, field_id) for a base override.
func (q *Queries) WeaveClosureOverrideOwner(ctx context.Context, id int64) (WeaveClosureOverrideOwnerRow, error) {
	row := q.db.QueryRow(ctx, weaveClosureOverrideOwner, id)
	var i WeaveClosureOverrideOwnerRow
	err := row.Scan(&i.EntityType, &i.EntityID, &i.FieldID)
	return i, err
}

const weaveClosurePlacementsForField = `-- name: WeaveClosurePlacementsForField :many
SELECT DISTINCT entity_type, entity_id
FROM weave_field_overrides
WHERE field_id = $1 AND project_id = $2 AND entity_type IN ('model', 'collection')
`

type WeaveClosurePlacementsForFieldParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
}

type WeaveClosurePlacementsForFieldRow struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

// gitmaterializer closure(): models/collections in this project that place
// fieldID via an override row. Editing/deleting the field must also rewrite
// each placing owner's overrides/ subtree.
func (q *Queries) WeaveClosurePlacementsForField(ctx context.Context, arg WeaveClosurePlacementsForFieldParams) ([]WeaveClosurePlacementsForFieldRow, error) {
	rows, err := q.db.Query(ctx, weaveClosurePlacementsForField, arg.FieldID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveClosurePlacementsForFieldRow{}
	for rows.Next() {
		var i WeaveClosurePlacementsForFieldRow
		if err := rows.Scan(&i.EntityType, &i.EntityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveCountFieldUsage = `-- name: WeaveCountFieldUsage :one
SELECT
    count(DISTINCT entity_id) FILTER (WHERE entity_type = 'model')::bigint
        AS models_using,
    count(DISTINCT entity_id) FILTER (WHERE entity_type = 'collection')::bigint
        AS collections_using,
    count(*) FILTER (WHERE entity_type IN ('model', 'collection'))::bigint
        AS override_count
FROM weave_field_overrides
WHERE field_id = $1 AND project_id = $2
`

type WeaveCountFieldUsageParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
}

type WeaveCountFieldUsageRow struct {
	ModelsUsing      int64 `json:"models_using"`
	CollectionsUsing int64 `json:"collections_using"`
	OverrideCount    int64 `json:"override_count"`
}

// "How many models / collections in this project use this field?"
// Drives the field item view's Stats tab. Counts
// distinct entity_ids per kind from weave_field_overrides — that
// table encodes both model_fields and collection_fields junctions
// via (entity_type, entity_id). override_count is the total number
// of model/collection override rows referencing this field (the
// override-row count, not the distinct entity count).
func (q *Queries) WeaveCountFieldUsage(ctx context.Context, arg WeaveCountFieldUsageParams) (WeaveCountFieldUsageRow, error) {
	row := q.db.QueryRow(ctx, weaveCountFieldUsage, arg.FieldID, arg.ProjectID)
	var i WeaveCountFieldUsageRow
	err := row.Scan(&i.ModelsUsing, &i.CollectionsUsing, &i.OverrideCount)
	return i, err
}

const weaveCountOverridesForEntity = `-- name: WeaveCountOverridesForEntity :one
SELECT COUNT(*) FROM weave_field_overrides WHERE entity_type = $1 AND entity_id = $2
`

type WeaveCountOverridesForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) WeaveCountOverridesForEntity(ctx context.Context, arg WeaveCountOverridesForEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountOverridesForEntity, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveCreateOverride = `-- name: WeaveCreateOverride :one

INSERT INTO weave_field_overrides (
    field_id, project_id, entity_type, entity_id,
    position, collection_order,
    display_name, description, collection_name,
    category_id, part_of_collection_id,
    expected_value_type, set_value,
    is_required, min_occurs, max_occurs, is_hidden, visibility,
    staging_id, content_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
) RETURNING id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id
`

type WeaveCreateOverrideParams struct {
	FieldID            string  `json:"field_id"`
	ProjectID          string  `json:"project_id"`
	EntityType         string  `json:"entity_type"`
	EntityID           string  `json:"entity_id"`
	Position           int32   `json:"position"`
	CollectionOrder    int32   `json:"collection_order"`
	DisplayName        []byte  `json:"display_name"`
	Description        []byte  `json:"description"`
	CollectionName     []byte  `json:"collection_name"`
	CategoryID         *string `json:"category_id"`
	PartOfCollectionID *string `json:"part_of_collection_id"`
	ExpectedValueType  *string `json:"expected_value_type"`
	SetValue           *string `json:"set_value"`
	IsRequired         *bool   `json:"is_required"`
	MinOccurs          *int32  `json:"min_occurs"`
	MaxOccurs          *int32  `json:"max_occurs"`
	IsHidden           *bool   `json:"is_hidden"`
	Visibility         *string `json:"visibility"`
	StagingID          *int64  `json:"staging_id"`
	ContentHash        *string `json:"content_hash"`
}

// Override PK is bigserial (auto-generated). No id parameter on insert.
// All entity references use semantic IDs directly.
func (q *Queries) WeaveCreateOverride(ctx context.Context, arg WeaveCreateOverrideParams) (WeaveFieldOverride, error) {
	row := q.db.QueryRow(ctx, weaveCreateOverride,
		arg.FieldID,
		arg.ProjectID,
		arg.EntityType,
		arg.EntityID,
		arg.Position,
		arg.CollectionOrder,
		arg.DisplayName,
		arg.Description,
		arg.CollectionName,
		arg.CategoryID,
		arg.PartOfCollectionID,
		arg.ExpectedValueType,
		arg.SetValue,
		arg.IsRequired,
		arg.MinOccurs,
		arg.MaxOccurs,
		arg.IsHidden,
		arg.Visibility,
		arg.StagingID,
		arg.ContentHash,
	)
	var i WeaveFieldOverride
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CollectionOrder,
		&i.DisplayName,
		&i.Description,
		&i.CollectionName,
		&i.CategoryID,
		&i.PartOfCollectionID,
		&i.ExpectedValueType,
		&i.SetValue,
		&i.IsRequired,
		&i.MinOccurs,
		&i.MaxOccurs,
		&i.IsHidden,
		&i.Visibility,
		&i.StagingID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.VersionNumber,
		&i.SetValueEntryID,
	)
	return i, err
}

const weaveCreateOverrideRef = `-- name: WeaveCreateOverrideRef :exec
INSERT INTO weave_override_refs (override_id, ref_type, target_id, semantic_id, position)
VALUES ($1, $2, $3, $4, $5)
`

type WeaveCreateOverrideRefParams struct {
	OverrideID int64  `json:"override_id"`
	RefType    string `json:"ref_type"`
	TargetID   string `json:"target_id"`
	SemanticID string `json:"semantic_id"`
	Position   int32  `json:"position"`
}

func (q *Queries) WeaveCreateOverrideRef(ctx context.Context, arg WeaveCreateOverrideRefParams) error {
	_, err := q.db.Exec(ctx, weaveCreateOverrideRef,
		arg.OverrideID,
		arg.RefType,
		arg.TargetID,
		arg.SemanticID,
		arg.Position,
	)
	return err
}

const weaveDeleteOverride = `-- name: WeaveDeleteOverride :exec
DELETE FROM weave_field_overrides WHERE id = $1
`

func (q *Queries) WeaveDeleteOverride(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, weaveDeleteOverride, id)
	return err
}

const weaveDeleteOverrideRefs = `-- name: WeaveDeleteOverrideRefs :exec
DELETE FROM weave_override_refs WHERE override_id = $1
`

func (q *Queries) WeaveDeleteOverrideRefs(ctx context.Context, overrideID int64) error {
	_, err := q.db.Exec(ctx, weaveDeleteOverrideRefs, overrideID)
	return err
}

const weaveDeleteOverridesForEntity = `-- name: WeaveDeleteOverridesForEntity :exec
DELETE FROM weave_field_overrides WHERE entity_type = $1 AND entity_id = $2
`

type WeaveDeleteOverridesForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) WeaveDeleteOverridesForEntity(ctx context.Context, arg WeaveDeleteOverridesForEntityParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteOverridesForEntity, arg.EntityType, arg.EntityID)
	return err
}

const weaveGetBaseOverride = `-- name: WeaveGetBaseOverride :one
SELECT id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id FROM weave_field_overrides
WHERE field_id = $1 AND project_id = $2 AND entity_type = ''
LIMIT 1
`

type WeaveGetBaseOverrideParams struct {
	FieldID   string `json:"field_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) WeaveGetBaseOverride(ctx context.Context, arg WeaveGetBaseOverrideParams) (WeaveFieldOverride, error) {
	row := q.db.QueryRow(ctx, weaveGetBaseOverride, arg.FieldID, arg.ProjectID)
	var i WeaveFieldOverride
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CollectionOrder,
		&i.DisplayName,
		&i.Description,
		&i.CollectionName,
		&i.CategoryID,
		&i.PartOfCollectionID,
		&i.ExpectedValueType,
		&i.SetValue,
		&i.IsRequired,
		&i.MinOccurs,
		&i.MaxOccurs,
		&i.IsHidden,
		&i.Visibility,
		&i.StagingID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.VersionNumber,
		&i.SetValueEntryID,
	)
	return i, err
}

const weaveGetOverrideByID = `-- name: WeaveGetOverrideByID :one
SELECT id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id FROM weave_field_overrides WHERE id = $1
`

func (q *Queries) WeaveGetOverrideByID(ctx context.Context, id int64) (WeaveFieldOverride, error) {
	row := q.db.QueryRow(ctx, weaveGetOverrideByID, id)
	var i WeaveFieldOverride
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CollectionOrder,
		&i.DisplayName,
		&i.Description,
		&i.CollectionName,
		&i.CategoryID,
		&i.PartOfCollectionID,
		&i.ExpectedValueType,
		&i.SetValue,
		&i.IsRequired,
		&i.MinOccurs,
		&i.MaxOccurs,
		&i.IsHidden,
		&i.Visibility,
		&i.StagingID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.VersionNumber,
		&i.SetValueEntryID,
	)
	return i, err
}

const weaveListAllBaseFieldCategoryAssignments = `-- name: WeaveListAllBaseFieldCategoryAssignments :many
SELECT field_id, category_id
FROM weave_field_overrides
WHERE project_id = $1
  AND entity_type = ''
  AND COALESCE(category_id, '') <> ''
`

type WeaveListAllBaseFieldCategoryAssignmentsRow struct {
	FieldID    string  `json:"field_id"`
	CategoryID *string `json:"category_id"`
}

// Returns (field_id, category_id) for every base override in the project.
// Drives the category filter + category column on the field list.
func (q *Queries) WeaveListAllBaseFieldCategoryAssignments(ctx context.Context, projectID string) ([]WeaveListAllBaseFieldCategoryAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, weaveListAllBaseFieldCategoryAssignments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListAllBaseFieldCategoryAssignmentsRow{}
	for rows.Next() {
		var i WeaveListAllBaseFieldCategoryAssignmentsRow
		if err := rows.Scan(&i.FieldID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListBaseFieldCategoriesForProject = `-- name: WeaveListBaseFieldCategoriesForProject :many
SELECT DISTINCT c.id, c.ui_name, c.canonical_order
FROM weave_categories c
JOIN weave_field_overrides fo ON fo.category_id = c.id
WHERE fo.project_id = $1
  AND fo.entity_type = ''
  AND COALESCE(fo.category_id, '') <> ''
ORDER BY c.canonical_order ASC, c.id ASC
`

type WeaveListBaseFieldCategoriesForProjectRow struct {
	ID             string `json:"id"`
	UiName         []byte `json:"ui_name"`
	CanonicalOrder int32  `json:"canonical_order"`
}

// Distinct categories assigned to base field overrides in a project.
// Drives the category filter dropdown on the field list.
func (q *Queries) WeaveListBaseFieldCategoriesForProject(ctx context.Context, projectID string) ([]WeaveListBaseFieldCategoriesForProjectRow, error) {
	rows, err := q.db.Query(ctx, weaveListBaseFieldCategoriesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListBaseFieldCategoriesForProjectRow{}
	for rows.Next() {
		var i WeaveListBaseFieldCategoriesForProjectRow
		if err := rows.Scan(&i.ID, &i.UiName, &i.CanonicalOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListBaseOverridesForFields = `-- name: WeaveListBaseOverridesForFields :many
SELECT id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id FROM weave_field_overrides
WHERE entity_type = ''
  AND project_id = $1
  AND field_id = ANY($2::text[])
`

type WeaveListBaseOverridesForFieldsParams struct {
	ProjectID string   `json:"project_id"`
	Column2   []string `json:"column_2"`
}

// Returns base overrides (entity_type=”) for a set of field IDs scoped
// to a project. Used by the resolver to enforce the "base SetValue is
// non-overridable" rule when materialising model/collection views.
func (q *Queries) WeaveListBaseOverridesForFields(ctx context.Context, arg WeaveListBaseOverridesForFieldsParams) ([]WeaveFieldOverride, error) {
	rows, err := q.db.Query(ctx, weaveListBaseOverridesForFields, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveFieldOverride{}
	for rows.Next() {
		var i WeaveFieldOverride
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CollectionOrder,
			&i.DisplayName,
			&i.Description,
			&i.CollectionName,
			&i.CategoryID,
			&i.PartOfCollectionID,
			&i.ExpectedValueType,
			&i.SetValue,
			&i.IsRequired,
			&i.MinOccurs,
			&i.MaxOccurs,
			&i.IsHidden,
			&i.Visibility,
			&i.StagingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.VersionNumber,
			&i.SetValueEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOverrideRefs = `-- name: WeaveListOverrideRefs :many
SELECT override_id, ref_type, target_id, semantic_id, position FROM weave_override_refs WHERE override_id = $1 ORDER BY ref_type, position
`

func (q *Queries) WeaveListOverrideRefs(ctx context.Context, overrideID int64) ([]WeaveOverrideRef, error) {
	rows, err := q.db.Query(ctx, weaveListOverrideRefs, overrideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOverrideRef{}
	for rows.Next() {
		var i WeaveOverrideRef
		if err := rows.Scan(
			&i.OverrideID,
			&i.RefType,
			&i.TargetID,
			&i.SemanticID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOverridesByProjectAndType = `-- name: WeaveListOverridesByProjectAndType :many
SELECT id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id FROM weave_field_overrides
WHERE project_id = $1 AND entity_type = $2
ORDER BY entity_id, position
`

type WeaveListOverridesByProjectAndTypeParams struct {
	ProjectID  string `json:"project_id"`
	EntityType string `json:"entity_type"`
}

// Returns all overrides for a project filtered by entity_type.
// Used by CSV export to get all model/collection/base overrides at once.
func (q *Queries) WeaveListOverridesByProjectAndType(ctx context.Context, arg WeaveListOverridesByProjectAndTypeParams) ([]WeaveFieldOverride, error) {
	rows, err := q.db.Query(ctx, weaveListOverridesByProjectAndType, arg.ProjectID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveFieldOverride{}
	for rows.Next() {
		var i WeaveFieldOverride
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CollectionOrder,
			&i.DisplayName,
			&i.Description,
			&i.CollectionName,
			&i.CategoryID,
			&i.PartOfCollectionID,
			&i.ExpectedValueType,
			&i.SetValue,
			&i.IsRequired,
			&i.MinOccurs,
			&i.MaxOccurs,
			&i.IsHidden,
			&i.Visibility,
			&i.StagingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.VersionNumber,
			&i.SetValueEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOverridesForEntity = `-- name: WeaveListOverridesForEntity :many
SELECT id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id FROM weave_field_overrides
WHERE entity_type = $1 AND entity_id = $2
ORDER BY position
`

type WeaveListOverridesForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) WeaveListOverridesForEntity(ctx context.Context, arg WeaveListOverridesForEntityParams) ([]WeaveFieldOverride, error) {
	rows, err := q.db.Query(ctx, weaveListOverridesForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveFieldOverride{}
	for rows.Next() {
		var i WeaveFieldOverride
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CollectionOrder,
			&i.DisplayName,
			&i.Description,
			&i.CollectionName,
			&i.CategoryID,
			&i.PartOfCollectionID,
			&i.ExpectedValueType,
			&i.SetValue,
			&i.IsRequired,
			&i.MinOccurs,
			&i.MaxOccurs,
			&i.IsHidden,
			&i.Visibility,
			&i.StagingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.VersionNumber,
			&i.SetValueEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOverridesForField = `-- name: WeaveListOverridesForField :many
SELECT id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id FROM weave_field_overrides WHERE field_id = $1
ORDER BY CASE entity_type WHEN 'model' THEN 0 WHEN 'collection' THEN 1 ELSE 2 END, position
`

func (q *Queries) WeaveListOverridesForField(ctx context.Context, fieldID string) ([]WeaveFieldOverride, error) {
	rows, err := q.db.Query(ctx, weaveListOverridesForField, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveFieldOverride{}
	for rows.Next() {
		var i WeaveFieldOverride
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CollectionOrder,
			&i.DisplayName,
			&i.Description,
			&i.CollectionName,
			&i.CategoryID,
			&i.PartOfCollectionID,
			&i.ExpectedValueType,
			&i.SetValue,
			&i.IsRequired,
			&i.MinOccurs,
			&i.MaxOccurs,
			&i.IsHidden,
			&i.Visibility,
			&i.StagingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.VersionNumber,
			&i.SetValueEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListRefsForOverrides = `-- name: WeaveListRefsForOverrides :many
SELECT override_id, ref_type, target_id, semantic_id, position FROM weave_override_refs WHERE override_id = ANY($1::bigint[])
ORDER BY override_id, ref_type, position
`

func (q *Queries) WeaveListRefsForOverrides(ctx context.Context, overrideIds []int64) ([]WeaveOverrideRef, error) {
	rows, err := q.db.Query(ctx, weaveListRefsForOverrides, overrideIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOverrideRef{}
	for rows.Next() {
		var i WeaveOverrideRef
		if err := rows.Scan(
			&i.OverrideID,
			&i.RefType,
			&i.TargetID,
			&i.SemanticID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveResolveForCollection = `-- name: WeaveResolveForCollection :many
SELECT
    fo.id, fo.field_id, fo.project_id, fo.entity_type, fo.entity_id, fo.position, fo.collection_order,
    fo.display_name, fo.description, fo.collection_name, fo.category_id, fo.part_of_collection_id,
    fo.set_value, fo.is_required, fo.min_occurs, fo.max_occurs, fo.is_hidden, fo.visibility,
    fo.staging_id, fo.created_at, fo.updated_at, fo.content_hash,
    f.semantic_id    AS field_semantic_id,
    f.system_name    AS field_system_name,
    f.ontology_scope AS field_ontology_scope,
    f.ontology_path  AS field_ontology_path,
    f.expected_value_type AS field_expected_value_type,
    f.path_elements  AS field_path_elements,
    f.subfield_paths AS field_subfield_paths
FROM weave_field_overrides fo
JOIN weave_fields f ON f.id = fo.field_id
WHERE fo.entity_type = 'collection'
  AND fo.entity_id = $1::text
  AND fo.project_id = $2::text
ORDER BY fo.category_id, fo.position
`

type WeaveResolveForCollectionParams struct {
	CollectionID string `json:"collection_id"`
	ProjectID    string `json:"project_id"`
}

type WeaveResolveForCollectionRow struct {
	ID                     int64     `json:"id"`
	FieldID                string    `json:"field_id"`
	ProjectID              string    `json:"project_id"`
	EntityType             string    `json:"entity_type"`
	EntityID               string    `json:"entity_id"`
	Position               int32     `json:"position"`
	CollectionOrder        int32     `json:"collection_order"`
	DisplayName            []byte    `json:"display_name"`
	Description            []byte    `json:"description"`
	CollectionName         []byte    `json:"collection_name"`
	CategoryID             *string   `json:"category_id"`
	PartOfCollectionID     *string   `json:"part_of_collection_id"`
	SetValue               *string   `json:"set_value"`
	IsRequired             *bool     `json:"is_required"`
	MinOccurs              *int32    `json:"min_occurs"`
	MaxOccurs              *int32    `json:"max_occurs"`
	IsHidden               *bool     `json:"is_hidden"`
	Visibility             *string   `json:"visibility"`
	StagingID              *int64    `json:"staging_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	ContentHash            *string   `json:"content_hash"`
	FieldSemanticID        *string   `json:"field_semantic_id"`
	FieldSystemName        *string   `json:"field_system_name"`
	FieldOntologyScope     []byte    `json:"field_ontology_scope"`
	FieldOntologyPath      *string   `json:"field_ontology_path"`
	FieldExpectedValueType *string   `json:"field_expected_value_type"`
	FieldPathElements      []byte    `json:"field_path_elements"`
	FieldSubfieldPaths     []byte    `json:"field_subfield_paths"`
}

// Returns ALL overrides for a collection with field identity joined.
func (q *Queries) WeaveResolveForCollection(ctx context.Context, arg WeaveResolveForCollectionParams) ([]WeaveResolveForCollectionRow, error) {
	rows, err := q.db.Query(ctx, weaveResolveForCollection, arg.CollectionID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveResolveForCollectionRow{}
	for rows.Next() {
		var i WeaveResolveForCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CollectionOrder,
			&i.DisplayName,
			&i.Description,
			&i.CollectionName,
			&i.CategoryID,
			&i.PartOfCollectionID,
			&i.SetValue,
			&i.IsRequired,
			&i.MinOccurs,
			&i.MaxOccurs,
			&i.IsHidden,
			&i.Visibility,
			&i.StagingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.FieldSemanticID,
			&i.FieldSystemName,
			&i.FieldOntologyScope,
			&i.FieldOntologyPath,
			&i.FieldExpectedValueType,
			&i.FieldPathElements,
			&i.FieldSubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveResolveForModel = `-- name: WeaveResolveForModel :many
SELECT
    fo.id, fo.field_id, fo.project_id, fo.entity_type, fo.entity_id, fo.position, fo.collection_order,
    fo.display_name, fo.description, fo.collection_name, fo.category_id, fo.part_of_collection_id,
    fo.set_value, fo.is_required, fo.min_occurs, fo.max_occurs, fo.is_hidden, fo.visibility,
    fo.staging_id, fo.created_at, fo.updated_at, fo.content_hash,
    f.semantic_id    AS field_semantic_id,
    f.system_name    AS field_system_name,
    f.ontology_scope AS field_ontology_scope,
    f.ontology_path  AS field_ontology_path,
    f.expected_value_type AS field_expected_value_type,
    f.path_elements  AS field_path_elements,
    f.subfield_paths AS field_subfield_paths
FROM weave_field_overrides fo
JOIN weave_fields f ON f.id = fo.field_id
WHERE fo.entity_type = 'model'
  AND fo.entity_id = $1::text
  AND fo.project_id = $2::text
ORDER BY fo.category_id, fo.part_of_collection_id, fo.position
`

type WeaveResolveForModelParams struct {
	ModelID   string `json:"model_id"`
	ProjectID string `json:"project_id"`
}

type WeaveResolveForModelRow struct {
	ID                     int64     `json:"id"`
	FieldID                string    `json:"field_id"`
	ProjectID              string    `json:"project_id"`
	EntityType             string    `json:"entity_type"`
	EntityID               string    `json:"entity_id"`
	Position               int32     `json:"position"`
	CollectionOrder        int32     `json:"collection_order"`
	DisplayName            []byte    `json:"display_name"`
	Description            []byte    `json:"description"`
	CollectionName         []byte    `json:"collection_name"`
	CategoryID             *string   `json:"category_id"`
	PartOfCollectionID     *string   `json:"part_of_collection_id"`
	SetValue               *string   `json:"set_value"`
	IsRequired             *bool     `json:"is_required"`
	MinOccurs              *int32    `json:"min_occurs"`
	MaxOccurs              *int32    `json:"max_occurs"`
	IsHidden               *bool     `json:"is_hidden"`
	Visibility             *string   `json:"visibility"`
	StagingID              *int64    `json:"staging_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	ContentHash            *string   `json:"content_hash"`
	FieldSemanticID        *string   `json:"field_semantic_id"`
	FieldSystemName        *string   `json:"field_system_name"`
	FieldOntologyScope     []byte    `json:"field_ontology_scope"`
	FieldOntologyPath      *string   `json:"field_ontology_path"`
	FieldExpectedValueType *string   `json:"field_expected_value_type"`
	FieldPathElements      []byte    `json:"field_path_elements"`
	FieldSubfieldPaths     []byte    `json:"field_subfield_paths"`
}

// Returns ALL overrides for a model with field identity joined.
// No DISTINCT ON — every override is shown (copy-on-adopt).
// Group by category → collection, order by position.
func (q *Queries) WeaveResolveForModel(ctx context.Context, arg WeaveResolveForModelParams) ([]WeaveResolveForModelRow, error) {
	rows, err := q.db.Query(ctx, weaveResolveForModel, arg.ModelID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveResolveForModelRow{}
	for rows.Next() {
		var i WeaveResolveForModelRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CollectionOrder,
			&i.DisplayName,
			&i.Description,
			&i.CollectionName,
			&i.CategoryID,
			&i.PartOfCollectionID,
			&i.SetValue,
			&i.IsRequired,
			&i.MinOccurs,
			&i.MaxOccurs,
			&i.IsHidden,
			&i.Visibility,
			&i.StagingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.FieldSemanticID,
			&i.FieldSystemName,
			&i.FieldOntologyScope,
			&i.FieldOntologyPath,
			&i.FieldExpectedValueType,
			&i.FieldPathElements,
			&i.FieldSubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveUpdateOverride = `-- name: WeaveUpdateOverride :one
UPDATE weave_field_overrides SET
    position = $2, collection_order = $3,
    display_name = $4, description = $5, collection_name = $6,
    category_id = $7, part_of_collection_id = $8,
    expected_value_type = $9, set_value = $10,
    is_required = $11, min_occurs = $12, max_occurs = $13,
    is_hidden = $14, visibility = $15,
    content_hash = $16,
    updated_at = NOW()
WHERE id = $1 RETURNING id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id
`

type WeaveUpdateOverrideParams struct {
	ID                 int64   `json:"id"`
	Position           int32   `json:"position"`
	CollectionOrder    int32   `json:"collection_order"`
	DisplayName        []byte  `json:"display_name"`
	Description        []byte  `json:"description"`
	CollectionName     []byte  `json:"collection_name"`
	CategoryID         *string `json:"category_id"`
	PartOfCollectionID *string `json:"part_of_collection_id"`
	ExpectedValueType  *string `json:"expected_value_type"`
	SetValue           *string `json:"set_value"`
	IsRequired         *bool   `json:"is_required"`
	MinOccurs          *int32  `json:"min_occurs"`
	MaxOccurs          *int32  `json:"max_occurs"`
	IsHidden           *bool   `json:"is_hidden"`
	Visibility         *string `json:"visibility"`
	ContentHash        *string `json:"content_hash"`
}

func (q *Queries) WeaveUpdateOverride(ctx context.Context, arg WeaveUpdateOverrideParams) (WeaveFieldOverride, error) {
	row := q.db.QueryRow(ctx, weaveUpdateOverride,
		arg.ID,
		arg.Position,
		arg.CollectionOrder,
		arg.DisplayName,
		arg.Description,
		arg.CollectionName,
		arg.CategoryID,
		arg.PartOfCollectionID,
		arg.ExpectedValueType,
		arg.SetValue,
		arg.IsRequired,
		arg.MinOccurs,
		arg.MaxOccurs,
		arg.IsHidden,
		arg.Visibility,
		arg.ContentHash,
	)
	var i WeaveFieldOverride
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CollectionOrder,
		&i.DisplayName,
		&i.Description,
		&i.CollectionName,
		&i.CategoryID,
		&i.PartOfCollectionID,
		&i.ExpectedValueType,
		&i.SetValue,
		&i.IsRequired,
		&i.MinOccurs,
		&i.MaxOccurs,
		&i.IsHidden,
		&i.Visibility,
		&i.StagingID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.VersionNumber,
		&i.SetValueEntryID,
	)
	return i, err
}

const weaveUpsertBaseOverride = `-- name: WeaveUpsertBaseOverride :one
INSERT INTO weave_field_overrides (
    field_id, project_id, entity_type, entity_id,
    position, collection_order,
    display_name, description, collection_name,
    category_id, part_of_collection_id,
    expected_value_type, set_value,
    is_required, min_occurs, max_occurs, is_hidden, visibility,
    staging_id, content_hash
) VALUES (
    $1, $2, '', '', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (field_id, project_id) WHERE entity_type = '' DO UPDATE SET
    position = EXCLUDED.position,
    collection_order = EXCLUDED.collection_order,
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    collection_name = EXCLUDED.collection_name,
    category_id = EXCLUDED.category_id,
    part_of_collection_id = EXCLUDED.part_of_collection_id,
    expected_value_type = EXCLUDED.expected_value_type,
    set_value = EXCLUDED.set_value,
    is_required = EXCLUDED.is_required,
    min_occurs = EXCLUDED.min_occurs,
    max_occurs = EXCLUDED.max_occurs,
    is_hidden = EXCLUDED.is_hidden,
    visibility = EXCLUDED.visibility,
    staging_id = EXCLUDED.staging_id,
    content_hash = EXCLUDED.content_hash,
    updated_at = NOW()
RETURNING id, field_id, project_id, entity_type, entity_id, position, collection_order, display_name, description, collection_name, category_id, part_of_collection_id, expected_value_type, set_value, is_required, min_occurs, max_occurs, is_hidden, visibility, staging_id, created_at, updated_at, content_hash, version_number, set_value_entry_id
`

type WeaveUpsertBaseOverrideParams struct {
	FieldID            string  `json:"field_id"`
	ProjectID          string  `json:"project_id"`
	Position           int32   `json:"position"`
	CollectionOrder    int32   `json:"collection_order"`
	DisplayName        []byte  `json:"display_name"`
	Description        []byte  `json:"description"`
	CollectionName     []byte  `json:"collection_name"`
	CategoryID         *string `json:"category_id"`
	PartOfCollectionID *string `json:"part_of_collection_id"`
	ExpectedValueType  *string `json:"expected_value_type"`
	SetValue           *string `json:"set_value"`
	IsRequired         *bool   `json:"is_required"`
	MinOccurs          *int32  `json:"min_occurs"`
	MaxOccurs          *int32  `json:"max_occurs"`
	IsHidden           *bool   `json:"is_hidden"`
	Visibility         *string `json:"visibility"`
	StagingID          *int64  `json:"staging_id"`
	ContentHash        *string `json:"content_hash"`
}

// Upsert a base override (entity_type=”). Matches on (field_id, project_id)
// via the partial unique index uniq_wfo_base_field_project.
func (q *Queries) WeaveUpsertBaseOverride(ctx context.Context, arg WeaveUpsertBaseOverrideParams) (WeaveFieldOverride, error) {
	row := q.db.QueryRow(ctx, weaveUpsertBaseOverride,
		arg.FieldID,
		arg.ProjectID,
		arg.Position,
		arg.CollectionOrder,
		arg.DisplayName,
		arg.Description,
		arg.CollectionName,
		arg.CategoryID,
		arg.PartOfCollectionID,
		arg.ExpectedValueType,
		arg.SetValue,
		arg.IsRequired,
		arg.MinOccurs,
		arg.MaxOccurs,
		arg.IsHidden,
		arg.Visibility,
		arg.StagingID,
		arg.ContentHash,
	)
	var i WeaveFieldOverride
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CollectionOrder,
		&i.DisplayName,
		&i.Description,
		&i.CollectionName,
		&i.CategoryID,
		&i.PartOfCollectionID,
		&i.ExpectedValueType,
		&i.SetValue,
		&i.IsRequired,
		&i.MinOccurs,
		&i.MaxOccurs,
		&i.IsHidden,
		&i.Visibility,
		&i.StagingID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.VersionNumber,
		&i.SetValueEntryID,
	)
	return i, err
}
