// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_categories.sql

package sqlcgen

import (
	"context"
	"time"
)

const weaveActivateCategory = `-- name: WeaveActivateCategory :exec
UPDATE weave_categories
SET deprecated = false, updated_at = NOW()
WHERE id = $1
`

// Reverses Deprecate. The category becomes available for new connections
// again.
func (q *Queries) WeaveActivateCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveActivateCategory, id)
	return err
}

const weaveCategoryCollectionFieldOverrides = `-- name: WeaveCategoryCollectionFieldOverrides :many
SELECT
    fo.id                                                AS override_id,
    COALESCE(col.ui_name ->> 'en', col.system_name, '') AS collection_name,
    COALESCE(f.ui_name ->> 'en', f.system_name, '')     AS field_name
FROM weave_field_overrides fo
JOIN weave_collections col ON fo.entity_id = col.id
JOIN weave_fields f ON fo.field_id = f.id
WHERE fo.entity_type = 'collection'
  AND fo.category_id = $1
  AND col.project_id = $2
`

type WeaveCategoryCollectionFieldOverridesParams struct {
	CategoryID *string `json:"category_id"`
	ProjectID  string  `json:"project_id"`
}

type WeaveCategoryCollectionFieldOverridesRow struct {
	OverrideID     int64  `json:"override_id"`
	CollectionName string `json:"collection_name"`
	FieldName      string `json:"field_name"`
}

// Returns collection-scoped field overrides that reference a given category,
// joined with collection name and field name for display.
func (q *Queries) WeaveCategoryCollectionFieldOverrides(ctx context.Context, arg WeaveCategoryCollectionFieldOverridesParams) ([]WeaveCategoryCollectionFieldOverridesRow, error) {
	rows, err := q.db.Query(ctx, weaveCategoryCollectionFieldOverrides, arg.CategoryID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveCategoryCollectionFieldOverridesRow{}
	for rows.Next() {
		var i WeaveCategoryCollectionFieldOverridesRow
		if err := rows.Scan(&i.OverrideID, &i.CollectionName, &i.FieldName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveCategoryIsInUse = `-- name: WeaveCategoryIsInUse :one
SELECT EXISTS (
    SELECT 1 FROM weave_field_overrides
    WHERE category_id != ''
      AND category_id IN ($1::text, $2::text)
) AS in_use
`

type WeaveCategoryIsInUseParams struct {
	CategoryUlid       string `json:"category_ulid"`
	CategorySemanticID string `json:"category_semantic_id"`
}

// Returns true if any field override references this category by ULID or
// semantic_id, across all entity_type values (base, model, collection).
// Hot path: used both server-side (delete preflight) and exposed in list
// responses to gate UI delete buttons.
func (q *Queries) WeaveCategoryIsInUse(ctx context.Context, arg WeaveCategoryIsInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, weaveCategoryIsInUse, arg.CategoryUlid, arg.CategorySemanticID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const weaveCategoryModelFieldOverrides = `-- name: WeaveCategoryModelFieldOverrides :many
SELECT
    fo.id                                              AS override_id,
    COALESCE(m.ui_name ->> 'en', m.system_name, '')   AS model_name,
    COALESCE(f.ui_name ->> 'en', f.system_name, '')   AS field_name
FROM weave_field_overrides fo
JOIN weave_models m ON fo.entity_id = m.id
JOIN weave_fields f ON fo.field_id = f.id
WHERE fo.entity_type = 'model'
  AND fo.category_id = $1
  AND m.project_id = $2
`

type WeaveCategoryModelFieldOverridesParams struct {
	CategoryID *string `json:"category_id"`
	ProjectID  string  `json:"project_id"`
}

type WeaveCategoryModelFieldOverridesRow struct {
	OverrideID int64  `json:"override_id"`
	ModelName  string `json:"model_name"`
	FieldName  string `json:"field_name"`
}

// Returns model-scoped field overrides that reference a given category,
// joined with model name and field name for display.
func (q *Queries) WeaveCategoryModelFieldOverrides(ctx context.Context, arg WeaveCategoryModelFieldOverridesParams) ([]WeaveCategoryModelFieldOverridesRow, error) {
	rows, err := q.db.Query(ctx, weaveCategoryModelFieldOverrides, arg.CategoryID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveCategoryModelFieldOverridesRow{}
	for rows.Next() {
		var i WeaveCategoryModelFieldOverridesRow
		if err := rows.Scan(&i.OverrideID, &i.ModelName, &i.FieldName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveClearFieldOverrideCategory = `-- name: WeaveClearFieldOverrideCategory :exec
UPDATE weave_field_overrides
SET category_id = ''
WHERE category_id = $1
`

// Clears category_id on any field override (base, model, collection) that
// references the given category. Used when a category is deleted.
func (q *Queries) WeaveClearFieldOverrideCategory(ctx context.Context, categoryID *string) error {
	_, err := q.db.Exec(ctx, weaveClearFieldOverrideCategory, categoryID)
	return err
}

const weaveCountCategories = `-- name: WeaveCountCategories :one
SELECT COUNT(*) FROM weave_categories WHERE project_id = $1
`

func (q *Queries) WeaveCountCategories(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountCategories, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveCreateCategory = `-- name: WeaveCreateCategory :one
INSERT INTO weave_categories (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id, canonical_order
) VALUES (
    $1, NOW(), NOW(), $2, $3, $4, $5, $6, $7, $8
) RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, canonical_order, deprecated, version_number
`

type WeaveCreateCategoryParams struct {
	ID             string  `json:"id"`
	SemanticID     *string `json:"semantic_id"`
	SystemName     *string `json:"system_name"`
	UiName         []byte  `json:"ui_name"`
	Description    []byte  `json:"description"`
	Status         string  `json:"status"`
	ProjectID      string  `json:"project_id"`
	CanonicalOrder int32   `json:"canonical_order"`
}

func (q *Queries) WeaveCreateCategory(ctx context.Context, arg WeaveCreateCategoryParams) (WeaveCategory, error) {
	row := q.db.QueryRow(ctx, weaveCreateCategory,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.CanonicalOrder,
	)
	var i WeaveCategory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.CanonicalOrder,
		&i.Deprecated,
		&i.VersionNumber,
	)
	return i, err
}

const weaveDeleteCategory = `-- name: WeaveDeleteCategory :exec
DELETE FROM weave_categories WHERE id = $1
`

func (q *Queries) WeaveDeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteCategory, id)
	return err
}

const weaveDeprecateCategory = `-- name: WeaveDeprecateCategory :exec
UPDATE weave_categories
SET deprecated = true, updated_at = NOW()
WHERE id = $1
`

// Soft-retires a category. Existing references stay intact; pickers stop
// offering it for new connections.
func (q *Queries) WeaveDeprecateCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeprecateCategory, id)
	return err
}

const weaveGetCategoryByID = `-- name: WeaveGetCategoryByID :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, canonical_order, deprecated, version_number FROM weave_categories WHERE id = $1
`

func (q *Queries) WeaveGetCategoryByID(ctx context.Context, id string) (WeaveCategory, error) {
	row := q.db.QueryRow(ctx, weaveGetCategoryByID, id)
	var i WeaveCategory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.CanonicalOrder,
		&i.Deprecated,
		&i.VersionNumber,
	)
	return i, err
}

const weaveGetCategoryByIdentifier = `-- name: WeaveGetCategoryByIdentifier :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, canonical_order, deprecated, version_number FROM weave_categories
WHERE (semantic_id = $1 OR system_name = $1 OR id = $1)
  AND project_id = $2
`

type WeaveGetCategoryByIdentifierParams struct {
	SemanticID *string `json:"semantic_id"`
	ProjectID  string  `json:"project_id"`
}

func (q *Queries) WeaveGetCategoryByIdentifier(ctx context.Context, arg WeaveGetCategoryByIdentifierParams) (WeaveCategory, error) {
	row := q.db.QueryRow(ctx, weaveGetCategoryByIdentifier, arg.SemanticID, arg.ProjectID)
	var i WeaveCategory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.CanonicalOrder,
		&i.Deprecated,
		&i.VersionNumber,
	)
	return i, err
}

const weaveListCategories = `-- name: WeaveListCategories :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, canonical_order, deprecated, version_number FROM weave_categories
WHERE project_id = $1
ORDER BY canonical_order ASC, system_name ASC
`

func (q *Queries) WeaveListCategories(ctx context.Context, projectID string) ([]WeaveCategory, error) {
	rows, err := q.db.Query(ctx, weaveListCategories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveCategory{}
	for rows.Next() {
		var i WeaveCategory
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.CanonicalOrder,
			&i.Deprecated,
			&i.VersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListCategoriesWithCounts = `-- name: WeaveListCategoriesWithCounts :many
SELECT
    c.id, c.created_at, c.updated_at, c.semantic_id, c.system_name, c.ui_name, c.description, c.status, c.project_id, c.canonical_order, c.deprecated, c.version_number,
    (SELECT COUNT(*) FROM weave_field_overrides
     WHERE entity_type = ''
       AND category_id = c.id
       AND project_id = $1::text) as field_count,
    (SELECT COUNT(*) FROM weave_field_overrides
     WHERE entity_type = 'model'
       AND category_id = c.id
       AND project_id = $1::text) as model_field_count,
    (SELECT COUNT(*) FROM weave_field_overrides
     WHERE entity_type = 'collection'
       AND category_id = c.id
       AND project_id = $1::text) as collection_field_count,
    EXISTS (
        SELECT 1 FROM weave_field_overrides fo
        WHERE fo.category_id != ''
          AND fo.category_id IN (c.id, c.semantic_id)
          AND fo.project_id = $1::text
    ) as in_use
FROM weave_categories c
WHERE c.project_id = $1::text
ORDER BY c.canonical_order ASC, c.system_name ASC
`

type WeaveListCategoriesWithCountsRow struct {
	ID                   string    `json:"id"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	SemanticID           *string   `json:"semantic_id"`
	SystemName           *string   `json:"system_name"`
	UiName               []byte    `json:"ui_name"`
	Description          []byte    `json:"description"`
	Status               string    `json:"status"`
	ProjectID            string    `json:"project_id"`
	CanonicalOrder       int32     `json:"canonical_order"`
	Deprecated           bool      `json:"deprecated"`
	VersionNumber        string    `json:"version_number"`
	FieldCount           int64     `json:"field_count"`
	ModelFieldCount      int64     `json:"model_field_count"`
	CollectionFieldCount int64     `json:"collection_field_count"`
	InUse                bool      `json:"in_use"`
}

// Returns each category in the project with its usage counts and a fast
// in_use boolean. Field-level category lives on the base override
// (entity_type=”) after migration 027; in_use accepts either ULID or
// semantic_id matches in any override row (base, model, collection).
func (q *Queries) WeaveListCategoriesWithCounts(ctx context.Context, projectID string) ([]WeaveListCategoriesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, weaveListCategoriesWithCounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListCategoriesWithCountsRow{}
	for rows.Next() {
		var i WeaveListCategoriesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.CanonicalOrder,
			&i.Deprecated,
			&i.VersionNumber,
			&i.FieldCount,
			&i.ModelFieldCount,
			&i.CollectionFieldCount,
			&i.InUse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveReassignFieldsToCategory = `-- name: WeaveReassignFieldsToCategory :exec
UPDATE weave_field_overrides
SET category_id = $2
WHERE category_id = $1
  AND entity_type = ''
  AND project_id = $3
`

type WeaveReassignFieldsToCategoryParams struct {
	CategoryID   *string `json:"category_id"`
	CategoryID_2 *string `json:"category_id_2"`
	ProjectID    string  `json:"project_id"`
}

// Reassigns field-level category from $1 to $2 within the project.
// After migration 027, field category lives on the base override
// (entity_type=”) — this updates that row.
func (q *Queries) WeaveReassignFieldsToCategory(ctx context.Context, arg WeaveReassignFieldsToCategoryParams) error {
	_, err := q.db.Exec(ctx, weaveReassignFieldsToCategory, arg.CategoryID, arg.CategoryID_2, arg.ProjectID)
	return err
}

const weaveUpdateCategory = `-- name: WeaveUpdateCategory :one
UPDATE weave_categories SET
    updated_at = NOW(),
    ui_name = $2,
    description = $3,
    system_name = $4,
    status = $5,
    canonical_order = $6
WHERE id = $1
RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, canonical_order, deprecated, version_number
`

type WeaveUpdateCategoryParams struct {
	ID             string  `json:"id"`
	UiName         []byte  `json:"ui_name"`
	Description    []byte  `json:"description"`
	SystemName     *string `json:"system_name"`
	Status         string  `json:"status"`
	CanonicalOrder int32   `json:"canonical_order"`
}

func (q *Queries) WeaveUpdateCategory(ctx context.Context, arg WeaveUpdateCategoryParams) (WeaveCategory, error) {
	row := q.db.QueryRow(ctx, weaveUpdateCategory,
		arg.ID,
		arg.UiName,
		arg.Description,
		arg.SystemName,
		arg.Status,
		arg.CanonicalOrder,
	)
	var i WeaveCategory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.CanonicalOrder,
		&i.Deprecated,
		&i.VersionNumber,
	)
	return i, err
}

const weaveUpdateCategoryOrder = `-- name: WeaveUpdateCategoryOrder :exec
UPDATE weave_categories
SET canonical_order = $2, updated_at = NOW()
WHERE id = $1
`

type WeaveUpdateCategoryOrderParams struct {
	ID             string `json:"id"`
	CanonicalOrder int32  `json:"canonical_order"`
}

func (q *Queries) WeaveUpdateCategoryOrder(ctx context.Context, arg WeaveUpdateCategoryOrderParams) error {
	_, err := q.db.Exec(ctx, weaveUpdateCategoryOrder, arg.ID, arg.CanonicalOrder)
	return err
}

const weaveUpsertCategory = `-- name: WeaveUpsertCategory :one
INSERT INTO weave_categories (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id, canonical_order
) VALUES (
    $1, NOW(), NOW(), $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    updated_at = NOW(),
    semantic_id = EXCLUDED.semantic_id,
    system_name = EXCLUDED.system_name,
    ui_name = EXCLUDED.ui_name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    project_id = EXCLUDED.project_id,
    canonical_order = EXCLUDED.canonical_order
RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, canonical_order, deprecated, version_number
`

type WeaveUpsertCategoryParams struct {
	ID             string  `json:"id"`
	SemanticID     *string `json:"semantic_id"`
	SystemName     *string `json:"system_name"`
	UiName         []byte  `json:"ui_name"`
	Description    []byte  `json:"description"`
	Status         string  `json:"status"`
	ProjectID      string  `json:"project_id"`
	CanonicalOrder int32   `json:"canonical_order"`
}

func (q *Queries) WeaveUpsertCategory(ctx context.Context, arg WeaveUpsertCategoryParams) (WeaveCategory, error) {
	row := q.db.QueryRow(ctx, weaveUpsertCategory,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.CanonicalOrder,
	)
	var i WeaveCategory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.CanonicalOrder,
		&i.Deprecated,
		&i.VersionNumber,
	)
	return i, err
}
