// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_collections.sql

package sqlcgen

import (
	"context"
	"time"
)

const weaveActivateCollection = `-- name: WeaveActivateCollection :exec
UPDATE weave_collections
SET deprecated = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) WeaveActivateCollection(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveActivateCollection, id)
	return err
}

const weaveCollectionIsInUse = `-- name: WeaveCollectionIsInUse :one
SELECT EXISTS (
    SELECT 1 FROM weave_override_refs r
    JOIN weave_field_overrides o ON o.id = r.override_id
    WHERE r.target_id = $1
      AND r.ref_type IN ('resource_model','collection_model')
      AND o.project_id = $2
    LIMIT 1
)::bool
`

type WeaveCollectionIsInUseParams struct {
	TargetID  string `json:"target_id"`
	ProjectID string `json:"project_id"`
}

// Returns true when any field's override-refs point at this
// collection (ref_type IN ('resource_model','collection_model'),
// target_id = $1). The collection's OWN override rows
// (entity_type='collection', entity_id=$1) are the collection's
// content — they don't count.
func (q *Queries) WeaveCollectionIsInUse(ctx context.Context, arg WeaveCollectionIsInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, weaveCollectionIsInUse, arg.TargetID, arg.ProjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveCollectionUsageCount = `-- name: WeaveCollectionUsageCount :one
SELECT COUNT(DISTINCT o.field_id) AS field_count
FROM weave_override_refs r
JOIN weave_field_overrides o ON o.id = r.override_id
WHERE r.target_id = $1
  AND r.ref_type IN ('resource_model','collection_model')
  AND o.project_id = $2
`

type WeaveCollectionUsageCountParams struct {
	TargetID  string `json:"target_id"`
	ProjectID string `json:"project_id"`
}

// Count of distinct fields referencing this collection as a value target.
func (q *Queries) WeaveCollectionUsageCount(ctx context.Context, arg WeaveCollectionUsageCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCollectionUsageCount, arg.TargetID, arg.ProjectID)
	var field_count int64
	err := row.Scan(&field_count)
	return field_count, err
}

const weaveCollectionUsageSamples = `-- name: WeaveCollectionUsageSamples :many
SELECT DISTINCT
    f.id          AS field_id,
    f.semantic_id AS field_semantic_id,
    COALESCE(f.ui_name ->> 'en', f.system_name, '') AS field_name
FROM weave_override_refs r
JOIN weave_field_overrides o ON o.id = r.override_id
JOIN weave_fields f ON f.id = o.field_id
WHERE r.target_id = $1
  AND r.ref_type IN ('resource_model','collection_model')
  AND o.project_id = $2
ORDER BY field_name
LIMIT 10
`

type WeaveCollectionUsageSamplesParams struct {
	TargetID  string `json:"target_id"`
	ProjectID string `json:"project_id"`
}

type WeaveCollectionUsageSamplesRow struct {
	FieldID         string  `json:"field_id"`
	FieldSemanticID *string `json:"field_semantic_id"`
	FieldName       string  `json:"field_name"`
}

// Up to 10 sample fields referencing this collection as a value target.
func (q *Queries) WeaveCollectionUsageSamples(ctx context.Context, arg WeaveCollectionUsageSamplesParams) ([]WeaveCollectionUsageSamplesRow, error) {
	rows, err := q.db.Query(ctx, weaveCollectionUsageSamples, arg.TargetID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveCollectionUsageSamplesRow{}
	for rows.Next() {
		var i WeaveCollectionUsageSamplesRow
		if err := rows.Scan(&i.FieldID, &i.FieldSemanticID, &i.FieldName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveCountCollections = `-- name: WeaveCountCollections :one
SELECT COUNT(*) FROM weave_collections
WHERE project_id = $1::text
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR system_name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR ((ontology_scope::jsonb->>'prefix') || ':' || (ontology_scope::jsonb->>'local_name')) = ANY(string_to_array($3::text, ',')))
  AND ($4::text = '' OR default_category_id = ANY(string_to_array($4::text, ',')))
`

type WeaveCountCollectionsParams struct {
	ProjectID  string `json:"project_id"`
	Search     string `json:"search"`
	ScopeClass string `json:"scope_class"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) WeaveCountCollections(ctx context.Context, arg WeaveCountCollectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountCollections,
		arg.ProjectID,
		arg.Search,
		arg.ScopeClass,
		arg.CategoryID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveCreateCollection = `-- name: WeaveCreateCollection :one
INSERT INTO weave_collections (
    id, system_name, ui_name, description,
    status, project_id, ontology_scope,
    collection_number, canonical_collection_order,
    default_category_id, staging_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, collection_number, canonical_collection_order, staging_id, deprecated, default_category_id, version_number
`

type WeaveCreateCollectionParams struct {
	ID                       string  `json:"id"`
	SystemName               *string `json:"system_name"`
	UiName                   []byte  `json:"ui_name"`
	Description              []byte  `json:"description"`
	Status                   string  `json:"status"`
	ProjectID                string  `json:"project_id"`
	OntologyScope            []byte  `json:"ontology_scope"`
	CollectionNumber         *int32  `json:"collection_number"`
	CanonicalCollectionOrder *int32  `json:"canonical_collection_order"`
	DefaultCategoryID        *string `json:"default_category_id"`
	StagingID                *int64  `json:"staging_id"`
}

func (q *Queries) WeaveCreateCollection(ctx context.Context, arg WeaveCreateCollectionParams) (WeaveCollection, error) {
	row := q.db.QueryRow(ctx, weaveCreateCollection,
		arg.ID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.OntologyScope,
		arg.CollectionNumber,
		arg.CanonicalCollectionOrder,
		arg.DefaultCategoryID,
		arg.StagingID,
	)
	var i WeaveCollection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.CollectionNumber,
		&i.CanonicalCollectionOrder,
		&i.StagingID,
		&i.Deprecated,
		&i.DefaultCategoryID,
		&i.VersionNumber,
	)
	return i, err
}

const weaveDeleteCollection = `-- name: WeaveDeleteCollection :exec
DELETE FROM weave_collections WHERE id = $1
`

func (q *Queries) WeaveDeleteCollection(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteCollection, id)
	return err
}

const weaveDeprecateCollection = `-- name: WeaveDeprecateCollection :exec
UPDATE weave_collections
SET deprecated = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) WeaveDeprecateCollection(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeprecateCollection, id)
	return err
}

const weaveGetCollectionByID = `-- name: WeaveGetCollectionByID :one
SELECT id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, collection_number, canonical_collection_order, staging_id, deprecated, default_category_id, version_number FROM weave_collections WHERE id = $1
`

func (q *Queries) WeaveGetCollectionByID(ctx context.Context, id string) (WeaveCollection, error) {
	row := q.db.QueryRow(ctx, weaveGetCollectionByID, id)
	var i WeaveCollection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.CollectionNumber,
		&i.CanonicalCollectionOrder,
		&i.StagingID,
		&i.Deprecated,
		&i.DefaultCategoryID,
		&i.VersionNumber,
	)
	return i, err
}

const weaveGetCollectionByIdentifier = `-- name: WeaveGetCollectionByIdentifier :one
SELECT id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, collection_number, canonical_collection_order, staging_id, deprecated, default_category_id, version_number FROM weave_collections
WHERE project_id = $1::text
  AND (system_name = $2::text OR id = $2::text)
LIMIT 1
`

type WeaveGetCollectionByIdentifierParams struct {
	ProjectID  string `json:"project_id"`
	Identifier string `json:"identifier"`
}

func (q *Queries) WeaveGetCollectionByIdentifier(ctx context.Context, arg WeaveGetCollectionByIdentifierParams) (WeaveCollection, error) {
	row := q.db.QueryRow(ctx, weaveGetCollectionByIdentifier, arg.ProjectID, arg.Identifier)
	var i WeaveCollection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.CollectionNumber,
		&i.CanonicalCollectionOrder,
		&i.StagingID,
		&i.Deprecated,
		&i.DefaultCategoryID,
		&i.VersionNumber,
	)
	return i, err
}

const weaveGetCollectionNamesByIDs = `-- name: WeaveGetCollectionNamesByIDs :many
SELECT id, ui_name FROM weave_collections WHERE id = ANY($1::text[])
`

type WeaveGetCollectionNamesByIDsRow struct {
	ID     string `json:"id"`
	UiName []byte `json:"ui_name"`
}

func (q *Queries) WeaveGetCollectionNamesByIDs(ctx context.Context, ids []string) ([]WeaveGetCollectionNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, weaveGetCollectionNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveGetCollectionNamesByIDsRow{}
	for rows.Next() {
		var i WeaveGetCollectionNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.UiName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListCollectionCategoriesForProject = `-- name: WeaveListCollectionCategoriesForProject :many
SELECT id, ui_name, canonical_order
FROM weave_categories
WHERE project_id = $1
ORDER BY canonical_order ASC, id ASC
`

type WeaveListCollectionCategoriesForProjectRow struct {
	ID             string `json:"id"`
	UiName         []byte `json:"ui_name"`
	CanonicalOrder int32  `json:"canonical_order"`
}

// All categories defined in this project. Used to populate the category
// filter dropdown on the collection list. The previous
// USED-only join silently returned 0 rows on projects whose collections
// weren't yet tagged with default_category_id — making the filter look
// broken to the customer. All-categories is symmetric with how
// categories surface elsewhere in the project (sidebar, drafts).
func (q *Queries) WeaveListCollectionCategoriesForProject(ctx context.Context, projectID string) ([]WeaveListCollectionCategoriesForProjectRow, error) {
	rows, err := q.db.Query(ctx, weaveListCollectionCategoriesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListCollectionCategoriesForProjectRow{}
	for rows.Next() {
		var i WeaveListCollectionCategoriesForProjectRow
		if err := rows.Scan(&i.ID, &i.UiName, &i.CanonicalOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListCollectionOptions = `-- name: WeaveListCollectionOptions :many
SELECT id, system_name, ui_name, status, collection_number
FROM weave_collections
WHERE project_id = $1::text
  AND deprecated = false
ORDER BY canonical_collection_order ASC, system_name ASC
`

type WeaveListCollectionOptionsRow struct {
	ID               string  `json:"id"`
	SystemName       *string `json:"system_name"`
	UiName           []byte  `json:"ui_name"`
	Status           string  `json:"status"`
	CollectionNumber *int32  `json:"collection_number"`
}

// Lightweight options list for ref pickers — only the columns the UI needs.
// No COUNT companion query, no path/scope/staging payload, no search arg.
// Ordered the same as WeaveListCollections so the dropdown matches the
// canonical list order curators see in the project page.
func (q *Queries) WeaveListCollectionOptions(ctx context.Context, projectID string) ([]WeaveListCollectionOptionsRow, error) {
	rows, err := q.db.Query(ctx, weaveListCollectionOptions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListCollectionOptionsRow{}
	for rows.Next() {
		var i WeaveListCollectionOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemName,
			&i.UiName,
			&i.Status,
			&i.CollectionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListCollectionScopeClasses = `-- name: WeaveListCollectionScopeClasses :many
SELECT DISTINCT ((ontology_scope::jsonb->>'prefix') || ':' || (ontology_scope::jsonb->>'local_name'))::text AS scope_class
FROM weave_collections
WHERE project_id = $1
  AND ontology_scope IS NOT NULL
  AND ontology_scope->>'prefix' IS NOT NULL
  AND ontology_scope->>'local_name' IS NOT NULL
ORDER BY scope_class ASC
`

// Returns distinct ontology scope classes (prefix:local_name) used by
// collections in this project. Drives the scope_class filter dropdown
// on the collection list.
func (q *Queries) WeaveListCollectionScopeClasses(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveListCollectionScopeClasses, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scope_class string
		if err := rows.Scan(&scope_class); err != nil {
			return nil, err
		}
		items = append(items, scope_class)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListCollections = `-- name: WeaveListCollections :many
SELECT id, created_at, updated_at, system_name, ui_name, description,
       status, project_id, ontology_scope, collection_number,
       canonical_collection_order, staging_id, deprecated, default_category_id
FROM weave_collections
WHERE project_id = $1::text
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR system_name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR ((ontology_scope::jsonb->>'prefix') || ':' || (ontology_scope::jsonb->>'local_name')) = ANY(string_to_array($3::text, ',')))
  AND ($4::text = '' OR default_category_id = ANY(string_to_array($4::text, ',')))
ORDER BY
    CASE WHEN $5::text = 'ui_name' AND NOT $6::boolean THEN ui_name->>'en' END ASC NULLS LAST,
    CASE WHEN $5::text = 'ui_name' AND $6::boolean THEN ui_name->>'en' END DESC NULLS LAST,
    CASE WHEN $5::text = 'name' AND NOT $6::boolean THEN system_name END ASC NULLS LAST,
    CASE WHEN $5::text = 'name' AND $6::boolean THEN system_name END DESC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND NOT $6::boolean THEN system_name END ASC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND $6::boolean THEN system_name END DESC NULLS LAST,
    CASE WHEN $5::text = 'updated_at' AND NOT $6::boolean THEN updated_at END ASC,
    CASE WHEN $5::text = 'updated_at' AND $6::boolean THEN updated_at END DESC,
    canonical_collection_order ASC, system_name ASC
LIMIT $8::integer OFFSET $7::integer
`

type WeaveListCollectionsParams struct {
	ProjectID    string `json:"project_id"`
	Search       string `json:"search"`
	ScopeClass   string `json:"scope_class"`
	CategoryID   string `json:"category_id"`
	SortBy       string `json:"sort_by"`
	SortDesc     bool   `json:"sort_desc"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type WeaveListCollectionsRow struct {
	ID                       string    `json:"id"`
	CreatedAt                time.Time `json:"created_at"`
	UpdatedAt                time.Time `json:"updated_at"`
	SystemName               *string   `json:"system_name"`
	UiName                   []byte    `json:"ui_name"`
	Description              []byte    `json:"description"`
	Status                   string    `json:"status"`
	ProjectID                string    `json:"project_id"`
	OntologyScope            []byte    `json:"ontology_scope"`
	CollectionNumber         *int32    `json:"collection_number"`
	CanonicalCollectionOrder *int32    `json:"canonical_collection_order"`
	StagingID                *int64    `json:"staging_id"`
	Deprecated               bool      `json:"deprecated"`
	DefaultCategoryID        *string   `json:"default_category_id"`
}

func (q *Queries) WeaveListCollections(ctx context.Context, arg WeaveListCollectionsParams) ([]WeaveListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, weaveListCollections,
		arg.ProjectID,
		arg.Search,
		arg.ScopeClass,
		arg.CategoryID,
		arg.SortBy,
		arg.SortDesc,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListCollectionsRow{}
	for rows.Next() {
		var i WeaveListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.CollectionNumber,
			&i.CanonicalCollectionOrder,
			&i.StagingID,
			&i.Deprecated,
			&i.DefaultCategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListReceiptCollectionClosure = `-- name: WeaveListReceiptCollectionClosure :many
WITH RECURSIVE walk(kind, id) AS (
    SELECT $2::text AS kind, $1::text AS id
  UNION
    SELECT nxt.kind, nxt.id
    FROM walk w
    JOIN weave_field_overrides o ON o.entity_type = w.kind AND o.entity_id = w.id
    JOIN weave_override_refs r ON r.override_id = o.id
    CROSS JOIN LATERAL (
      SELECT 'model'::text AS kind, m.id
      FROM weave_models m
      WHERE m.id = r.target_id AND r.ref_type = 'resource_model'
      UNION ALL
      SELECT 'collection'::text, c.id
      FROM weave_collections c
      WHERE c.id = r.target_id AND r.ref_type = 'collection_model'
    ) nxt
)
SELECT DISTINCT id FROM walk WHERE kind = 'collection'
`

type WeaveListReceiptCollectionClosureParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// Returns every collection in the transitive closure rooted at the
// receipt seed (source_entity_id + entity_type). Drives the
// per-receipt bill-of-materials on the Adoptions tab. Walker pattern
// mirrors the model closure — both kinds traverse the same
// override-ref graph, only the final filter differs.
func (q *Queries) WeaveListReceiptCollectionClosure(ctx context.Context, arg WeaveListReceiptCollectionClosureParams) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveListReceiptCollectionClosure, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListReceiptCollectionDirect = `-- name: WeaveListReceiptCollectionDirect :many
SELECT DISTINCT c.id
FROM weave_field_overrides o
JOIN weave_override_refs r ON r.override_id = o.id AND r.ref_type = 'collection_model'
JOIN weave_collections c ON c.id = r.target_id
WHERE o.entity_type = $2::text AND o.entity_id = $1::text
`

type WeaveListReceiptCollectionDirectParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// Direct (depth-1) collection references from the receipt seed —
// every collection that the seed's overrides reference via a
// collection_model override ref. Pairs with
// WeaveListReceiptCollectionClosure (transitive). Both queries follow
// the same edge type (override refs) so direct ≤ transitive holds.
// part_of_collection_id is a separate relationship on the override
// row and is intentionally excluded — the closure walker doesn't
// traverse it either.
func (q *Queries) WeaveListReceiptCollectionDirect(ctx context.Context, arg WeaveListReceiptCollectionDirectParams) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveListReceiptCollectionDirect, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListReferenceAdoptedCollections = `-- name: WeaveListReferenceAdoptedCollections :many
SELECT DISTINCT c.id, c.created_at, c.updated_at, c.system_name, c.ui_name, c.description, c.status, c.project_id, c.ontology_scope, c.collection_number, c.canonical_collection_order, c.staging_id, c.deprecated, c.default_category_id, c.version_number
FROM weave_collections c
JOIN weave_field_overrides o ON o.part_of_collection_id = c.id
WHERE o.project_id = $1
  AND COALESCE(o.part_of_collection_id, '') <> ''
  AND c.project_id <> $1
ORDER BY c.id
`

// Returns every collection from another project that the current
// project's field overrides reference via part_of_collection_id.
// Drives the "Adopted (by reference)" slice of the collection list
// rule (adopt/adapt rollout plan, task 3b).
func (q *Queries) WeaveListReferenceAdoptedCollections(ctx context.Context, projectID string) ([]WeaveCollection, error) {
	rows, err := q.db.Query(ctx, weaveListReferenceAdoptedCollections, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveCollection{}
	for rows.Next() {
		var i WeaveCollection
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.CollectionNumber,
			&i.CanonicalCollectionOrder,
			&i.StagingID,
			&i.Deprecated,
			&i.DefaultCategoryID,
			&i.VersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveUpdateCollection = `-- name: WeaveUpdateCollection :one
UPDATE weave_collections SET
    ui_name = $2, description = $3, system_name = $4, status = $5,
    ontology_scope = $6, collection_number = $7, canonical_collection_order = $8,
    default_category_id = $9,
    updated_at = NOW()
WHERE id = $1 RETURNING id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, collection_number, canonical_collection_order, staging_id, deprecated, default_category_id, version_number
`

type WeaveUpdateCollectionParams struct {
	ID                       string  `json:"id"`
	UiName                   []byte  `json:"ui_name"`
	Description              []byte  `json:"description"`
	SystemName               *string `json:"system_name"`
	Status                   string  `json:"status"`
	OntologyScope            []byte  `json:"ontology_scope"`
	CollectionNumber         *int32  `json:"collection_number"`
	CanonicalCollectionOrder *int32  `json:"canonical_collection_order"`
	DefaultCategoryID        *string `json:"default_category_id"`
}

func (q *Queries) WeaveUpdateCollection(ctx context.Context, arg WeaveUpdateCollectionParams) (WeaveCollection, error) {
	row := q.db.QueryRow(ctx, weaveUpdateCollection,
		arg.ID,
		arg.UiName,
		arg.Description,
		arg.SystemName,
		arg.Status,
		arg.OntologyScope,
		arg.CollectionNumber,
		arg.CanonicalCollectionOrder,
		arg.DefaultCategoryID,
	)
	var i WeaveCollection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.CollectionNumber,
		&i.CanonicalCollectionOrder,
		&i.StagingID,
		&i.Deprecated,
		&i.DefaultCategoryID,
		&i.VersionNumber,
	)
	return i, err
}

const weaveUpsertCollection = `-- name: WeaveUpsertCollection :one
INSERT INTO weave_collections (
    id, system_name, ui_name, description,
    status, project_id, ontology_scope,
    collection_number, canonical_collection_order,
    default_category_id, staging_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    system_name = EXCLUDED.system_name,
    ui_name = EXCLUDED.ui_name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    project_id = EXCLUDED.project_id,
    ontology_scope = EXCLUDED.ontology_scope,
    collection_number = EXCLUDED.collection_number,
    canonical_collection_order = EXCLUDED.canonical_collection_order,
    default_category_id = EXCLUDED.default_category_id,
    staging_id = EXCLUDED.staging_id,
    updated_at = NOW()
RETURNING id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, collection_number, canonical_collection_order, staging_id, deprecated, default_category_id, version_number
`

type WeaveUpsertCollectionParams struct {
	ID                       string  `json:"id"`
	SystemName               *string `json:"system_name"`
	UiName                   []byte  `json:"ui_name"`
	Description              []byte  `json:"description"`
	Status                   string  `json:"status"`
	ProjectID                string  `json:"project_id"`
	OntologyScope            []byte  `json:"ontology_scope"`
	CollectionNumber         *int32  `json:"collection_number"`
	CanonicalCollectionOrder *int32  `json:"canonical_collection_order"`
	DefaultCategoryID        *string `json:"default_category_id"`
	StagingID                *int64  `json:"staging_id"`
}

func (q *Queries) WeaveUpsertCollection(ctx context.Context, arg WeaveUpsertCollectionParams) (WeaveCollection, error) {
	row := q.db.QueryRow(ctx, weaveUpsertCollection,
		arg.ID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.OntologyScope,
		arg.CollectionNumber,
		arg.CanonicalCollectionOrder,
		arg.DefaultCategoryID,
		arg.StagingID,
	)
	var i WeaveCollection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.CollectionNumber,
		&i.CanonicalCollectionOrder,
		&i.StagingID,
		&i.Deprecated,
		&i.DefaultCategoryID,
		&i.VersionNumber,
	)
	return i, err
}
