// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_project_attributions.sql

package sqlcgen

import (
	"context"
	"time"
)

const weaveDeleteProjectAttribution = `-- name: WeaveDeleteProjectAttribution :exec
DELETE FROM weave_project_attributions
WHERE project_id = $1 AND actor_id = $2 AND kind = $3 AND position = $4
`

type WeaveDeleteProjectAttributionParams struct {
	ProjectID string `json:"project_id"`
	ActorID   string `json:"actor_id"`
	Kind      string `json:"kind"`
	Position  int32  `json:"position"`
}

// Removes one specific row (the combination uniquely identifies it).
func (q *Queries) WeaveDeleteProjectAttribution(ctx context.Context, arg WeaveDeleteProjectAttributionParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteProjectAttribution,
		arg.ProjectID,
		arg.ActorID,
		arg.Kind,
		arg.Position,
	)
	return err
}

const weaveDeleteProjectAttributionsByKind = `-- name: WeaveDeleteProjectAttributionsByKind :exec
DELETE FROM weave_project_attributions
WHERE project_id = $1 AND kind = $2
`

type WeaveDeleteProjectAttributionsByKindParams struct {
	ProjectID string `json:"project_id"`
	Kind      string `json:"kind"`
}

// Wipes a (project, kind) bucket. Called by the loader before
// re-inserting so removed names disappear on re-import. Settings UI
// does not use this.
func (q *Queries) WeaveDeleteProjectAttributionsByKind(ctx context.Context, arg WeaveDeleteProjectAttributionsByKindParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteProjectAttributionsByKind, arg.ProjectID, arg.Kind)
	return err
}

const weaveInsertProjectAttribution = `-- name: WeaveInsertProjectAttribution :one
INSERT INTO weave_project_attributions (project_id, actor_id, kind, position, note)
VALUES (
    $1, $2, $3,
    COALESCE(
        (SELECT MAX(position) + 1
         FROM weave_project_attributions
         WHERE project_id = $1 AND kind = $3),
        0
    ),
    $4
)
RETURNING project_id, actor_id, kind, position, note, created_at
`

type WeaveInsertProjectAttributionParams struct {
	ProjectID string `json:"project_id"`
	ActorID   string `json:"actor_id"`
	Kind      string `json:"kind"`
	Note      string `json:"note"`
}

// Append-style insert that picks the next position within the
// (project, kind) bucket. Used by both the importer wave and the
// settings POST handler.
func (q *Queries) WeaveInsertProjectAttribution(ctx context.Context, arg WeaveInsertProjectAttributionParams) (WeaveProjectAttribution, error) {
	row := q.db.QueryRow(ctx, weaveInsertProjectAttribution,
		arg.ProjectID,
		arg.ActorID,
		arg.Kind,
		arg.Note,
	)
	var i WeaveProjectAttribution
	err := row.Scan(
		&i.ProjectID,
		&i.ActorID,
		&i.Kind,
		&i.Position,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const weaveInsertProjectAttributionAt = `-- name: WeaveInsertProjectAttributionAt :one
INSERT INTO weave_project_attributions (project_id, actor_id, kind, position, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, actor_id, kind, position) DO UPDATE SET
    note = EXCLUDED.note
RETURNING project_id, actor_id, kind, position, note, created_at
`

type WeaveInsertProjectAttributionAtParams struct {
	ProjectID string `json:"project_id"`
	ActorID   string `json:"actor_id"`
	Kind      string `json:"kind"`
	Position  int32  `json:"position"`
	Note      string `json:"note"`
}

// Explicit-position variant used by the loader wave so the source
// order of "George Bruseker, Veselina Kalkandzhieva" is preserved.
func (q *Queries) WeaveInsertProjectAttributionAt(ctx context.Context, arg WeaveInsertProjectAttributionAtParams) (WeaveProjectAttribution, error) {
	row := q.db.QueryRow(ctx, weaveInsertProjectAttributionAt,
		arg.ProjectID,
		arg.ActorID,
		arg.Kind,
		arg.Position,
		arg.Note,
	)
	var i WeaveProjectAttribution
	err := row.Scan(
		&i.ProjectID,
		&i.ActorID,
		&i.Kind,
		&i.Position,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const weaveListProjectAttributions = `-- name: WeaveListProjectAttributions :many
SELECT
    a.project_id,
    a.actor_id,
    a.kind,
    a.position,
    a.note,
    a.created_at,
    act.display_name AS actor_name,
    act.type         AS actor_type
FROM weave_project_attributions a
JOIN weave_actors act ON act.id = a.actor_id
WHERE a.project_id = $1
ORDER BY
    CASE a.kind WHEN 'author' THEN 0 WHEN 'funder' THEN 1 WHEN 'adopter' THEN 2 ELSE 3 END,
    a.position ASC
`

type WeaveListProjectAttributionsRow struct {
	ProjectID string    `json:"project_id"`
	ActorID   string    `json:"actor_id"`
	Kind      string    `json:"kind"`
	Position  int32     `json:"position"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
	ActorName string    `json:"actor_name"`
	ActorType string    `json:"actor_type"`
}

// Lists attribution rows for a single project, joined with the actor for
// display name + type. Ordered by kind then position so the credits
// panel renders authors → funders → adopters in source order.
func (q *Queries) WeaveListProjectAttributions(ctx context.Context, projectID string) ([]WeaveListProjectAttributionsRow, error) {
	rows, err := q.db.Query(ctx, weaveListProjectAttributions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListProjectAttributionsRow{}
	for rows.Next() {
		var i WeaveListProjectAttributionsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ActorID,
			&i.Kind,
			&i.Position,
			&i.Note,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListProjectAttributionsForProjects = `-- name: WeaveListProjectAttributionsForProjects :many
SELECT
    a.project_id,
    a.actor_id,
    a.kind,
    a.position,
    a.note,
    a.created_at,
    act.display_name AS actor_name,
    act.type         AS actor_type
FROM weave_project_attributions a
JOIN weave_actors act ON act.id = a.actor_id
WHERE a.project_id = ANY($1::text[])
ORDER BY
    a.project_id,
    CASE a.kind WHEN 'author' THEN 0 WHEN 'funder' THEN 1 WHEN 'adopter' THEN 2 ELSE 3 END,
    a.position ASC
`

type WeaveListProjectAttributionsForProjectsRow struct {
	ProjectID string    `json:"project_id"`
	ActorID   string    `json:"actor_id"`
	Kind      string    `json:"kind"`
	Position  int32     `json:"position"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
	ActorName string    `json:"actor_name"`
	ActorType string    `json:"actor_type"`
}

// Same shape, batched over a set of project IDs.
func (q *Queries) WeaveListProjectAttributionsForProjects(ctx context.Context, dollar_1 []string) ([]WeaveListProjectAttributionsForProjectsRow, error) {
	rows, err := q.db.Query(ctx, weaveListProjectAttributionsForProjects, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListProjectAttributionsForProjectsRow{}
	for rows.Next() {
		var i WeaveListProjectAttributionsForProjectsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ActorID,
			&i.Kind,
			&i.Position,
			&i.Note,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSetProjectAttributionPosition = `-- name: WeaveSetProjectAttributionPosition :exec
UPDATE weave_project_attributions
SET position = $5
WHERE project_id = $1 AND actor_id = $2 AND kind = $3 AND position = $4
`

type WeaveSetProjectAttributionPositionParams struct {
	ProjectID  string `json:"project_id"`
	ActorID    string `json:"actor_id"`
	Kind       string `json:"kind"`
	Position   int32  `json:"position"`
	Position_2 int32  `json:"position_2"`
}

// Moves one row to a new position within its (project, kind) bucket.
// The settings reorder handler issues this once per row in the
// requested order.
func (q *Queries) WeaveSetProjectAttributionPosition(ctx context.Context, arg WeaveSetProjectAttributionPositionParams) error {
	_, err := q.db.Exec(ctx, weaveSetProjectAttributionPosition,
		arg.ProjectID,
		arg.ActorID,
		arg.Kind,
		arg.Position,
		arg.Position_2,
	)
	return err
}

const weaveUpdateProjectAttributionNote = `-- name: WeaveUpdateProjectAttributionNote :exec
UPDATE weave_project_attributions
SET note = $5
WHERE project_id = $1 AND actor_id = $2 AND kind = $3 AND position = $4
`

type WeaveUpdateProjectAttributionNoteParams struct {
	ProjectID string `json:"project_id"`
	ActorID   string `json:"actor_id"`
	Kind      string `json:"kind"`
	Position  int32  `json:"position"`
	Note      string `json:"note"`
}

// Edit the freeform "what they did" note on one row. Actor + kind +
// position are immutable (delete + re-add to change those).
func (q *Queries) WeaveUpdateProjectAttributionNote(ctx context.Context, arg WeaveUpdateProjectAttributionNoteParams) error {
	_, err := q.db.Exec(ctx, weaveUpdateProjectAttributionNote,
		arg.ProjectID,
		arg.ActorID,
		arg.Kind,
		arg.Position,
		arg.Note,
	)
	return err
}
