// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_vocabulary.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const weaveAddProjectServiceVocabulary = `-- name: WeaveAddProjectServiceVocabulary :one
INSERT INTO weave_vocabularies (id, project_id, system_name, ui_name, base_uri, connector_type, config, status, created_at, updated_at)
VALUES ($1::text, $2::text, $3::text, $4::jsonb, NULLIF($5::text, ''), 'vocabservice', $6::jsonb, 'published', NOW(), NOW())
ON CONFLICT (project_id, system_name) WHERE system_name IS NOT NULL AND system_name <> ''
DO UPDATE SET
    deprecated = false,
    status = 'published',
    ui_name = EXCLUDED.ui_name,
    base_uri = EXCLUDED.base_uri,
    config = EXCLUDED.config,
    updated_at = NOW()
WHERE weave_vocabularies.deprecated
RETURNING id
`

type WeaveAddProjectServiceVocabularyParams struct {
	ID         string          `json:"id"`
	ProjectID  string          `json:"project_id"`
	SystemName string          `json:"system_name"`
	UiName     json.RawMessage `json:"ui_name"`
	BaseUri    string          `json:"base_uri"`
	Config     json.RawMessage `json:"config"`
}

// Enabling a service vocabulary for a project IS creating its row.
//
// Adding a mount the project removed earlier REVIVES that row rather than
// inserting a second one. Removal deprecates rather than deletes, so the old
// row still holds (project_id, system_name) in the partial unique index from
// migration 014 — without the upsert, removing a vocabulary would be a
// one-way door, and the add would fail with "already added to this project"
// while the screen showed it as removed. Reviving also brings back the
// entries cached under that row, which is what a curator re-adding a source
// they had pinned terms from would expect.
//
// The DO UPDATE is guarded on the existing row being deprecated, so adding a
// mount that is genuinely still there updates nothing and returns no row —
// which the store maps to the 409 conflict. The conflict target repeats the
// index's predicate so Postgres can infer the partial index.
func (q *Queries) WeaveAddProjectServiceVocabulary(ctx context.Context, arg WeaveAddProjectServiceVocabularyParams) (string, error) {
	row := q.db.QueryRow(ctx, weaveAddProjectServiceVocabulary,
		arg.ID,
		arg.ProjectID,
		arg.SystemName,
		arg.UiName,
		arg.BaseUri,
		arg.Config,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const weaveConceptListDecoration = `-- name: WeaveConceptListDecoration :many
SELECT
    cl.id,
    COALESCE(v.id, '') AS vocabulary_id,
    COALESCE(v.semantic_id, '') AS vocabulary_semantic_id,
    COALESCE(v.system_name, '') AS vocabulary_system_name,
    COALESCE(v.ui_name, '{}'::jsonb) AS vocabulary_ui_name,
    COALESCE(v.base_uri, '') AS vocabulary_base_uri,
    COALESCE(lte.id, '') AS list_type_id,
    COALESCE(lte.vocabulary_id, '') AS list_type_vocabulary_id,
    COALESCE(lte.uri, '') AS list_type_uri,
    COALESCE(lte.label, '{}'::jsonb) AS list_type_label,
    COALESCE(lte.scope_note, '{}'::jsonb) AS list_type_scope_note,
    COALESCE(lte.broader_uri, '') AS list_type_broader_uri,
    COALESCE(lte.external_id, '') AS list_type_external_id,
    COUNT(DISTINCT cle.id) AS entry_count,
    COUNT(DISTINCT fo.field_id) AS bound_field_count
FROM weave_concept_lists cl
LEFT JOIN weave_vocabularies v ON v.id = cl.vocabulary_id
LEFT JOIN weave_vocabulary_entries lte ON lte.id = cl.list_type
LEFT JOIN weave_concept_list_entries cle ON cle.concept_list_id = cl.id
LEFT JOIN weave_override_refs r
    ON r.ref_type = 'concept_list'
    AND (r.target_id = cl.id OR r.semantic_id = cl.semantic_id)
LEFT JOIN weave_field_overrides fo
    ON fo.id = r.override_id
    AND fo.project_id = cl.project_id
WHERE cl.project_id = $1
GROUP BY cl.id, v.id, v.semantic_id, v.system_name, v.ui_name, v.base_uri, lte.id, lte.vocabulary_id, lte.uri, lte.label, lte.scope_note, lte.broader_uri, lte.external_id
`

type WeaveConceptListDecorationRow struct {
	ID                   string          `json:"id"`
	VocabularyID         string          `json:"vocabulary_id"`
	VocabularySemanticID string          `json:"vocabulary_semantic_id"`
	VocabularySystemName string          `json:"vocabulary_system_name"`
	VocabularyUiName     []byte          `json:"vocabulary_ui_name"`
	VocabularyBaseUri    string          `json:"vocabulary_base_uri"`
	ListTypeID           string          `json:"list_type_id"`
	ListTypeVocabularyID string          `json:"list_type_vocabulary_id"`
	ListTypeUri          string          `json:"list_type_uri"`
	ListTypeLabel        json.RawMessage `json:"list_type_label"`
	ListTypeScopeNote    []byte          `json:"list_type_scope_note"`
	ListTypeBroaderUri   string          `json:"list_type_broader_uri"`
	ListTypeExternalID   string          `json:"list_type_external_id"`
	EntryCount           int64           `json:"entry_count"`
	BoundFieldCount      int64           `json:"bound_field_count"`
}

// The vocabulary and bound-field decoration beside each of a project's concept lists.  (was decorateConceptLists)
func (q *Queries) WeaveConceptListDecoration(ctx context.Context, projectID string) ([]WeaveConceptListDecorationRow, error) {
	rows, err := q.db.Query(ctx, weaveConceptListDecoration, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveConceptListDecorationRow{}
	for rows.Next() {
		var i WeaveConceptListDecorationRow
		if err := rows.Scan(
			&i.ID,
			&i.VocabularyID,
			&i.VocabularySemanticID,
			&i.VocabularySystemName,
			&i.VocabularyUiName,
			&i.VocabularyBaseUri,
			&i.ListTypeID,
			&i.ListTypeVocabularyID,
			&i.ListTypeUri,
			&i.ListTypeLabel,
			&i.ListTypeScopeNote,
			&i.ListTypeBroaderUri,
			&i.ListTypeExternalID,
			&i.EntryCount,
			&i.BoundFieldCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveConceptListOverrideRefCount = `-- name: WeaveConceptListOverrideRefCount :one
SELECT COUNT(DISTINCT fo.field_id)
FROM weave_override_refs r
JOIN weave_field_overrides fo ON fo.id = r.override_id
WHERE fo.project_id = $1
  AND r.ref_type = 'concept_list'
  AND (r.target_id = $2 OR r.semantic_id = $3)
`

type WeaveConceptListOverrideRefCountParams struct {
	ProjectID  string `json:"project_id"`
	TargetID   string `json:"target_id"`
	SemanticID string `json:"semantic_id"`
}

// How many distinct fields reference the list through an override; the delete guard.  (was DeleteConceptList)
func (q *Queries) WeaveConceptListOverrideRefCount(ctx context.Context, arg WeaveConceptListOverrideRefCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveConceptListOverrideRefCount, arg.ProjectID, arg.TargetID, arg.SemanticID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveConceptURIInLists = `-- name: WeaveConceptURIInLists :one
SELECT EXISTS (
    SELECT 1
    FROM weave_concept_lists cl
    JOIN weave_concept_list_entries cle ON cle.concept_list_id = cl.id
    JOIN weave_vocabulary_entries ve ON ve.id = cle.vocabulary_entry_id AND ve.uri = $1::text
    WHERE (cl.id = ANY($2::text[]) OR cl.semantic_id = ANY($2::text[]))
) AS present
`

type WeaveConceptURIInListsParams struct {
	Uri string   `json:"uri"`
	Ids []string `json:"ids"`
}

// Whether a concept URI is an explicit entry of any of the given concept lists
// (by id or semantic id). Used to validate a field's set_value against its
// bound control list(s) (#3599).
func (q *Queries) WeaveConceptURIInLists(ctx context.Context, arg WeaveConceptURIInListsParams) (bool, error) {
	row := q.db.QueryRow(ctx, weaveConceptURIInLists, arg.Uri, arg.Ids)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const weaveCreateConceptList = `-- name: WeaveCreateConceptList :one
INSERT INTO weave_concept_lists (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id,
    list_type, vocabulary_id
) VALUES (
    $1, NOW(), NOW(), $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id, is_closed
`

type WeaveCreateConceptListParams struct {
	ID           string  `json:"id"`
	SemanticID   *string `json:"semantic_id"`
	SystemName   *string `json:"system_name"`
	UiName       []byte  `json:"ui_name"`
	Description  []byte  `json:"description"`
	Status       string  `json:"status"`
	ProjectID    string  `json:"project_id"`
	ListType     *string `json:"list_type"`
	VocabularyID *string `json:"vocabulary_id"`
}

func (q *Queries) WeaveCreateConceptList(ctx context.Context, arg WeaveCreateConceptListParams) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveCreateConceptList,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.ListType,
		arg.VocabularyID,
	)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
		&i.IsClosed,
	)
	return i, err
}

const weaveCreateConceptListEntry = `-- name: WeaveCreateConceptListEntry :one
INSERT INTO weave_concept_list_entries (
    id, concept_list_id, vocabulary_entry_id, position,
    custom_label, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) RETURNING id, concept_list_id, vocabulary_entry_id, position, custom_label, created_at, updated_at
`

type WeaveCreateConceptListEntryParams struct {
	ID                string `json:"id"`
	ConceptListID     string `json:"concept_list_id"`
	VocabularyEntryID string `json:"vocabulary_entry_id"`
	Position          int32  `json:"position"`
	CustomLabel       []byte `json:"custom_label"`
}

func (q *Queries) WeaveCreateConceptListEntry(ctx context.Context, arg WeaveCreateConceptListEntryParams) (WeaveConceptListEntry, error) {
	row := q.db.QueryRow(ctx, weaveCreateConceptListEntry,
		arg.ID,
		arg.ConceptListID,
		arg.VocabularyEntryID,
		arg.Position,
		arg.CustomLabel,
	)
	var i WeaveConceptListEntry
	err := row.Scan(
		&i.ID,
		&i.ConceptListID,
		&i.VocabularyEntryID,
		&i.Position,
		&i.CustomLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveCreateVocabulary = `-- name: WeaveCreateVocabulary :one
INSERT INTO weave_vocabularies (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id,
    connector_type, base_uri, config
) VALUES (
    $1, NOW(), NOW(), $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted, deprecated
`

type WeaveCreateVocabularyParams struct {
	ID            string  `json:"id"`
	SemanticID    *string `json:"semantic_id"`
	SystemName    *string `json:"system_name"`
	UiName        []byte  `json:"ui_name"`
	Description   []byte  `json:"description"`
	Status        string  `json:"status"`
	ProjectID     string  `json:"project_id"`
	ConnectorType string  `json:"connector_type"`
	BaseUri       *string `json:"base_uri"`
	Config        []byte  `json:"config"`
}

func (q *Queries) WeaveCreateVocabulary(ctx context.Context, arg WeaveCreateVocabularyParams) (WeaveVocabulary, error) {
	row := q.db.QueryRow(ctx, weaveCreateVocabulary,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.ConnectorType,
		arg.BaseUri,
		arg.Config,
	)
	var i WeaveVocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ConnectorType,
		&i.BaseUri,
		&i.Config,
		&i.ConfigEncrypted,
		&i.Deprecated,
	)
	return i, err
}

const weaveCreateVocabularyEntry = `-- name: WeaveCreateVocabularyEntry :one
INSERT INTO weave_vocabulary_entries (
    id, vocabulary_id, uri, label, scope_note,
    broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
) RETURNING id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
`

type WeaveCreateVocabularyEntryParams struct {
	ID               string          `json:"id"`
	VocabularyID     string          `json:"vocabulary_id"`
	Uri              string          `json:"uri"`
	Label            json.RawMessage `json:"label"`
	ScopeNote        []byte          `json:"scope_note"`
	BroaderUri       *string         `json:"broader_uri"`
	BroaderPath      json.RawMessage `json:"broader_path"`
	BroaderPathItems json.RawMessage `json:"broader_path_items"`
	ExternalID       *string         `json:"external_id"`
}

func (q *Queries) WeaveCreateVocabularyEntry(ctx context.Context, arg WeaveCreateVocabularyEntryParams) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveCreateVocabularyEntry,
		arg.ID,
		arg.VocabularyID,
		arg.Uri,
		arg.Label,
		arg.ScopeNote,
		arg.BroaderUri,
		arg.BroaderPath,
		arg.BroaderPathItems,
		arg.ExternalID,
	)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveDeleteConceptList = `-- name: WeaveDeleteConceptList :exec
DELETE FROM weave_concept_lists
WHERE project_id = $1
  AND (id = $2 OR semantic_id = $2)
`

type WeaveDeleteConceptListParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

// Delete a concept list by id or semantic id.  (was DeleteConceptList)
func (q *Queries) WeaveDeleteConceptList(ctx context.Context, arg WeaveDeleteConceptListParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteConceptList, arg.ProjectID, arg.ID)
	return err
}

const weaveDeleteConceptListEntry = `-- name: WeaveDeleteConceptListEntry :exec
DELETE FROM weave_concept_list_entries WHERE id = $1
`

func (q *Queries) WeaveDeleteConceptListEntry(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteConceptListEntry, id)
	return err
}

const weaveDeleteConceptListEntryInList = `-- name: WeaveDeleteConceptListEntryInList :exec
DELETE FROM weave_concept_list_entries
WHERE id = $1 AND concept_list_id = $2
`

type WeaveDeleteConceptListEntryInListParams struct {
	ID            string `json:"id"`
	ConceptListID string `json:"concept_list_id"`
}

// Remove one entry from a list.  (was RemoveConceptListEntry)
func (q *Queries) WeaveDeleteConceptListEntryInList(ctx context.Context, arg WeaveDeleteConceptListEntryInListParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteConceptListEntryInList, arg.ID, arg.ConceptListID)
	return err
}

const weaveDeprecateProjectVocabulary = `-- name: WeaveDeprecateProjectVocabulary :one
UPDATE weave_vocabularies
SET deprecated = true, updated_at = NOW()
WHERE id = $1::text AND project_id = $2::text
  -- The project's local-terms row is not removable. It is the fallback for
  -- terms no thesaurus has, every project needs one, and a concept list with
  -- no source vocabulary resolves against it — retiring it would leave a
  -- curator unable to add a term anywhere. Enforced here rather than only in
  -- the UI, so the endpoint cannot be asked to do it directly.
  AND connector_type <> 'local'
RETURNING id
`

type WeaveDeprecateProjectVocabularyParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

// Removing a vocabulary deprecates its row rather than deleting it.
//
// A delete cannot express what removal means here. weave_vocabulary_entries
// cascades from weave_vocabularies, so deleting takes every pinned entry with
// it and empties the concept lists built on them; and weave_concept_lists has
// a plain foreign key with no ON DELETE action, so Postgres refuses the delete
// outright while any list still points at the row. Removal has to leave the
// row in place: the lists keep their entries and keep resolving them, and the
// vocabulary simply stops being offered for anything new.
func (q *Queries) WeaveDeprecateProjectVocabulary(ctx context.Context, arg WeaveDeprecateProjectVocabularyParams) (string, error) {
	row := q.db.QueryRow(ctx, weaveDeprecateProjectVocabulary, arg.ID, arg.ProjectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const weaveFindConceptListEntryByVocabEntry = `-- name: WeaveFindConceptListEntryByVocabEntry :one
SELECT id
FROM weave_concept_list_entries
WHERE concept_list_id = $1 AND vocabulary_entry_id = $2
LIMIT 1
`

type WeaveFindConceptListEntryByVocabEntryParams struct {
	ConceptListID     string `json:"concept_list_id"`
	VocabularyEntryID string `json:"vocabulary_entry_id"`
}

// Find an existing entry so adding the same term twice is idempotent.  (was AddConceptListEntry)
func (q *Queries) WeaveFindConceptListEntryByVocabEntry(ctx context.Context, arg WeaveFindConceptListEntryByVocabEntryParams) (string, error) {
	row := q.db.QueryRow(ctx, weaveFindConceptListEntryByVocabEntry, arg.ConceptListID, arg.VocabularyEntryID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const weaveFindConceptListsByListType = `-- name: WeaveFindConceptListsByListType :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id, is_closed FROM weave_concept_lists
WHERE list_type = $1
ORDER BY system_name ASC
`

func (q *Queries) WeaveFindConceptListsByListType(ctx context.Context, listType *string) ([]WeaveConceptList, error) {
	rows, err := q.db.Query(ctx, weaveFindConceptListsByListType, listType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveConceptList{}
	for rows.Next() {
		var i WeaveConceptList
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ListType,
			&i.VocabularyID,
			&i.IsClosed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveFindLocalVocabulary = `-- name: WeaveFindLocalVocabulary :one
SELECT id FROM weave_vocabularies
WHERE project_id = $1 AND connector_type = 'local'
ORDER BY created_at LIMIT 1
`

// The project's local vocabulary, if it already has one.  (was ensureLocalVocabulary)
func (q *Queries) WeaveFindLocalVocabulary(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRow(ctx, weaveFindLocalVocabulary, projectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const weaveFindVocabularyForURI = `-- name: WeaveFindVocabularyForURI :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted, deprecated FROM weave_vocabularies
WHERE base_uri IS NOT NULL
  AND base_uri <> ''
  AND $1::text LIKE base_uri || '%'
ORDER BY LENGTH(base_uri) DESC
LIMIT 1
`

func (q *Queries) WeaveFindVocabularyForURI(ctx context.Context, uri string) (WeaveVocabulary, error) {
	row := q.db.QueryRow(ctx, weaveFindVocabularyForURI, uri)
	var i WeaveVocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ConnectorType,
		&i.BaseUri,
		&i.Config,
		&i.ConfigEncrypted,
		&i.Deprecated,
	)
	return i, err
}

const weaveGetConceptList = `-- name: WeaveGetConceptList :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id, is_closed FROM weave_concept_lists WHERE id = $1
`

func (q *Queries) WeaveGetConceptList(ctx context.Context, id string) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveGetConceptList, id)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
		&i.IsClosed,
	)
	return i, err
}

const weaveGetConceptListByIDOrSemanticID = `-- name: WeaveGetConceptListByIDOrSemanticID :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id, is_closed FROM weave_concept_lists
WHERE id = $1::text
   OR semantic_id = $1::text
LIMIT 1
`

func (q *Queries) WeaveGetConceptListByIDOrSemanticID(ctx context.Context, id string) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveGetConceptListByIDOrSemanticID, id)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
		&i.IsClosed,
	)
	return i, err
}

const weaveGetConceptListNamesByIDs = `-- name: WeaveGetConceptListNamesByIDs :many
SELECT id, semantic_id, ui_name, project_id, is_closed
FROM weave_concept_lists
WHERE id = ANY($1::text[])
   OR semantic_id = ANY($1::text[])
`

type WeaveGetConceptListNamesByIDsRow struct {
	ID         string  `json:"id"`
	SemanticID *string `json:"semantic_id"`
	UiName     []byte  `json:"ui_name"`
	ProjectID  string  `json:"project_id"`
	IsClosed   bool    `json:"is_closed"`
}

func (q *Queries) WeaveGetConceptListNamesByIDs(ctx context.Context, ids []string) ([]WeaveGetConceptListNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, weaveGetConceptListNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveGetConceptListNamesByIDsRow{}
	for rows.Next() {
		var i WeaveGetConceptListNamesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SemanticID,
			&i.UiName,
			&i.ProjectID,
			&i.IsClosed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveGetProjectConceptList = `-- name: WeaveGetProjectConceptList :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id, is_closed FROM weave_concept_lists
WHERE project_id = $1::text
  AND (id = $2::text OR semantic_id = $2::text)
`

type WeaveGetProjectConceptListParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) WeaveGetProjectConceptList(ctx context.Context, arg WeaveGetProjectConceptListParams) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveGetProjectConceptList, arg.ProjectID, arg.ID)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
		&i.IsClosed,
	)
	return i, err
}

const weaveGetProjectConceptListArchive = `-- name: WeaveGetProjectConceptListArchive :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id, version_number, is_closed FROM weave_concept_lists_archive
WHERE project_id = $1::text
  AND (id = $2::text OR semantic_id = $2::text)
  AND version_number = $3::text
`

type WeaveGetProjectConceptListArchiveParams struct {
	ProjectID     string `json:"project_id"`
	ID            string `json:"id"`
	VersionNumber string `json:"version_number"`
}

func (q *Queries) WeaveGetProjectConceptListArchive(ctx context.Context, arg WeaveGetProjectConceptListArchiveParams) (WeaveConceptListsArchive, error) {
	row := q.db.QueryRow(ctx, weaveGetProjectConceptListArchive, arg.ProjectID, arg.ID, arg.VersionNumber)
	var i WeaveConceptListsArchive
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
		&i.VersionNumber,
		&i.IsClosed,
	)
	return i, err
}

const weaveGetVocabulary = `-- name: WeaveGetVocabulary :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted, deprecated FROM weave_vocabularies WHERE id = $1
`

func (q *Queries) WeaveGetVocabulary(ctx context.Context, id string) (WeaveVocabulary, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabulary, id)
	var i WeaveVocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ConnectorType,
		&i.BaseUri,
		&i.Config,
		&i.ConfigEncrypted,
		&i.Deprecated,
	)
	return i, err
}

const weaveGetVocabularyEntry = `-- name: WeaveGetVocabularyEntry :one
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries WHERE id = $1
`

func (q *Queries) WeaveGetVocabularyEntry(ctx context.Context, id string) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabularyEntry, id)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveGetVocabularyEntryByURI = `-- name: WeaveGetVocabularyEntryByURI :one
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries
WHERE uri = $1::text
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) WeaveGetVocabularyEntryByURI(ctx context.Context, uri string) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabularyEntryByURI, uri)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveGetVocabularyEntryByVocabularyURI = `-- name: WeaveGetVocabularyEntryByVocabularyURI :one
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries
WHERE vocabulary_id = $1::text
  AND uri = $2::text
LIMIT 1
`

type WeaveGetVocabularyEntryByVocabularyURIParams struct {
	VocabularyID string `json:"vocabulary_id"`
	Uri          string `json:"uri"`
}

func (q *Queries) WeaveGetVocabularyEntryByVocabularyURI(ctx context.Context, arg WeaveGetVocabularyEntryByVocabularyURIParams) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabularyEntryByVocabularyURI, arg.VocabularyID, arg.Uri)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveListAdminVocabularies = `-- name: WeaveListAdminVocabularies :many

SELECT
    v.id,
    COALESCE(v.semantic_id, '') AS semantic_id,
    COALESCE(v.system_name, '') AS system_name,
    COALESCE(v.ui_name, '{}'::jsonb) AS ui_name,
    COALESCE(v.description, '{}'::jsonb) AS description,
    v.status,
    v.project_id,
    v.connector_type,
    COALESCE(v.base_uri, '') AS base_uri,
    v.created_at,
    v.updated_at,
    COUNT(DISTINCT ve.id) AS entry_count,
    COUNT(DISTINCT v.project_id) AS project_count
FROM weave_vocabularies v
LEFT JOIN weave_vocabulary_entries ve ON ve.vocabulary_id = v.id
GROUP BY v.id
ORDER BY v.system_name ASC, v.id ASC
`

type WeaveListAdminVocabulariesRow struct {
	ID            string    `json:"id"`
	SemanticID    string    `json:"semantic_id"`
	SystemName    string    `json:"system_name"`
	UiName        []byte    `json:"ui_name"`
	Description   []byte    `json:"description"`
	Status        string    `json:"status"`
	ProjectID     string    `json:"project_id"`
	ConnectorType string    `json:"connector_type"`
	BaseUri       string    `json:"base_uri"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	EntryCount    int64     `json:"entry_count"`
	ProjectCount  int64     `json:"project_count"`
}

// ===========================================================================
// Queries moved out of pkg/weave/vocabulary/service.go, where they were Go
// string literals. Moved verbatim: a behaviour change hidden inside a
// mechanical move is the hardest kind to find later, so any improvement to
// these is a separate commit with its own test.
// ===========================================================================
// Administrative inventory of every vocabulary with its project and entry count.  (was ListAdminVocabularies)
func (q *Queries) WeaveListAdminVocabularies(ctx context.Context) ([]WeaveListAdminVocabulariesRow, error) {
	rows, err := q.db.Query(ctx, weaveListAdminVocabularies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListAdminVocabulariesRow{}
	for rows.Next() {
		var i WeaveListAdminVocabulariesRow
		if err := rows.Scan(
			&i.ID,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ConnectorType,
			&i.BaseUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCount,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListConceptListEntries = `-- name: WeaveListConceptListEntries :many
SELECT id, concept_list_id, vocabulary_entry_id, position, custom_label, created_at, updated_at FROM weave_concept_list_entries
WHERE concept_list_id = $1
ORDER BY position ASC
`

func (q *Queries) WeaveListConceptListEntries(ctx context.Context, conceptListID string) ([]WeaveConceptListEntry, error) {
	rows, err := q.db.Query(ctx, weaveListConceptListEntries, conceptListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveConceptListEntry{}
	for rows.Next() {
		var i WeaveConceptListEntry
		if err := rows.Scan(
			&i.ID,
			&i.ConceptListID,
			&i.VocabularyEntryID,
			&i.Position,
			&i.CustomLabel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListConceptListEntriesArchiveWithVocabulary = `-- name: WeaveListConceptListEntriesArchiveWithVocabulary :many
SELECT
    cle.id AS concept_list_entry_id,
    cle.concept_list_id,
    cle.vocabulary_entry_id,
    cle.position,
    cle.custom_label,
    cle.created_at AS concept_list_entry_created_at,
    cle.updated_at AS concept_list_entry_updated_at,
    ve.id AS entry_id,
    ve.vocabulary_id,
    ve.uri,
    ve.label,
    ve.scope_note,
    ve.broader_uri,
    ve.broader_path,
    ve.broader_path_items,
    ve.external_id,
    ve.created_at AS entry_created_at,
    ve.updated_at AS entry_updated_at
FROM weave_concept_list_entries_archive cle
JOIN weave_vocabulary_entries ve ON ve.id = cle.vocabulary_entry_id
WHERE cle.concept_list_id = $1::text
  AND cle.version_number = $2::text
ORDER BY cle.position ASC, ve.uri ASC
`

type WeaveListConceptListEntriesArchiveWithVocabularyParams struct {
	ConceptListID string `json:"concept_list_id"`
	VersionNumber string `json:"version_number"`
}

type WeaveListConceptListEntriesArchiveWithVocabularyRow struct {
	ConceptListEntryID        string          `json:"concept_list_entry_id"`
	ConceptListID             string          `json:"concept_list_id"`
	VocabularyEntryID         string          `json:"vocabulary_entry_id"`
	Position                  int32           `json:"position"`
	CustomLabel               []byte          `json:"custom_label"`
	ConceptListEntryCreatedAt time.Time       `json:"concept_list_entry_created_at"`
	ConceptListEntryUpdatedAt time.Time       `json:"concept_list_entry_updated_at"`
	EntryID                   string          `json:"entry_id"`
	VocabularyID              string          `json:"vocabulary_id"`
	Uri                       string          `json:"uri"`
	Label                     json.RawMessage `json:"label"`
	ScopeNote                 []byte          `json:"scope_note"`
	BroaderUri                *string         `json:"broader_uri"`
	BroaderPath               json.RawMessage `json:"broader_path"`
	BroaderPathItems          json.RawMessage `json:"broader_path_items"`
	ExternalID                *string         `json:"external_id"`
	EntryCreatedAt            time.Time       `json:"entry_created_at"`
	EntryUpdatedAt            time.Time       `json:"entry_updated_at"`
}

func (q *Queries) WeaveListConceptListEntriesArchiveWithVocabulary(ctx context.Context, arg WeaveListConceptListEntriesArchiveWithVocabularyParams) ([]WeaveListConceptListEntriesArchiveWithVocabularyRow, error) {
	rows, err := q.db.Query(ctx, weaveListConceptListEntriesArchiveWithVocabulary, arg.ConceptListID, arg.VersionNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListConceptListEntriesArchiveWithVocabularyRow{}
	for rows.Next() {
		var i WeaveListConceptListEntriesArchiveWithVocabularyRow
		if err := rows.Scan(
			&i.ConceptListEntryID,
			&i.ConceptListID,
			&i.VocabularyEntryID,
			&i.Position,
			&i.CustomLabel,
			&i.ConceptListEntryCreatedAt,
			&i.ConceptListEntryUpdatedAt,
			&i.EntryID,
			&i.VocabularyID,
			&i.Uri,
			&i.Label,
			&i.ScopeNote,
			&i.BroaderUri,
			&i.BroaderPath,
			&i.BroaderPathItems,
			&i.ExternalID,
			&i.EntryCreatedAt,
			&i.EntryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListConceptListEntriesWithVocabulary = `-- name: WeaveListConceptListEntriesWithVocabulary :many
SELECT
    cle.id AS concept_list_entry_id,
    cle.concept_list_id,
    cle.vocabulary_entry_id,
    cle.position,
    cle.custom_label,
    cle.created_at AS concept_list_entry_created_at,
    cle.updated_at AS concept_list_entry_updated_at,
    ve.id AS entry_id,
    ve.vocabulary_id,
    ve.uri,
    ve.label,
    ve.scope_note,
    ve.broader_uri,
    ve.broader_path,
    ve.broader_path_items,
    ve.external_id,
    ve.created_at AS entry_created_at,
    ve.updated_at AS entry_updated_at
FROM weave_concept_list_entries cle
JOIN weave_vocabulary_entries ve ON ve.id = cle.vocabulary_entry_id
WHERE cle.concept_list_id = $1::text
ORDER BY cle.position ASC, ve.uri ASC
`

type WeaveListConceptListEntriesWithVocabularyRow struct {
	ConceptListEntryID        string          `json:"concept_list_entry_id"`
	ConceptListID             string          `json:"concept_list_id"`
	VocabularyEntryID         string          `json:"vocabulary_entry_id"`
	Position                  int32           `json:"position"`
	CustomLabel               []byte          `json:"custom_label"`
	ConceptListEntryCreatedAt time.Time       `json:"concept_list_entry_created_at"`
	ConceptListEntryUpdatedAt time.Time       `json:"concept_list_entry_updated_at"`
	EntryID                   string          `json:"entry_id"`
	VocabularyID              string          `json:"vocabulary_id"`
	Uri                       string          `json:"uri"`
	Label                     json.RawMessage `json:"label"`
	ScopeNote                 []byte          `json:"scope_note"`
	BroaderUri                *string         `json:"broader_uri"`
	BroaderPath               json.RawMessage `json:"broader_path"`
	BroaderPathItems          json.RawMessage `json:"broader_path_items"`
	ExternalID                *string         `json:"external_id"`
	EntryCreatedAt            time.Time       `json:"entry_created_at"`
	EntryUpdatedAt            time.Time       `json:"entry_updated_at"`
}

func (q *Queries) WeaveListConceptListEntriesWithVocabulary(ctx context.Context, conceptListID string) ([]WeaveListConceptListEntriesWithVocabularyRow, error) {
	rows, err := q.db.Query(ctx, weaveListConceptListEntriesWithVocabulary, conceptListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListConceptListEntriesWithVocabularyRow{}
	for rows.Next() {
		var i WeaveListConceptListEntriesWithVocabularyRow
		if err := rows.Scan(
			&i.ConceptListEntryID,
			&i.ConceptListID,
			&i.VocabularyEntryID,
			&i.Position,
			&i.CustomLabel,
			&i.ConceptListEntryCreatedAt,
			&i.ConceptListEntryUpdatedAt,
			&i.EntryID,
			&i.VocabularyID,
			&i.Uri,
			&i.Label,
			&i.ScopeNote,
			&i.BroaderUri,
			&i.BroaderPath,
			&i.BroaderPathItems,
			&i.ExternalID,
			&i.EntryCreatedAt,
			&i.EntryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListConceptListMemberURIs = `-- name: WeaveListConceptListMemberURIs :many
SELECT DISTINCT ve.uri
FROM weave_concept_lists cl
JOIN weave_concept_list_entries cle ON cle.concept_list_id = cl.id
JOIN weave_vocabulary_entries ve ON ve.id = cle.vocabulary_entry_id
WHERE (cl.id = ANY($1::text[]) OR cl.semantic_id = ANY($1::text[]))
ORDER BY ve.uri
`

// Distinct member concept URIs across the given concept lists (by id or
// semantic_id). Used to emit sealed-list value enums in generators (#3599).
func (q *Queries) WeaveListConceptListMemberURIs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveListConceptListMemberURIs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var uri string
		if err := rows.Scan(&uri); err != nil {
			return nil, err
		}
		items = append(items, uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListConceptLists = `-- name: WeaveListConceptLists :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id, is_closed FROM weave_concept_lists
WHERE project_id = $1
ORDER BY system_name ASC
`

func (q *Queries) WeaveListConceptLists(ctx context.Context, projectID string) ([]WeaveConceptList, error) {
	rows, err := q.db.Query(ctx, weaveListConceptLists, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveConceptList{}
	for rows.Next() {
		var i WeaveConceptList
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ListType,
			&i.VocabularyID,
			&i.IsClosed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListProjectScopedVocabularies = `-- name: WeaveListProjectScopedVocabularies :many
SELECT v.id, v.created_at, v.updated_at, v.semantic_id, v.system_name, v.ui_name, v.description, v.status, v.project_id, v.connector_type, v.base_uri, v.config, v.config_encrypted, v.deprecated
FROM weave_vocabularies v
WHERE v.project_id = $1::text
ORDER BY v.system_name ASC, v.id ASC
`

// A project's vocabularies are exactly the rows carrying its project_id.
// There is no global tier and no join table: see
// docs/plans/2026-09-26-vocabulary-project-ownership-design.md.
func (q *Queries) WeaveListProjectScopedVocabularies(ctx context.Context, projectID string) ([]WeaveVocabulary, error) {
	rows, err := q.db.Query(ctx, weaveListProjectScopedVocabularies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveVocabulary{}
	for rows.Next() {
		var i WeaveVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ConnectorType,
			&i.BaseUri,
			&i.Config,
			&i.ConfigEncrypted,
			&i.Deprecated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListVocabularies = `-- name: WeaveListVocabularies :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted, deprecated FROM weave_vocabularies
ORDER BY system_name ASC
`

func (q *Queries) WeaveListVocabularies(ctx context.Context) ([]WeaveVocabulary, error) {
	rows, err := q.db.Query(ctx, weaveListVocabularies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveVocabulary{}
	for rows.Next() {
		var i WeaveVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ConnectorType,
			&i.BaseUri,
			&i.Config,
			&i.ConfigEncrypted,
			&i.Deprecated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListVocabularySettingsOptions = `-- name: WeaveListVocabularySettingsOptions :many
SELECT
    v.id,
    COALESCE(v.system_name, '') AS system_name,
    COALESCE(v.ui_name, '{}'::jsonb) AS ui_name,
    COALESCE(v.description, '{}'::jsonb) AS description,
    v.status,
    v.deprecated,
    v.connector_type,
    COALESCE(v.base_uri, '') AS base_uri
FROM weave_vocabularies v
WHERE v.project_id = $1::text
ORDER BY v.system_name ASC, v.id ASC
`

type WeaveListVocabularySettingsOptionsRow struct {
	ID            string `json:"id"`
	SystemName    string `json:"system_name"`
	UiName        []byte `json:"ui_name"`
	Description   []byte `json:"description"`
	Status        string `json:"status"`
	Deprecated    bool   `json:"deprecated"`
	ConnectorType string `json:"connector_type"`
	BaseUri       string `json:"base_uri"`
}

// The vocabularies a project has, for the settings screen. Every row is
// owned by the project; "selected" is no longer a concept, because having
// the row IS the enablement.
func (q *Queries) WeaveListVocabularySettingsOptions(ctx context.Context, projectID string) ([]WeaveListVocabularySettingsOptionsRow, error) {
	rows, err := q.db.Query(ctx, weaveListVocabularySettingsOptions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListVocabularySettingsOptionsRow{}
	for rows.Next() {
		var i WeaveListVocabularySettingsOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.Deprecated,
			&i.ConnectorType,
			&i.BaseUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveMaxConceptListNumber = `-- name: WeaveMaxConceptListNumber :one
SELECT COALESCE(MAX((regexp_match(id, '^' || $1 || '\.CL\.([0-9]+)$'))[1]::bigint), 0)
FROM weave_concept_lists
WHERE project_id = $1
  AND id ~ ('^' || $1 || '\.CL\.[0-9]+$')
`

// Scoped to the list as well as the entry id. The existing WeaveSetConceptListEntryPosition is not:
// a wrong id there can touch an entry in another list. That looser form has
// one legacy caller and is left alone here rather than changed underneath it.
// Highest existing CL number for a project, scanned from the id.  (was nextConceptListID)
func (q *Queries) WeaveMaxConceptListNumber(ctx context.Context, dollar_1 *string) (interface{}, error) {
	row := q.db.QueryRow(ctx, weaveMaxConceptListNumber, dollar_1)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const weaveNextConceptListEntryPosition = `-- name: WeaveNextConceptListEntryPosition :one
SELECT COALESCE(MAX(position), 0) + 1
FROM weave_concept_list_entries
WHERE concept_list_id = $1
`

// The next position in a list; MAX(position)+1.  (was AddConceptListEntry)
func (q *Queries) WeaveNextConceptListEntryPosition(ctx context.Context, conceptListID string) (int32, error) {
	row := q.db.QueryRow(ctx, weaveNextConceptListEntryPosition, conceptListID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveNextLocalTermPosition = `-- name: WeaveNextLocalTermPosition :one
SELECT COALESCE(MAX(position), 0) + 1 FROM weave_concept_list_entries WHERE concept_list_id = $1
`

// The next position when appending a locally created term.  (was CreateLocalTerm)
func (q *Queries) WeaveNextLocalTermPosition(ctx context.Context, conceptListID string) (int32, error) {
	row := q.db.QueryRow(ctx, weaveNextLocalTermPosition, conceptListID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveReserveConceptListCounter = `-- name: WeaveReserveConceptListCounter :exec
INSERT INTO weave_entity_counters (project_id, kind, next_n)
VALUES ($1, 'concept_list', $2)
ON CONFLICT (project_id, kind)
DO UPDATE SET
    next_n = GREATEST(weave_entity_counters.next_n, EXCLUDED.next_n),
    updated_at = NOW()
`

type WeaveReserveConceptListCounterParams struct {
	ProjectID string `json:"project_id"`
	NextN     int64  `json:"next_n"`
}

// Advance and return the project's concept-list counter.  (was nextConceptListID)
func (q *Queries) WeaveReserveConceptListCounter(ctx context.Context, arg WeaveReserveConceptListCounterParams) error {
	_, err := q.db.Exec(ctx, weaveReserveConceptListCounter, arg.ProjectID, arg.NextN)
	return err
}

const weaveSearchConceptListEntries = `-- name: WeaveSearchConceptListEntries :many
SELECT
    cle.id AS concept_list_entry_id,
    cle.concept_list_id,
    cle.vocabulary_entry_id,
    cle.position,
    cle.custom_label,
    cle.created_at AS concept_list_entry_created_at,
    cle.updated_at AS concept_list_entry_updated_at,
    ve.id AS entry_id,
    ve.vocabulary_id,
    ve.uri,
    ve.label,
    ve.scope_note,
    ve.broader_uri,
    ve.broader_path,
    ve.broader_path_items,
    ve.external_id,
    ve.created_at AS entry_created_at,
    ve.updated_at AS entry_updated_at
FROM weave_concept_list_entries cle
JOIN weave_vocabulary_entries ve ON ve.id = cle.vocabulary_entry_id
WHERE cle.concept_list_id = $1::text
  AND (
    EXISTS (SELECT 1 FROM jsonb_each_text(ve.label) WHERE value ILIKE '%' || $2::text || '%')
    OR ve.uri ILIKE '%' || $2::text || '%'
    OR ve.external_id ILIKE '%' || $2::text || '%'
  )
ORDER BY cle.position ASC, ve.uri ASC
LIMIT $3::integer
`

type WeaveSearchConceptListEntriesParams struct {
	ConceptListID string `json:"concept_list_id"`
	Query         string `json:"query"`
	ResultLimit   int32  `json:"result_limit"`
}

type WeaveSearchConceptListEntriesRow struct {
	ConceptListEntryID        string          `json:"concept_list_entry_id"`
	ConceptListID             string          `json:"concept_list_id"`
	VocabularyEntryID         string          `json:"vocabulary_entry_id"`
	Position                  int32           `json:"position"`
	CustomLabel               []byte          `json:"custom_label"`
	ConceptListEntryCreatedAt time.Time       `json:"concept_list_entry_created_at"`
	ConceptListEntryUpdatedAt time.Time       `json:"concept_list_entry_updated_at"`
	EntryID                   string          `json:"entry_id"`
	VocabularyID              string          `json:"vocabulary_id"`
	Uri                       string          `json:"uri"`
	Label                     json.RawMessage `json:"label"`
	ScopeNote                 []byte          `json:"scope_note"`
	BroaderUri                *string         `json:"broader_uri"`
	BroaderPath               json.RawMessage `json:"broader_path"`
	BroaderPathItems          json.RawMessage `json:"broader_path_items"`
	ExternalID                *string         `json:"external_id"`
	EntryCreatedAt            time.Time       `json:"entry_created_at"`
	EntryUpdatedAt            time.Time       `json:"entry_updated_at"`
}

func (q *Queries) WeaveSearchConceptListEntries(ctx context.Context, arg WeaveSearchConceptListEntriesParams) ([]WeaveSearchConceptListEntriesRow, error) {
	rows, err := q.db.Query(ctx, weaveSearchConceptListEntries, arg.ConceptListID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveSearchConceptListEntriesRow{}
	for rows.Next() {
		var i WeaveSearchConceptListEntriesRow
		if err := rows.Scan(
			&i.ConceptListEntryID,
			&i.ConceptListID,
			&i.VocabularyEntryID,
			&i.Position,
			&i.CustomLabel,
			&i.ConceptListEntryCreatedAt,
			&i.ConceptListEntryUpdatedAt,
			&i.EntryID,
			&i.VocabularyID,
			&i.Uri,
			&i.Label,
			&i.ScopeNote,
			&i.BroaderUri,
			&i.BroaderPath,
			&i.BroaderPathItems,
			&i.ExternalID,
			&i.EntryCreatedAt,
			&i.EntryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSearchVocabularyEntries = `-- name: WeaveSearchVocabularyEntries :many
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries
WHERE vocabulary_id = $1::text
  AND (
    EXISTS (SELECT 1 FROM jsonb_each_text(label) WHERE value ILIKE '%' || $2::text || '%')
    OR uri ILIKE '%' || $2::text || '%'
    OR external_id ILIKE '%' || $2::text || '%'
  )
ORDER BY uri ASC
LIMIT 50
`

type WeaveSearchVocabularyEntriesParams struct {
	VocabularyID string `json:"vocabulary_id"`
	Query        string `json:"query"`
}

func (q *Queries) WeaveSearchVocabularyEntries(ctx context.Context, arg WeaveSearchVocabularyEntriesParams) ([]WeaveVocabularyEntry, error) {
	rows, err := q.db.Query(ctx, weaveSearchVocabularyEntries, arg.VocabularyID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveVocabularyEntry{}
	for rows.Next() {
		var i WeaveVocabularyEntry
		if err := rows.Scan(
			&i.ID,
			&i.VocabularyID,
			&i.Uri,
			&i.Label,
			&i.ScopeNote,
			&i.BroaderUri,
			&i.BroaderPath,
			&i.BroaderPathItems,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSetConceptListClosed = `-- name: WeaveSetConceptListClosed :exec
UPDATE weave_concept_lists SET is_closed = $2, updated_at = NOW() WHERE id = $1
`

type WeaveSetConceptListClosedParams struct {
	ID       string `json:"id"`
	IsClosed bool   `json:"is_closed"`
}

func (q *Queries) WeaveSetConceptListClosed(ctx context.Context, arg WeaveSetConceptListClosedParams) error {
	_, err := q.db.Exec(ctx, weaveSetConceptListClosed, arg.ID, arg.IsClosed)
	return err
}

const weaveSetConceptListEntryPositionInList = `-- name: WeaveSetConceptListEntryPositionInList :exec
UPDATE weave_concept_list_entries
SET position = $1,
    updated_at = NOW()
WHERE id = $2
  AND concept_list_id = $3
`

type WeaveSetConceptListEntryPositionInListParams struct {
	Position      int32  `json:"position"`
	ID            string `json:"id"`
	ConceptListID string `json:"concept_list_id"`
}

// Set one entry's position; the reorder loop calls it per id.  (was ReorderConceptListEntries)
func (q *Queries) WeaveSetConceptListEntryPositionInList(ctx context.Context, arg WeaveSetConceptListEntryPositionInListParams) error {
	_, err := q.db.Exec(ctx, weaveSetConceptListEntryPositionInList, arg.Position, arg.ID, arg.ConceptListID)
	return err
}

const weaveUpdateConceptList = `-- name: WeaveUpdateConceptList :exec
UPDATE weave_concept_lists
SET system_name = $3,
    ui_name = $4::jsonb,
    description = $5::jsonb,
    status = $6,
    vocabulary_id = $7,
    list_type = $8,
    updated_at = NOW()
WHERE project_id = $1
  AND (id = $2 OR semantic_id = $2)
`

type WeaveUpdateConceptListParams struct {
	ProjectID    string          `json:"project_id"`
	ID           string          `json:"id"`
	SystemName   *string         `json:"system_name"`
	Column4      json.RawMessage `json:"column_4"`
	Column5      json.RawMessage `json:"column_5"`
	Status       string          `json:"status"`
	VocabularyID *string         `json:"vocabulary_id"`
	ListType     *string         `json:"list_type"`
}

// Update a concept list's editable fields.  (was UpdateConceptList)
func (q *Queries) WeaveUpdateConceptList(ctx context.Context, arg WeaveUpdateConceptListParams) error {
	_, err := q.db.Exec(ctx, weaveUpdateConceptList,
		arg.ProjectID,
		arg.ID,
		arg.SystemName,
		arg.Column4,
		arg.Column5,
		arg.Status,
		arg.VocabularyID,
		arg.ListType,
	)
	return err
}

const weaveUpdateConceptListEntryLabel = `-- name: WeaveUpdateConceptListEntryLabel :exec
UPDATE weave_concept_list_entries
SET custom_label = $1::jsonb,
    updated_at = NOW()
WHERE id = $2
  AND concept_list_id = $3
`

type WeaveUpdateConceptListEntryLabelParams struct {
	Column1       json.RawMessage `json:"column_1"`
	ID            string          `json:"id"`
	ConceptListID string          `json:"concept_list_id"`
}

// Scoped to the list as well as the entry id. The existing WeaveDeleteConceptListEntry is not:
// a wrong id there can touch an entry in another list. That looser form has
// one legacy caller and is left alone here rather than changed underneath it.
// Set an entry's custom label.  (was UpdateConceptListEntry)
func (q *Queries) WeaveUpdateConceptListEntryLabel(ctx context.Context, arg WeaveUpdateConceptListEntryLabelParams) error {
	_, err := q.db.Exec(ctx, weaveUpdateConceptListEntryLabel, arg.Column1, arg.ID, arg.ConceptListID)
	return err
}

const weaveUpdateConceptListEntryOrder = `-- name: WeaveUpdateConceptListEntryOrder :exec
UPDATE weave_concept_list_entries
SET position = $2, updated_at = NOW()
WHERE id = $1
`

type WeaveUpdateConceptListEntryOrderParams struct {
	ID       string `json:"id"`
	Position int32  `json:"position"`
}

func (q *Queries) WeaveUpdateConceptListEntryOrder(ctx context.Context, arg WeaveUpdateConceptListEntryOrderParams) error {
	_, err := q.db.Exec(ctx, weaveUpdateConceptListEntryOrder, arg.ID, arg.Position)
	return err
}

const weaveUpsertVocabularyEntry = `-- name: WeaveUpsertVocabularyEntry :one
INSERT INTO weave_vocabulary_entries (
    id, vocabulary_id, uri, label, scope_note,
    broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
) VALUES (
    $1::text, $2::text, $3::text, $4::jsonb, $5::jsonb,
    $6::text, $7::jsonb, $8::jsonb, $9::text, NOW(), NOW()
)
ON CONFLICT (vocabulary_id, uri) DO UPDATE SET
    label = EXCLUDED.label,
    scope_note = EXCLUDED.scope_note,
    broader_uri = EXCLUDED.broader_uri,
    broader_path = EXCLUDED.broader_path,
    broader_path_items = EXCLUDED.broader_path_items,
    external_id = EXCLUDED.external_id,
    updated_at = NOW()
RETURNING id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
`

type WeaveUpsertVocabularyEntryParams struct {
	ID               string          `json:"id"`
	VocabularyID     string          `json:"vocabulary_id"`
	Uri              string          `json:"uri"`
	Label            json.RawMessage `json:"label"`
	ScopeNote        json.RawMessage `json:"scope_note"`
	BroaderUri       string          `json:"broader_uri"`
	BroaderPath      json.RawMessage `json:"broader_path"`
	BroaderPathItems json.RawMessage `json:"broader_path_items"`
	ExternalID       string          `json:"external_id"`
}

func (q *Queries) WeaveUpsertVocabularyEntry(ctx context.Context, arg WeaveUpsertVocabularyEntryParams) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveUpsertVocabularyEntry,
		arg.ID,
		arg.VocabularyID,
		arg.Uri,
		arg.Label,
		arg.ScopeNote,
		arg.BroaderUri,
		arg.BroaderPath,
		arg.BroaderPathItems,
		arg.ExternalID,
	)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
