// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_collection_placements.sql

package sqlcgen

import (
	"context"
)

const weaveDeleteCollectionPlacement = `-- name: WeaveDeleteCollectionPlacement :exec
DELETE FROM weave_collection_placements
WHERE model_id = $1 AND category_id = $2 AND collection_id = $3
`

type WeaveDeleteCollectionPlacementParams struct {
	ModelID      string `json:"model_id"`
	CategoryID   string `json:"category_id"`
	CollectionID string `json:"collection_id"`
}

func (q *Queries) WeaveDeleteCollectionPlacement(ctx context.Context, arg WeaveDeleteCollectionPlacementParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteCollectionPlacement, arg.ModelID, arg.CategoryID, arg.CollectionID)
	return err
}

const weaveDeleteCollectionPlacementsByModel = `-- name: WeaveDeleteCollectionPlacementsByModel :exec
DELETE FROM weave_collection_placements
WHERE model_id = $1
`

func (q *Queries) WeaveDeleteCollectionPlacementsByModel(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, weaveDeleteCollectionPlacementsByModel, modelID)
	return err
}

const weaveGetCollectionPlacement = `-- name: WeaveGetCollectionPlacement :one
SELECT id, project_id, model_id, category_id, collection_id, is_required, min_occurs, max_occurs, is_hidden, created_at, updated_at FROM weave_collection_placements
WHERE model_id = $1 AND category_id = $2 AND collection_id = $3
`

type WeaveGetCollectionPlacementParams struct {
	ModelID      string `json:"model_id"`
	CategoryID   string `json:"category_id"`
	CollectionID string `json:"collection_id"`
}

func (q *Queries) WeaveGetCollectionPlacement(ctx context.Context, arg WeaveGetCollectionPlacementParams) (WeaveCollectionPlacement, error) {
	row := q.db.QueryRow(ctx, weaveGetCollectionPlacement, arg.ModelID, arg.CategoryID, arg.CollectionID)
	var i WeaveCollectionPlacement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ModelID,
		&i.CategoryID,
		&i.CollectionID,
		&i.IsRequired,
		&i.MinOccurs,
		&i.MaxOccurs,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveListCollectionPlacementsByModel = `-- name: WeaveListCollectionPlacementsByModel :many
SELECT id, project_id, model_id, category_id, collection_id, is_required, min_occurs, max_occurs, is_hidden, created_at, updated_at FROM weave_collection_placements
WHERE model_id = $1
ORDER BY category_id, collection_id
`

func (q *Queries) WeaveListCollectionPlacementsByModel(ctx context.Context, modelID string) ([]WeaveCollectionPlacement, error) {
	rows, err := q.db.Query(ctx, weaveListCollectionPlacementsByModel, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveCollectionPlacement{}
	for rows.Next() {
		var i WeaveCollectionPlacement
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ModelID,
			&i.CategoryID,
			&i.CollectionID,
			&i.IsRequired,
			&i.MinOccurs,
			&i.MaxOccurs,
			&i.IsHidden,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveUpsertCollectionPlacement = `-- name: WeaveUpsertCollectionPlacement :one

INSERT INTO weave_collection_placements (
    project_id, model_id, category_id, collection_id,
    is_required, min_occurs, max_occurs, is_hidden
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (model_id, category_id, collection_id) DO UPDATE SET
    is_required = EXCLUDED.is_required,
    min_occurs  = EXCLUDED.min_occurs,
    max_occurs  = EXCLUDED.max_occurs,
    is_hidden   = EXCLUDED.is_hidden,
    updated_at  = now()
RETURNING id, project_id, model_id, category_id, collection_id, is_required, min_occurs, max_occurs, is_hidden, created_at, updated_at
`

type WeaveUpsertCollectionPlacementParams struct {
	ProjectID    string `json:"project_id"`
	ModelID      string `json:"model_id"`
	CategoryID   string `json:"category_id"`
	CollectionID string `json:"collection_id"`
	IsRequired   bool   `json:"is_required"`
	MinOccurs    int32  `json:"min_occurs"`
	MaxOccurs    *int32 `json:"max_occurs"`
	IsHidden     bool   `json:"is_hidden"`
}

// Collection placements: per-(model, category, collection) constraints for a
// collection group inside a model. PK is bigserial; all
// entity references use semantic IDs directly.
func (q *Queries) WeaveUpsertCollectionPlacement(ctx context.Context, arg WeaveUpsertCollectionPlacementParams) (WeaveCollectionPlacement, error) {
	row := q.db.QueryRow(ctx, weaveUpsertCollectionPlacement,
		arg.ProjectID,
		arg.ModelID,
		arg.CategoryID,
		arg.CollectionID,
		arg.IsRequired,
		arg.MinOccurs,
		arg.MaxOccurs,
		arg.IsHidden,
	)
	var i WeaveCollectionPlacement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ModelID,
		&i.CategoryID,
		&i.CollectionID,
		&i.IsRequired,
		&i.MinOccurs,
		&i.MaxOccurs,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
