// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_path_elements.sql

package sqlcgen

import (
	"context"
)

const findFieldsByAnchoredSequence2 = `-- name: FindFieldsByAnchoredSequence2 :many
SELECT DISTINCT f.id, f.created_at, f.updated_at, f.semantic_id, f.system_name, f.ui_name, f.description, f.status, f.project_id, f.ontology_scope, f.ontology_path, f.path_elements, f.expected_value_type, f.examples, f.staging_id, f.deprecated, f.version_number, f.subfield_paths
FROM weave_fields f
JOIN weave_path_elements pe1 ON pe1.field_id = f.id
JOIN weave_path_elements pe2 ON pe2.field_id = f.id AND pe2.position > pe1.position
WHERE f.ontology_scope->>'local_name' = $1::text
  AND pe1.local_name = $2::text
  AND pe2.local_name = $3::text
`

type FindFieldsByAnchoredSequence2Params struct {
	Anchor string `json:"anchor"`
	Name1  string `json:"name1"`
	Name2  string `json:"name2"`
}

// Mode 3: Anchored — scope class filter + two-element subsequence
func (q *Queries) FindFieldsByAnchoredSequence2(ctx context.Context, arg FindFieldsByAnchoredSequence2Params) ([]WeaveField, error) {
	rows, err := q.db.Query(ctx, findFieldsByAnchoredSequence2, arg.Anchor, arg.Name1, arg.Name2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveField{}
	for rows.Next() {
		var i WeaveField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.OntologyPath,
			&i.PathElements,
			&i.ExpectedValueType,
			&i.Examples,
			&i.StagingID,
			&i.Deprecated,
			&i.VersionNumber,
			&i.SubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFieldsByContiguousSequence2 = `-- name: FindFieldsByContiguousSequence2 :many
SELECT DISTINCT f.id, f.created_at, f.updated_at, f.semantic_id, f.system_name, f.ui_name, f.description, f.status, f.project_id, f.ontology_scope, f.ontology_path, f.path_elements, f.expected_value_type, f.examples, f.staging_id, f.deprecated, f.version_number, f.subfield_paths
FROM weave_path_elements pe1
JOIN weave_path_elements pe2 ON pe2.field_id = pe1.field_id AND pe2.position = pe1.position + 1
JOIN weave_fields f ON f.id = pe1.field_id
WHERE pe1.local_name = $1::text
  AND pe2.local_name = $2::text
`

type FindFieldsByContiguousSequence2Params struct {
	Name1 string `json:"name1"`
	Name2 string `json:"name2"`
}

// Mode 1: Contiguous — two elements must be adjacent in path
func (q *Queries) FindFieldsByContiguousSequence2(ctx context.Context, arg FindFieldsByContiguousSequence2Params) ([]WeaveField, error) {
	rows, err := q.db.Query(ctx, findFieldsByContiguousSequence2, arg.Name1, arg.Name2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveField{}
	for rows.Next() {
		var i WeaveField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.OntologyPath,
			&i.PathElements,
			&i.ExpectedValueType,
			&i.Examples,
			&i.StagingID,
			&i.Deprecated,
			&i.VersionNumber,
			&i.SubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFieldsByContiguousSequence3 = `-- name: FindFieldsByContiguousSequence3 :many
SELECT DISTINCT f.id, f.created_at, f.updated_at, f.semantic_id, f.system_name, f.ui_name, f.description, f.status, f.project_id, f.ontology_scope, f.ontology_path, f.path_elements, f.expected_value_type, f.examples, f.staging_id, f.deprecated, f.version_number, f.subfield_paths
FROM weave_path_elements pe1
JOIN weave_path_elements pe2 ON pe2.field_id = pe1.field_id AND pe2.position = pe1.position + 1
JOIN weave_path_elements pe3 ON pe3.field_id = pe1.field_id AND pe3.position = pe2.position + 1
JOIN weave_fields f ON f.id = pe1.field_id
WHERE pe1.local_name = $1::text
  AND pe2.local_name = $2::text
  AND pe3.local_name = $3::text
`

type FindFieldsByContiguousSequence3Params struct {
	Name1 string `json:"name1"`
	Name2 string `json:"name2"`
	Name3 string `json:"name3"`
}

// Mode 1: Contiguous — three elements must be adjacent
func (q *Queries) FindFieldsByContiguousSequence3(ctx context.Context, arg FindFieldsByContiguousSequence3Params) ([]WeaveField, error) {
	rows, err := q.db.Query(ctx, findFieldsByContiguousSequence3, arg.Name1, arg.Name2, arg.Name3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveField{}
	for rows.Next() {
		var i WeaveField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.OntologyPath,
			&i.PathElements,
			&i.ExpectedValueType,
			&i.Examples,
			&i.StagingID,
			&i.Deprecated,
			&i.VersionNumber,
			&i.SubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFieldsBySubsequence2 = `-- name: FindFieldsBySubsequence2 :many
SELECT DISTINCT f.id, f.created_at, f.updated_at, f.semantic_id, f.system_name, f.ui_name, f.description, f.status, f.project_id, f.ontology_scope, f.ontology_path, f.path_elements, f.expected_value_type, f.examples, f.staging_id, f.deprecated, f.version_number, f.subfield_paths
FROM weave_path_elements pe1
JOIN weave_path_elements pe2 ON pe2.field_id = pe1.field_id AND pe2.position > pe1.position
JOIN weave_fields f ON f.id = pe1.field_id
WHERE pe1.local_name = $1::text
  AND pe2.local_name = $2::text
`

type FindFieldsBySubsequence2Params struct {
	Name1 string `json:"name1"`
	Name2 string `json:"name2"`
}

// Mode 2: Subsequence — two elements in order, gaps allowed
func (q *Queries) FindFieldsBySubsequence2(ctx context.Context, arg FindFieldsBySubsequence2Params) ([]WeaveField, error) {
	rows, err := q.db.Query(ctx, findFieldsBySubsequence2, arg.Name1, arg.Name2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveField{}
	for rows.Next() {
		var i WeaveField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.OntologyPath,
			&i.PathElements,
			&i.ExpectedValueType,
			&i.Examples,
			&i.StagingID,
			&i.Deprecated,
			&i.VersionNumber,
			&i.SubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFieldsBySubsequence3 = `-- name: FindFieldsBySubsequence3 :many
SELECT DISTINCT f.id, f.created_at, f.updated_at, f.semantic_id, f.system_name, f.ui_name, f.description, f.status, f.project_id, f.ontology_scope, f.ontology_path, f.path_elements, f.expected_value_type, f.examples, f.staging_id, f.deprecated, f.version_number, f.subfield_paths
FROM weave_path_elements pe1
JOIN weave_path_elements pe2 ON pe2.field_id = pe1.field_id AND pe2.position > pe1.position
JOIN weave_path_elements pe3 ON pe3.field_id = pe1.field_id AND pe3.position > pe2.position
JOIN weave_fields f ON f.id = pe1.field_id
WHERE pe1.local_name = $1::text
  AND pe2.local_name = $2::text
  AND pe3.local_name = $3::text
`

type FindFieldsBySubsequence3Params struct {
	Name1 string `json:"name1"`
	Name2 string `json:"name2"`
	Name3 string `json:"name3"`
}

// Mode 2: Subsequence — three elements in order, gaps allowed
func (q *Queries) FindFieldsBySubsequence3(ctx context.Context, arg FindFieldsBySubsequence3Params) ([]WeaveField, error) {
	rows, err := q.db.Query(ctx, findFieldsBySubsequence3, arg.Name1, arg.Name2, arg.Name3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveField{}
	for rows.Next() {
		var i WeaveField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.OntologyPath,
			&i.PathElements,
			&i.ExpectedValueType,
			&i.Examples,
			&i.StagingID,
			&i.Deprecated,
			&i.VersionNumber,
			&i.SubfieldPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
