// Code generated by tygo. DO NOT EDIT.
// Re-exports ScopeInfo and ParsedPath for single-import convenience.
export type { ScopeInfo, ParsedPath } from './parsed-path-types';

//////////
// source: path_element.go

/**
 * PathElement represents one step in an ontology path (class, property, or literal).
 * This is a core domain type used by Field, PathBuilder UI, and path queries.
 */
export interface PathElement {
  type: string; // "class", "property", or "literal"
  uri: string; // Full prefixed URI (e.g., "crm:E21_Person")
  prefix: string; // Namespace prefix (e.g., "crm")
  local_name: string; // Local name (e.g., "E21_Person")
  datatype?: string; // For literals: "rdf:literal", "xsd:date"
  position: number /* int */; // 0-indexed position in path
  complete?: boolean; // Editor-only: modeler marked the path finished in the path editor. Ignored by resolution, generators, and the path audit.
  class_code?: string; // Short class code (e.g., "E33_E41")
  instance_id?: string; // Legacy hand-coded bracket ID (e.g., "HERF.200_1"); persisted in path_elements JSONB
  path_node?: string; // Generated structural ancestor chain (slugified qnames). Set on class elements while building generator snapshots; never persisted.
  path_node_id?: string; // Short generated node id, {class_code}_{occurrence}, derived from PathNode. The X3ML variable / UI id. Supersedes InstanceID.
  ontology_version_id?: string; // FK to ontology version for compatibility checks
  /**
   * AdditionalTypes holds secondary class instantiations for multi-typed nodes.
   * Example: E29_Design_or_Procedure/crmdig:D1_Digital_Object means the node
   * is simultaneously an instance of both classes. The primary type is in the
   * fields above; additional types are here.
   */
  additional_types?: TypeRef[];
  /**
   * SubPropertyOf is set for CRM ".1" property-class qualifiers.
   * Example: P14.1_in_the_role_of qualifies P14_carried_out_by with a type.
   * The value is the parent property code (e.g., "P14" for "P14.1").
   */
  sub_property_of?: string;
}
/**
 * TypeRef identifies an ontology class used as an additional type on a path element.
 */
export interface TypeRef {
  uri: string; // Full prefixed URI (e.g., "crmdig:D1_Digital_Object")
  prefix: string; // Namespace prefix (e.g., "crmdig")
  local_name: string; // Local name (e.g., "D1_Digital_Object")
  class_code?: string; // Short class code (e.g., "D1")
}
