// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_vocabulary.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const weaveCreateConceptList = `-- name: WeaveCreateConceptList :one
INSERT INTO weave_concept_lists (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id,
    list_type, vocabulary_id
) VALUES (
    $1, NOW(), NOW(), $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id
`

type WeaveCreateConceptListParams struct {
	ID           string  `json:"id"`
	SemanticID   *string `json:"semantic_id"`
	SystemName   *string `json:"system_name"`
	UiName       []byte  `json:"ui_name"`
	Description  []byte  `json:"description"`
	Status       string  `json:"status"`
	ProjectID    string  `json:"project_id"`
	ListType     *string `json:"list_type"`
	VocabularyID *string `json:"vocabulary_id"`
}

func (q *Queries) WeaveCreateConceptList(ctx context.Context, arg WeaveCreateConceptListParams) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveCreateConceptList,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.ListType,
		arg.VocabularyID,
	)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
	)
	return i, err
}

const weaveCreateConceptListEntry = `-- name: WeaveCreateConceptListEntry :one
INSERT INTO weave_concept_list_entries (
    id, concept_list_id, vocabulary_entry_id, position,
    custom_label, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) RETURNING id, concept_list_id, vocabulary_entry_id, position, custom_label, created_at, updated_at
`

type WeaveCreateConceptListEntryParams struct {
	ID                string `json:"id"`
	ConceptListID     string `json:"concept_list_id"`
	VocabularyEntryID string `json:"vocabulary_entry_id"`
	Position          int32  `json:"position"`
	CustomLabel       []byte `json:"custom_label"`
}

func (q *Queries) WeaveCreateConceptListEntry(ctx context.Context, arg WeaveCreateConceptListEntryParams) (WeaveConceptListEntry, error) {
	row := q.db.QueryRow(ctx, weaveCreateConceptListEntry,
		arg.ID,
		arg.ConceptListID,
		arg.VocabularyEntryID,
		arg.Position,
		arg.CustomLabel,
	)
	var i WeaveConceptListEntry
	err := row.Scan(
		&i.ID,
		&i.ConceptListID,
		&i.VocabularyEntryID,
		&i.Position,
		&i.CustomLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveCreateVocabulary = `-- name: WeaveCreateVocabulary :one
INSERT INTO weave_vocabularies (
    id, created_at, updated_at, semantic_id, system_name,
    ui_name, description, status, project_id,
    connector_type, base_uri, config
) VALUES (
    $1, NOW(), NOW(), $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted
`

type WeaveCreateVocabularyParams struct {
	ID            string  `json:"id"`
	SemanticID    *string `json:"semantic_id"`
	SystemName    *string `json:"system_name"`
	UiName        []byte  `json:"ui_name"`
	Description   []byte  `json:"description"`
	Status        string  `json:"status"`
	ProjectID     *string `json:"project_id"`
	ConnectorType string  `json:"connector_type"`
	BaseUri       *string `json:"base_uri"`
	Config        []byte  `json:"config"`
}

func (q *Queries) WeaveCreateVocabulary(ctx context.Context, arg WeaveCreateVocabularyParams) (WeaveVocabulary, error) {
	row := q.db.QueryRow(ctx, weaveCreateVocabulary,
		arg.ID,
		arg.SemanticID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.ConnectorType,
		arg.BaseUri,
		arg.Config,
	)
	var i WeaveVocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ConnectorType,
		&i.BaseUri,
		&i.Config,
		&i.ConfigEncrypted,
	)
	return i, err
}

const weaveCreateVocabularyEntry = `-- name: WeaveCreateVocabularyEntry :one
INSERT INTO weave_vocabulary_entries (
    id, vocabulary_id, uri, label, scope_note,
    broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
) RETURNING id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
`

type WeaveCreateVocabularyEntryParams struct {
	ID               string          `json:"id"`
	VocabularyID     string          `json:"vocabulary_id"`
	Uri              string          `json:"uri"`
	Label            json.RawMessage `json:"label"`
	ScopeNote        []byte          `json:"scope_note"`
	BroaderUri       *string         `json:"broader_uri"`
	BroaderPath      json.RawMessage `json:"broader_path"`
	BroaderPathItems json.RawMessage `json:"broader_path_items"`
	ExternalID       *string         `json:"external_id"`
}

func (q *Queries) WeaveCreateVocabularyEntry(ctx context.Context, arg WeaveCreateVocabularyEntryParams) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveCreateVocabularyEntry,
		arg.ID,
		arg.VocabularyID,
		arg.Uri,
		arg.Label,
		arg.ScopeNote,
		arg.BroaderUri,
		arg.BroaderPath,
		arg.BroaderPathItems,
		arg.ExternalID,
	)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveDeleteConceptListEntry = `-- name: WeaveDeleteConceptListEntry :exec
DELETE FROM weave_concept_list_entries WHERE id = $1
`

func (q *Queries) WeaveDeleteConceptListEntry(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteConceptListEntry, id)
	return err
}

const weaveFindConceptListsByListType = `-- name: WeaveFindConceptListsByListType :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id FROM weave_concept_lists
WHERE list_type = $1
ORDER BY system_name ASC
`

func (q *Queries) WeaveFindConceptListsByListType(ctx context.Context, listType *string) ([]WeaveConceptList, error) {
	rows, err := q.db.Query(ctx, weaveFindConceptListsByListType, listType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveConceptList{}
	for rows.Next() {
		var i WeaveConceptList
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ListType,
			&i.VocabularyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveFindVocabularyForURI = `-- name: WeaveFindVocabularyForURI :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted FROM weave_vocabularies
WHERE base_uri IS NOT NULL
  AND base_uri <> ''
  AND $1::text LIKE base_uri || '%'
ORDER BY LENGTH(base_uri) DESC
LIMIT 1
`

func (q *Queries) WeaveFindVocabularyForURI(ctx context.Context, uri string) (WeaveVocabulary, error) {
	row := q.db.QueryRow(ctx, weaveFindVocabularyForURI, uri)
	var i WeaveVocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ConnectorType,
		&i.BaseUri,
		&i.Config,
		&i.ConfigEncrypted,
	)
	return i, err
}

const weaveGetConceptList = `-- name: WeaveGetConceptList :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id FROM weave_concept_lists WHERE id = $1
`

func (q *Queries) WeaveGetConceptList(ctx context.Context, id string) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveGetConceptList, id)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
	)
	return i, err
}

const weaveGetConceptListByIDOrSemanticID = `-- name: WeaveGetConceptListByIDOrSemanticID :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id FROM weave_concept_lists
WHERE id = $1::text
   OR semantic_id = $1::text
LIMIT 1
`

func (q *Queries) WeaveGetConceptListByIDOrSemanticID(ctx context.Context, id string) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveGetConceptListByIDOrSemanticID, id)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
	)
	return i, err
}

const weaveGetConceptListNamesByIDs = `-- name: WeaveGetConceptListNamesByIDs :many
SELECT id, semantic_id, ui_name, project_id
FROM weave_concept_lists
WHERE id = ANY($1::text[])
   OR semantic_id = ANY($1::text[])
`

type WeaveGetConceptListNamesByIDsRow struct {
	ID         string  `json:"id"`
	SemanticID *string `json:"semantic_id"`
	UiName     []byte  `json:"ui_name"`
	ProjectID  string  `json:"project_id"`
}

func (q *Queries) WeaveGetConceptListNamesByIDs(ctx context.Context, ids []string) ([]WeaveGetConceptListNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, weaveGetConceptListNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveGetConceptListNamesByIDsRow{}
	for rows.Next() {
		var i WeaveGetConceptListNamesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SemanticID,
			&i.UiName,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveGetProjectConceptList = `-- name: WeaveGetProjectConceptList :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id FROM weave_concept_lists
WHERE project_id = $1::text
  AND (id = $2::text OR semantic_id = $2::text)
`

type WeaveGetProjectConceptListParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) WeaveGetProjectConceptList(ctx context.Context, arg WeaveGetProjectConceptListParams) (WeaveConceptList, error) {
	row := q.db.QueryRow(ctx, weaveGetProjectConceptList, arg.ProjectID, arg.ID)
	var i WeaveConceptList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ListType,
		&i.VocabularyID,
	)
	return i, err
}

const weaveGetVocabulary = `-- name: WeaveGetVocabulary :one
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted FROM weave_vocabularies WHERE id = $1
`

func (q *Queries) WeaveGetVocabulary(ctx context.Context, id string) (WeaveVocabulary, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabulary, id)
	var i WeaveVocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SemanticID,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.ConnectorType,
		&i.BaseUri,
		&i.Config,
		&i.ConfigEncrypted,
	)
	return i, err
}

const weaveGetVocabularyEntry = `-- name: WeaveGetVocabularyEntry :one
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries WHERE id = $1
`

func (q *Queries) WeaveGetVocabularyEntry(ctx context.Context, id string) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabularyEntry, id)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveGetVocabularyEntryByURI = `-- name: WeaveGetVocabularyEntryByURI :one
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries
WHERE uri = $1::text
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) WeaveGetVocabularyEntryByURI(ctx context.Context, uri string) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabularyEntryByURI, uri)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveGetVocabularyEntryByVocabularyURI = `-- name: WeaveGetVocabularyEntryByVocabularyURI :one
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries
WHERE vocabulary_id = $1::text
  AND uri = $2::text
LIMIT 1
`

type WeaveGetVocabularyEntryByVocabularyURIParams struct {
	VocabularyID string `json:"vocabulary_id"`
	Uri          string `json:"uri"`
}

func (q *Queries) WeaveGetVocabularyEntryByVocabularyURI(ctx context.Context, arg WeaveGetVocabularyEntryByVocabularyURIParams) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveGetVocabularyEntryByVocabularyURI, arg.VocabularyID, arg.Uri)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const weaveListConceptListEntries = `-- name: WeaveListConceptListEntries :many
SELECT id, concept_list_id, vocabulary_entry_id, position, custom_label, created_at, updated_at FROM weave_concept_list_entries
WHERE concept_list_id = $1
ORDER BY position ASC
`

func (q *Queries) WeaveListConceptListEntries(ctx context.Context, conceptListID string) ([]WeaveConceptListEntry, error) {
	rows, err := q.db.Query(ctx, weaveListConceptListEntries, conceptListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveConceptListEntry{}
	for rows.Next() {
		var i WeaveConceptListEntry
		if err := rows.Scan(
			&i.ID,
			&i.ConceptListID,
			&i.VocabularyEntryID,
			&i.Position,
			&i.CustomLabel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListConceptListEntriesWithVocabulary = `-- name: WeaveListConceptListEntriesWithVocabulary :many
SELECT
    cle.id AS concept_list_entry_id,
    cle.concept_list_id,
    cle.vocabulary_entry_id,
    cle.position,
    cle.custom_label,
    cle.created_at AS concept_list_entry_created_at,
    cle.updated_at AS concept_list_entry_updated_at,
    ve.id AS entry_id,
    ve.vocabulary_id,
    ve.uri,
    ve.label,
    ve.scope_note,
    ve.broader_uri,
    ve.broader_path,
    ve.broader_path_items,
    ve.external_id,
    ve.created_at AS entry_created_at,
    ve.updated_at AS entry_updated_at
FROM weave_concept_list_entries cle
JOIN weave_vocabulary_entries ve ON ve.id = cle.vocabulary_entry_id
WHERE cle.concept_list_id = $1::text
ORDER BY cle.position ASC, ve.uri ASC
`

type WeaveListConceptListEntriesWithVocabularyRow struct {
	ConceptListEntryID        string          `json:"concept_list_entry_id"`
	ConceptListID             string          `json:"concept_list_id"`
	VocabularyEntryID         string          `json:"vocabulary_entry_id"`
	Position                  int32           `json:"position"`
	CustomLabel               []byte          `json:"custom_label"`
	ConceptListEntryCreatedAt time.Time       `json:"concept_list_entry_created_at"`
	ConceptListEntryUpdatedAt time.Time       `json:"concept_list_entry_updated_at"`
	EntryID                   string          `json:"entry_id"`
	VocabularyID              string          `json:"vocabulary_id"`
	Uri                       string          `json:"uri"`
	Label                     json.RawMessage `json:"label"`
	ScopeNote                 []byte          `json:"scope_note"`
	BroaderUri                *string         `json:"broader_uri"`
	BroaderPath               json.RawMessage `json:"broader_path"`
	BroaderPathItems          json.RawMessage `json:"broader_path_items"`
	ExternalID                *string         `json:"external_id"`
	EntryCreatedAt            time.Time       `json:"entry_created_at"`
	EntryUpdatedAt            time.Time       `json:"entry_updated_at"`
}

func (q *Queries) WeaveListConceptListEntriesWithVocabulary(ctx context.Context, conceptListID string) ([]WeaveListConceptListEntriesWithVocabularyRow, error) {
	rows, err := q.db.Query(ctx, weaveListConceptListEntriesWithVocabulary, conceptListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListConceptListEntriesWithVocabularyRow{}
	for rows.Next() {
		var i WeaveListConceptListEntriesWithVocabularyRow
		if err := rows.Scan(
			&i.ConceptListEntryID,
			&i.ConceptListID,
			&i.VocabularyEntryID,
			&i.Position,
			&i.CustomLabel,
			&i.ConceptListEntryCreatedAt,
			&i.ConceptListEntryUpdatedAt,
			&i.EntryID,
			&i.VocabularyID,
			&i.Uri,
			&i.Label,
			&i.ScopeNote,
			&i.BroaderUri,
			&i.BroaderPath,
			&i.BroaderPathItems,
			&i.ExternalID,
			&i.EntryCreatedAt,
			&i.EntryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListConceptLists = `-- name: WeaveListConceptLists :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, list_type, vocabulary_id FROM weave_concept_lists
WHERE project_id = $1
ORDER BY system_name ASC
`

func (q *Queries) WeaveListConceptLists(ctx context.Context, projectID string) ([]WeaveConceptList, error) {
	rows, err := q.db.Query(ctx, weaveListConceptLists, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveConceptList{}
	for rows.Next() {
		var i WeaveConceptList
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ListType,
			&i.VocabularyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListGlobalVocabularies = `-- name: WeaveListGlobalVocabularies :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted FROM weave_vocabularies
WHERE project_id IS NULL
ORDER BY system_name ASC
`

func (q *Queries) WeaveListGlobalVocabularies(ctx context.Context) ([]WeaveVocabulary, error) {
	rows, err := q.db.Query(ctx, weaveListGlobalVocabularies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveVocabulary{}
	for rows.Next() {
		var i WeaveVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ConnectorType,
			&i.BaseUri,
			&i.Config,
			&i.ConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListProjectScopedVocabularies = `-- name: WeaveListProjectScopedVocabularies :many
SELECT v.id, v.created_at, v.updated_at, v.semantic_id, v.system_name, v.ui_name, v.description, v.status, v.project_id, v.connector_type, v.base_uri, v.config, v.config_encrypted
FROM weave_vocabularies v
LEFT JOIN weave_project_vocabularies pv
    ON pv.vocabulary_id = v.id
    AND pv.project_id = $1::text
    AND pv.status = 'active'
WHERE v.project_id = $1::text
   OR pv.project_id = $1::text
ORDER BY (v.project_id IS NULL) DESC, v.system_name ASC, v.id ASC
`

func (q *Queries) WeaveListProjectScopedVocabularies(ctx context.Context, projectID string) ([]WeaveVocabulary, error) {
	rows, err := q.db.Query(ctx, weaveListProjectScopedVocabularies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveVocabulary{}
	for rows.Next() {
		var i WeaveVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ConnectorType,
			&i.BaseUri,
			&i.Config,
			&i.ConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListVocabularies = `-- name: WeaveListVocabularies :many
SELECT id, created_at, updated_at, semantic_id, system_name, ui_name, description, status, project_id, connector_type, base_uri, config, config_encrypted FROM weave_vocabularies
ORDER BY system_name ASC
`

func (q *Queries) WeaveListVocabularies(ctx context.Context) ([]WeaveVocabulary, error) {
	rows, err := q.db.Query(ctx, weaveListVocabularies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveVocabulary{}
	for rows.Next() {
		var i WeaveVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.ConnectorType,
			&i.BaseUri,
			&i.Config,
			&i.ConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSearchConceptListEntries = `-- name: WeaveSearchConceptListEntries :many
SELECT
    cle.id AS concept_list_entry_id,
    cle.concept_list_id,
    cle.vocabulary_entry_id,
    cle.position,
    cle.custom_label,
    cle.created_at AS concept_list_entry_created_at,
    cle.updated_at AS concept_list_entry_updated_at,
    ve.id AS entry_id,
    ve.vocabulary_id,
    ve.uri,
    ve.label,
    ve.scope_note,
    ve.broader_uri,
    ve.broader_path,
    ve.broader_path_items,
    ve.external_id,
    ve.created_at AS entry_created_at,
    ve.updated_at AS entry_updated_at
FROM weave_concept_list_entries cle
JOIN weave_vocabulary_entries ve ON ve.id = cle.vocabulary_entry_id
WHERE cle.concept_list_id = $1::text
  AND (
    EXISTS (SELECT 1 FROM jsonb_each_text(ve.label) WHERE value ILIKE '%' || $2::text || '%')
    OR ve.uri ILIKE '%' || $2::text || '%'
    OR ve.external_id ILIKE '%' || $2::text || '%'
  )
ORDER BY cle.position ASC, ve.uri ASC
LIMIT $3::integer
`

type WeaveSearchConceptListEntriesParams struct {
	ConceptListID string `json:"concept_list_id"`
	Query         string `json:"query"`
	ResultLimit   int32  `json:"result_limit"`
}

type WeaveSearchConceptListEntriesRow struct {
	ConceptListEntryID        string          `json:"concept_list_entry_id"`
	ConceptListID             string          `json:"concept_list_id"`
	VocabularyEntryID         string          `json:"vocabulary_entry_id"`
	Position                  int32           `json:"position"`
	CustomLabel               []byte          `json:"custom_label"`
	ConceptListEntryCreatedAt time.Time       `json:"concept_list_entry_created_at"`
	ConceptListEntryUpdatedAt time.Time       `json:"concept_list_entry_updated_at"`
	EntryID                   string          `json:"entry_id"`
	VocabularyID              string          `json:"vocabulary_id"`
	Uri                       string          `json:"uri"`
	Label                     json.RawMessage `json:"label"`
	ScopeNote                 []byte          `json:"scope_note"`
	BroaderUri                *string         `json:"broader_uri"`
	BroaderPath               json.RawMessage `json:"broader_path"`
	BroaderPathItems          json.RawMessage `json:"broader_path_items"`
	ExternalID                *string         `json:"external_id"`
	EntryCreatedAt            time.Time       `json:"entry_created_at"`
	EntryUpdatedAt            time.Time       `json:"entry_updated_at"`
}

func (q *Queries) WeaveSearchConceptListEntries(ctx context.Context, arg WeaveSearchConceptListEntriesParams) ([]WeaveSearchConceptListEntriesRow, error) {
	rows, err := q.db.Query(ctx, weaveSearchConceptListEntries, arg.ConceptListID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveSearchConceptListEntriesRow{}
	for rows.Next() {
		var i WeaveSearchConceptListEntriesRow
		if err := rows.Scan(
			&i.ConceptListEntryID,
			&i.ConceptListID,
			&i.VocabularyEntryID,
			&i.Position,
			&i.CustomLabel,
			&i.ConceptListEntryCreatedAt,
			&i.ConceptListEntryUpdatedAt,
			&i.EntryID,
			&i.VocabularyID,
			&i.Uri,
			&i.Label,
			&i.ScopeNote,
			&i.BroaderUri,
			&i.BroaderPath,
			&i.BroaderPathItems,
			&i.ExternalID,
			&i.EntryCreatedAt,
			&i.EntryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSearchVocabularyEntries = `-- name: WeaveSearchVocabularyEntries :many
SELECT id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at FROM weave_vocabulary_entries
WHERE vocabulary_id = $1::text
  AND (
    EXISTS (SELECT 1 FROM jsonb_each_text(label) WHERE value ILIKE '%' || $2::text || '%')
    OR uri ILIKE '%' || $2::text || '%'
    OR external_id ILIKE '%' || $2::text || '%'
  )
ORDER BY uri ASC
LIMIT 50
`

type WeaveSearchVocabularyEntriesParams struct {
	VocabularyID string `json:"vocabulary_id"`
	Query        string `json:"query"`
}

func (q *Queries) WeaveSearchVocabularyEntries(ctx context.Context, arg WeaveSearchVocabularyEntriesParams) ([]WeaveVocabularyEntry, error) {
	rows, err := q.db.Query(ctx, weaveSearchVocabularyEntries, arg.VocabularyID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveVocabularyEntry{}
	for rows.Next() {
		var i WeaveVocabularyEntry
		if err := rows.Scan(
			&i.ID,
			&i.VocabularyID,
			&i.Uri,
			&i.Label,
			&i.ScopeNote,
			&i.BroaderUri,
			&i.BroaderPath,
			&i.BroaderPathItems,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveUpdateConceptListEntryOrder = `-- name: WeaveUpdateConceptListEntryOrder :exec
UPDATE weave_concept_list_entries
SET position = $2, updated_at = NOW()
WHERE id = $1
`

type WeaveUpdateConceptListEntryOrderParams struct {
	ID       string `json:"id"`
	Position int32  `json:"position"`
}

func (q *Queries) WeaveUpdateConceptListEntryOrder(ctx context.Context, arg WeaveUpdateConceptListEntryOrderParams) error {
	_, err := q.db.Exec(ctx, weaveUpdateConceptListEntryOrder, arg.ID, arg.Position)
	return err
}

const weaveUpsertVocabularyEntry = `-- name: WeaveUpsertVocabularyEntry :one
INSERT INTO weave_vocabulary_entries (
    id, vocabulary_id, uri, label, scope_note,
    broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
) VALUES (
    $1::text, $2::text, $3::text, $4::jsonb, $5::jsonb,
    $6::text, $7::jsonb, $8::jsonb, $9::text, NOW(), NOW()
)
ON CONFLICT (vocabulary_id, uri) DO UPDATE SET
    label = EXCLUDED.label,
    scope_note = EXCLUDED.scope_note,
    broader_uri = EXCLUDED.broader_uri,
    broader_path = EXCLUDED.broader_path,
    broader_path_items = EXCLUDED.broader_path_items,
    external_id = EXCLUDED.external_id,
    updated_at = NOW()
RETURNING id, vocabulary_id, uri, label, scope_note, broader_uri, broader_path, broader_path_items, external_id, created_at, updated_at
`

type WeaveUpsertVocabularyEntryParams struct {
	ID               string          `json:"id"`
	VocabularyID     string          `json:"vocabulary_id"`
	Uri              string          `json:"uri"`
	Label            json.RawMessage `json:"label"`
	ScopeNote        json.RawMessage `json:"scope_note"`
	BroaderUri       string          `json:"broader_uri"`
	BroaderPath      json.RawMessage `json:"broader_path"`
	BroaderPathItems json.RawMessage `json:"broader_path_items"`
	ExternalID       string          `json:"external_id"`
}

func (q *Queries) WeaveUpsertVocabularyEntry(ctx context.Context, arg WeaveUpsertVocabularyEntryParams) (WeaveVocabularyEntry, error) {
	row := q.db.QueryRow(ctx, weaveUpsertVocabularyEntry,
		arg.ID,
		arg.VocabularyID,
		arg.Uri,
		arg.Label,
		arg.ScopeNote,
		arg.BroaderUri,
		arg.BroaderPath,
		arg.BroaderPathItems,
		arg.ExternalID,
	)
	var i WeaveVocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.Uri,
		&i.Label,
		&i.ScopeNote,
		&i.BroaderUri,
		&i.BroaderPath,
		&i.BroaderPathItems,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
