// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_models.sql

package sqlcgen

import (
	"context"
	"time"
)

const weaveActivateModel = `-- name: WeaveActivateModel :exec
UPDATE weave_models
SET deprecated = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) WeaveActivateModel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveActivateModel, id)
	return err
}

const weaveCountModels = `-- name: WeaveCountModels :one
SELECT COUNT(*) FROM weave_models
WHERE project_id = $1::text
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR system_name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR model_type = $3::text)
  AND ($4::text = '' OR ((ontology_scope::jsonb->>'prefix') || ':' || (ontology_scope::jsonb->>'local_name')) = $4::text)
`

type WeaveCountModelsParams struct {
	ProjectID  string `json:"project_id"`
	Search     string `json:"search"`
	ModelType  string `json:"model_type"`
	ScopeClass string `json:"scope_class"`
}

func (q *Queries) WeaveCountModels(ctx context.Context, arg WeaveCountModelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountModels,
		arg.ProjectID,
		arg.Search,
		arg.ModelType,
		arg.ScopeClass,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveCreateModel = `-- name: WeaveCreateModel :one
INSERT INTO weave_models (
    id, system_name, ui_name, description,
    status, project_id, ontology_scope, staging_id, model_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, staging_id, deprecated, version_number, model_type
`

type WeaveCreateModelParams struct {
	ID            string  `json:"id"`
	SystemName    *string `json:"system_name"`
	UiName        []byte  `json:"ui_name"`
	Description   []byte  `json:"description"`
	Status        string  `json:"status"`
	ProjectID     string  `json:"project_id"`
	OntologyScope []byte  `json:"ontology_scope"`
	StagingID     *int64  `json:"staging_id"`
	ModelType     string  `json:"model_type"`
}

func (q *Queries) WeaveCreateModel(ctx context.Context, arg WeaveCreateModelParams) (WeaveModel, error) {
	row := q.db.QueryRow(ctx, weaveCreateModel,
		arg.ID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.OntologyScope,
		arg.StagingID,
		arg.ModelType,
	)
	var i WeaveModel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.ModelType,
	)
	return i, err
}

const weaveDeleteModel = `-- name: WeaveDeleteModel :exec
DELETE FROM weave_models WHERE id = $1
`

func (q *Queries) WeaveDeleteModel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteModel, id)
	return err
}

const weaveDeprecateModel = `-- name: WeaveDeprecateModel :exec
UPDATE weave_models
SET deprecated = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) WeaveDeprecateModel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeprecateModel, id)
	return err
}

const weaveGetModelByID = `-- name: WeaveGetModelByID :one
SELECT id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, staging_id, deprecated, version_number, model_type FROM weave_models WHERE id = $1
`

func (q *Queries) WeaveGetModelByID(ctx context.Context, id string) (WeaveModel, error) {
	row := q.db.QueryRow(ctx, weaveGetModelByID, id)
	var i WeaveModel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.ModelType,
	)
	return i, err
}

const weaveGetModelByIdentifier = `-- name: WeaveGetModelByIdentifier :one
SELECT id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, staging_id, deprecated, version_number, model_type FROM weave_models
WHERE project_id = $1::text
  AND (system_name = $2::text OR id = $2::text)
LIMIT 1
`

type WeaveGetModelByIdentifierParams struct {
	ProjectID  string `json:"project_id"`
	Identifier string `json:"identifier"`
}

func (q *Queries) WeaveGetModelByIdentifier(ctx context.Context, arg WeaveGetModelByIdentifierParams) (WeaveModel, error) {
	row := q.db.QueryRow(ctx, weaveGetModelByIdentifier, arg.ProjectID, arg.Identifier)
	var i WeaveModel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.ModelType,
	)
	return i, err
}

const weaveGetModelNamesByIDs = `-- name: WeaveGetModelNamesByIDs :many
SELECT id, ui_name FROM weave_models WHERE id = ANY($1::text[])
`

type WeaveGetModelNamesByIDsRow struct {
	ID     string `json:"id"`
	UiName []byte `json:"ui_name"`
}

func (q *Queries) WeaveGetModelNamesByIDs(ctx context.Context, ids []string) ([]WeaveGetModelNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, weaveGetModelNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveGetModelNamesByIDsRow{}
	for rows.Next() {
		var i WeaveGetModelNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.UiName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListModelOptions = `-- name: WeaveListModelOptions :many
SELECT id, system_name, ui_name, status
FROM weave_models
WHERE project_id = $1::text
  AND deprecated = false
ORDER BY system_name ASC
`

type WeaveListModelOptionsRow struct {
	ID         string  `json:"id"`
	SystemName *string `json:"system_name"`
	UiName     []byte  `json:"ui_name"`
	Status     string  `json:"status"`
}

// Lightweight options list for ref pickers — only the columns the UI needs.
// No COUNT companion, no description payload, no search filter (the
// frontend filters client-side once the small list is loaded).
func (q *Queries) WeaveListModelOptions(ctx context.Context, projectID string) ([]WeaveListModelOptionsRow, error) {
	rows, err := q.db.Query(ctx, weaveListModelOptions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListModelOptionsRow{}
	for rows.Next() {
		var i WeaveListModelOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemName,
			&i.UiName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListModelScopeClasses = `-- name: WeaveListModelScopeClasses :many
SELECT DISTINCT ((ontology_scope::jsonb->>'prefix') || ':' || (ontology_scope::jsonb->>'local_name'))::text AS scope_class
FROM weave_models
WHERE project_id = $1
  AND ontology_scope IS NOT NULL
  AND ontology_scope->>'prefix' IS NOT NULL
  AND ontology_scope->>'local_name' IS NOT NULL
ORDER BY scope_class ASC
`

// Returns distinct ontology scope classes (prefix:local_name) used by
// models in this project. Drives the scope_class filter dropdown.
func (q *Queries) WeaveListModelScopeClasses(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.Query(ctx, weaveListModelScopeClasses, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scope_class string
		if err := rows.Scan(&scope_class); err != nil {
			return nil, err
		}
		items = append(items, scope_class)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListModels = `-- name: WeaveListModels :many
SELECT id, created_at, updated_at, system_name, ui_name, description,
       status, project_id, ontology_scope, staging_id, deprecated, model_type
FROM weave_models
WHERE project_id = $1::text
  AND ($2::text = ''
       OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $2::text || '%')
       OR system_name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR model_type = $3::text)
  AND ($4::text = '' OR ((ontology_scope::jsonb->>'prefix') || ':' || (ontology_scope::jsonb->>'local_name')) = $4::text)
ORDER BY
    CASE WHEN model_type = 'core' THEN 0 ELSE 1 END,
    CASE WHEN $5::text = 'ui_name' AND NOT $6::boolean THEN ui_name->>'en' END ASC NULLS LAST,
    CASE WHEN $5::text = 'ui_name' AND $6::boolean THEN ui_name->>'en' END DESC NULLS LAST,
    CASE WHEN $5::text = 'name' AND NOT $6::boolean THEN system_name END ASC NULLS LAST,
    CASE WHEN $5::text = 'name' AND $6::boolean THEN system_name END DESC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND NOT $6::boolean THEN system_name END ASC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND $6::boolean THEN system_name END DESC NULLS LAST,
    CASE WHEN $5::text = 'updated_at' AND NOT $6::boolean THEN updated_at END ASC,
    CASE WHEN $5::text = 'updated_at' AND $6::boolean THEN updated_at END DESC,
    system_name ASC
LIMIT $8::integer OFFSET $7::integer
`

type WeaveListModelsParams struct {
	ProjectID    string `json:"project_id"`
	Search       string `json:"search"`
	ModelType    string `json:"model_type"`
	ScopeClass   string `json:"scope_class"`
	SortBy       string `json:"sort_by"`
	SortDesc     bool   `json:"sort_desc"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type WeaveListModelsRow struct {
	ID            string    `json:"id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	SystemName    *string   `json:"system_name"`
	UiName        []byte    `json:"ui_name"`
	Description   []byte    `json:"description"`
	Status        string    `json:"status"`
	ProjectID     string    `json:"project_id"`
	OntologyScope []byte    `json:"ontology_scope"`
	StagingID     *int64    `json:"staging_id"`
	Deprecated    bool      `json:"deprecated"`
	ModelType     string    `json:"model_type"`
}

func (q *Queries) WeaveListModels(ctx context.Context, arg WeaveListModelsParams) ([]WeaveListModelsRow, error) {
	rows, err := q.db.Query(ctx, weaveListModels,
		arg.ProjectID,
		arg.Search,
		arg.ModelType,
		arg.ScopeClass,
		arg.SortBy,
		arg.SortDesc,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListModelsRow{}
	for rows.Next() {
		var i WeaveListModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.ProjectID,
			&i.OntologyScope,
			&i.StagingID,
			&i.Deprecated,
			&i.ModelType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveModelIsInUse = `-- name: WeaveModelIsInUse :one
SELECT EXISTS (
    SELECT 1 FROM weave_override_refs r
    JOIN weave_field_overrides o ON o.id = r.override_id
    WHERE r.target_id = $1
      AND r.ref_type IN ('resource_model','collection_model')
      AND o.project_id = $2
    LIMIT 1
)::bool
`

type WeaveModelIsInUseParams struct {
	TargetID  string `json:"target_id"`
	ProjectID string `json:"project_id"`
}

// Returns true when any field's override-refs point at this model
// (ref_type IN ('resource_model','collection_model'), target_id = $1).
// The model's OWN override rows (entity_type='model', entity_id=$1)
// are the model's content — they don't count as in-use.
func (q *Queries) WeaveModelIsInUse(ctx context.Context, arg WeaveModelIsInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, weaveModelIsInUse, arg.TargetID, arg.ProjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const weaveModelUsageCount = `-- name: WeaveModelUsageCount :one
SELECT COUNT(DISTINCT o.field_id) AS field_count
FROM weave_override_refs r
JOIN weave_field_overrides o ON o.id = r.override_id
WHERE r.target_id = $1
  AND r.ref_type IN ('resource_model','collection_model')
  AND o.project_id = $2
`

type WeaveModelUsageCountParams struct {
	TargetID  string `json:"target_id"`
	ProjectID string `json:"project_id"`
}

// Count of distinct fields referencing this model as a value target.
func (q *Queries) WeaveModelUsageCount(ctx context.Context, arg WeaveModelUsageCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveModelUsageCount, arg.TargetID, arg.ProjectID)
	var field_count int64
	err := row.Scan(&field_count)
	return field_count, err
}

const weaveModelUsageSamples = `-- name: WeaveModelUsageSamples :many
SELECT DISTINCT
    f.id          AS field_id,
    f.semantic_id AS field_semantic_id,
    COALESCE(f.ui_name ->> 'en', f.system_name, '') AS field_name
FROM weave_override_refs r
JOIN weave_field_overrides o ON o.id = r.override_id
JOIN weave_fields f ON f.id = o.field_id
WHERE r.target_id = $1
  AND r.ref_type IN ('resource_model','collection_model')
  AND o.project_id = $2
ORDER BY field_name
LIMIT 10
`

type WeaveModelUsageSamplesParams struct {
	TargetID  string `json:"target_id"`
	ProjectID string `json:"project_id"`
}

type WeaveModelUsageSamplesRow struct {
	FieldID         string  `json:"field_id"`
	FieldSemanticID *string `json:"field_semantic_id"`
	FieldName       string  `json:"field_name"`
}

// Up to 10 sample fields referencing this model as a value target.
func (q *Queries) WeaveModelUsageSamples(ctx context.Context, arg WeaveModelUsageSamplesParams) ([]WeaveModelUsageSamplesRow, error) {
	rows, err := q.db.Query(ctx, weaveModelUsageSamples, arg.TargetID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveModelUsageSamplesRow{}
	for rows.Next() {
		var i WeaveModelUsageSamplesRow
		if err := rows.Scan(&i.FieldID, &i.FieldSemanticID, &i.FieldName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveUpdateModel = `-- name: WeaveUpdateModel :one
UPDATE weave_models SET
    ui_name = $2, description = $3, system_name = $4, status = $5,
    ontology_scope = $6, model_type = $7, updated_at = NOW()
WHERE id = $1 RETURNING id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, staging_id, deprecated, version_number, model_type
`

type WeaveUpdateModelParams struct {
	ID            string  `json:"id"`
	UiName        []byte  `json:"ui_name"`
	Description   []byte  `json:"description"`
	SystemName    *string `json:"system_name"`
	Status        string  `json:"status"`
	OntologyScope []byte  `json:"ontology_scope"`
	ModelType     string  `json:"model_type"`
}

func (q *Queries) WeaveUpdateModel(ctx context.Context, arg WeaveUpdateModelParams) (WeaveModel, error) {
	row := q.db.QueryRow(ctx, weaveUpdateModel,
		arg.ID,
		arg.UiName,
		arg.Description,
		arg.SystemName,
		arg.Status,
		arg.OntologyScope,
		arg.ModelType,
	)
	var i WeaveModel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.ModelType,
	)
	return i, err
}

const weaveUpsertModel = `-- name: WeaveUpsertModel :one
INSERT INTO weave_models (
    id, system_name, ui_name, description,
    status, project_id, ontology_scope, staging_id, model_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    system_name = EXCLUDED.system_name,
    ui_name = EXCLUDED.ui_name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    project_id = EXCLUDED.project_id,
    ontology_scope = EXCLUDED.ontology_scope,
    staging_id = EXCLUDED.staging_id,
    model_type = EXCLUDED.model_type,
    updated_at = NOW()
RETURNING id, created_at, updated_at, system_name, ui_name, description, status, project_id, ontology_scope, staging_id, deprecated, version_number, model_type
`

type WeaveUpsertModelParams struct {
	ID            string  `json:"id"`
	SystemName    *string `json:"system_name"`
	UiName        []byte  `json:"ui_name"`
	Description   []byte  `json:"description"`
	Status        string  `json:"status"`
	ProjectID     string  `json:"project_id"`
	OntologyScope []byte  `json:"ontology_scope"`
	StagingID     *int64  `json:"staging_id"`
	ModelType     string  `json:"model_type"`
}

func (q *Queries) WeaveUpsertModel(ctx context.Context, arg WeaveUpsertModelParams) (WeaveModel, error) {
	row := q.db.QueryRow(ctx, weaveUpsertModel,
		arg.ID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.ProjectID,
		arg.OntologyScope,
		arg.StagingID,
		arg.ModelType,
	)
	var i WeaveModel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.ProjectID,
		&i.OntologyScope,
		&i.StagingID,
		&i.Deprecated,
		&i.VersionNumber,
		&i.ModelType,
	)
	return i, err
}
