// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_ontology_relations.sql

package sqlcgen

import (
	"context"
)

const weaveDeleteOntologyRelationsForSource = `-- name: WeaveDeleteOntologyRelationsForSource :exec

DELETE FROM weave_ontology_relations
WHERE source_id = $1 AND source_kind = $2
`

type WeaveDeleteOntologyRelationsForSourceParams struct {
	SourceID   string `json:"source_id"`
	SourceKind string `json:"source_kind"`
}

// Recursive ancestor / descendant CTEs intentionally omitted here — sqlc's
// parser flags ambiguity in the recursive arm when used through generated
// code. Phase D's autocomplete subpackage runs these as inline SQL via
// pgxpool directly.
func (q *Queries) WeaveDeleteOntologyRelationsForSource(ctx context.Context, arg WeaveDeleteOntologyRelationsForSourceParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteOntologyRelationsForSource, arg.SourceID, arg.SourceKind)
	return err
}

const weaveDeleteOntologyRelationsForSourceByType = `-- name: WeaveDeleteOntologyRelationsForSourceByType :exec
DELETE FROM weave_ontology_relations
WHERE source_id = $1 AND source_kind = $2 AND rel_type = $3
`

type WeaveDeleteOntologyRelationsForSourceByTypeParams struct {
	SourceID   string `json:"source_id"`
	SourceKind string `json:"source_kind"`
	RelType    string `json:"rel_type"`
}

func (q *Queries) WeaveDeleteOntologyRelationsForSourceByType(ctx context.Context, arg WeaveDeleteOntologyRelationsForSourceByTypeParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteOntologyRelationsForSourceByType, arg.SourceID, arg.SourceKind, arg.RelType)
	return err
}

const weaveInsertOntologyRelation = `-- name: WeaveInsertOntologyRelation :exec
INSERT INTO weave_ontology_relations (
    source_id, source_kind, rel_type, target_qname, position
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_id, source_kind, rel_type, target_qname) DO NOTHING
`

type WeaveInsertOntologyRelationParams struct {
	SourceID    string `json:"source_id"`
	SourceKind  string `json:"source_kind"`
	RelType     string `json:"rel_type"`
	TargetQname string `json:"target_qname"`
	Position    int32  `json:"position"`
}

func (q *Queries) WeaveInsertOntologyRelation(ctx context.Context, arg WeaveInsertOntologyRelationParams) error {
	_, err := q.db.Exec(ctx, weaveInsertOntologyRelation,
		arg.SourceID,
		arg.SourceKind,
		arg.RelType,
		arg.TargetQname,
		arg.Position,
	)
	return err
}

const weaveListOntologyRelationsForSource = `-- name: WeaveListOntologyRelationsForSource :many
SELECT source_id, source_kind, rel_type, target_qname, position FROM weave_ontology_relations
WHERE source_id = $1 AND source_kind = $2
ORDER BY rel_type ASC, position ASC
`

type WeaveListOntologyRelationsForSourceParams struct {
	SourceID   string `json:"source_id"`
	SourceKind string `json:"source_kind"`
}

func (q *Queries) WeaveListOntologyRelationsForSource(ctx context.Context, arg WeaveListOntologyRelationsForSourceParams) ([]WeaveOntologyRelation, error) {
	rows, err := q.db.Query(ctx, weaveListOntologyRelationsForSource, arg.SourceID, arg.SourceKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyRelation{}
	for rows.Next() {
		var i WeaveOntologyRelation
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceKind,
			&i.RelType,
			&i.TargetQname,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOntologyRelationsForSourceByType = `-- name: WeaveListOntologyRelationsForSourceByType :many
SELECT source_id, source_kind, rel_type, target_qname, position FROM weave_ontology_relations
WHERE source_id = $1 AND source_kind = $2 AND rel_type = $3
ORDER BY position ASC
`

type WeaveListOntologyRelationsForSourceByTypeParams struct {
	SourceID   string `json:"source_id"`
	SourceKind string `json:"source_kind"`
	RelType    string `json:"rel_type"`
}

func (q *Queries) WeaveListOntologyRelationsForSourceByType(ctx context.Context, arg WeaveListOntologyRelationsForSourceByTypeParams) ([]WeaveOntologyRelation, error) {
	rows, err := q.db.Query(ctx, weaveListOntologyRelationsForSourceByType, arg.SourceID, arg.SourceKind, arg.RelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyRelation{}
	for rows.Next() {
		var i WeaveOntologyRelation
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceKind,
			&i.RelType,
			&i.TargetQname,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListOntologyRelationsForTarget = `-- name: WeaveListOntologyRelationsForTarget :many
SELECT source_id, source_kind, rel_type, target_qname, position FROM weave_ontology_relations
WHERE target_qname = $1 AND rel_type = $2
ORDER BY source_id ASC
`

type WeaveListOntologyRelationsForTargetParams struct {
	TargetQname string `json:"target_qname"`
	RelType     string `json:"rel_type"`
}

func (q *Queries) WeaveListOntologyRelationsForTarget(ctx context.Context, arg WeaveListOntologyRelationsForTargetParams) ([]WeaveOntologyRelation, error) {
	rows, err := q.db.Query(ctx, weaveListOntologyRelationsForTarget, arg.TargetQname, arg.RelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveOntologyRelation{}
	for rows.Next() {
		var i WeaveOntologyRelation
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceKind,
			&i.RelType,
			&i.TargetQname,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
