// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_project_ontology_versions.sql

package sqlcgen

import (
	"context"
)

const weaveClearProjectPrimaryOntologies = `-- name: WeaveClearProjectPrimaryOntologies :exec
UPDATE weave_project_ontology_versions
SET is_primary = false
WHERE project_id = $1 AND is_primary = true
`

func (q *Queries) WeaveClearProjectPrimaryOntologies(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, weaveClearProjectPrimaryOntologies, projectID)
	return err
}

const weaveCountPathElementsForVersionInProject = `-- name: WeaveCountPathElementsForVersionInProject :one
SELECT COUNT(*) FROM weave_path_elements wpe
JOIN weave_fields wf ON wpe.field_id = wf.id
WHERE wpe.ontology_version_id = $1 AND wf.project_id = $2
`

type WeaveCountPathElementsForVersionInProjectParams struct {
	OntologyVersionID *string `json:"ontology_version_id"`
	ProjectID         string  `json:"project_id"`
}

// Used as the delete-usage guard in Task 19.
func (q *Queries) WeaveCountPathElementsForVersionInProject(ctx context.Context, arg WeaveCountPathElementsForVersionInProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountPathElementsForVersionInProject, arg.OntologyVersionID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveCreateProjectOntologyVersion = `-- name: WeaveCreateProjectOntologyVersion :one
INSERT INTO weave_project_ontology_versions (
    project_id, ontology_version_id, added_by_id,
    is_primary, usage_notes, added_at
) VALUES ($1, $2, $3, $4, $5, now())
RETURNING project_id, ontology_version_id, added_at, added_by_id, is_primary, usage_notes, version_number
`

type WeaveCreateProjectOntologyVersionParams struct {
	ProjectID         string  `json:"project_id"`
	OntologyVersionID string  `json:"ontology_version_id"`
	AddedByID         *string `json:"added_by_id"`
	IsPrimary         *bool   `json:"is_primary"`
	UsageNotes        *string `json:"usage_notes"`
}

func (q *Queries) WeaveCreateProjectOntologyVersion(ctx context.Context, arg WeaveCreateProjectOntologyVersionParams) (WeaveProjectOntologyVersion, error) {
	row := q.db.QueryRow(ctx, weaveCreateProjectOntologyVersion,
		arg.ProjectID,
		arg.OntologyVersionID,
		arg.AddedByID,
		arg.IsPrimary,
		arg.UsageNotes,
	)
	var i WeaveProjectOntologyVersion
	err := row.Scan(
		&i.ProjectID,
		&i.OntologyVersionID,
		&i.AddedAt,
		&i.AddedByID,
		&i.IsPrimary,
		&i.UsageNotes,
		&i.VersionNumber,
	)
	return i, err
}

const weaveDeleteProjectOntologyVersion = `-- name: WeaveDeleteProjectOntologyVersion :exec
DELETE FROM weave_project_ontology_versions
WHERE project_id = $1 AND ontology_version_id = $2
`

type WeaveDeleteProjectOntologyVersionParams struct {
	ProjectID         string `json:"project_id"`
	OntologyVersionID string `json:"ontology_version_id"`
}

func (q *Queries) WeaveDeleteProjectOntologyVersion(ctx context.Context, arg WeaveDeleteProjectOntologyVersionParams) error {
	_, err := q.db.Exec(ctx, weaveDeleteProjectOntologyVersion, arg.ProjectID, arg.OntologyVersionID)
	return err
}

const weaveGetProjectOntologyVersion = `-- name: WeaveGetProjectOntologyVersion :one
SELECT project_id, ontology_version_id, added_at, added_by_id, is_primary, usage_notes, version_number FROM weave_project_ontology_versions
WHERE project_id = $1 AND ontology_version_id = $2
`

type WeaveGetProjectOntologyVersionParams struct {
	ProjectID         string `json:"project_id"`
	OntologyVersionID string `json:"ontology_version_id"`
}

func (q *Queries) WeaveGetProjectOntologyVersion(ctx context.Context, arg WeaveGetProjectOntologyVersionParams) (WeaveProjectOntologyVersion, error) {
	row := q.db.QueryRow(ctx, weaveGetProjectOntologyVersion, arg.ProjectID, arg.OntologyVersionID)
	var i WeaveProjectOntologyVersion
	err := row.Scan(
		&i.ProjectID,
		&i.OntologyVersionID,
		&i.AddedAt,
		&i.AddedByID,
		&i.IsPrimary,
		&i.UsageNotes,
		&i.VersionNumber,
	)
	return i, err
}

const weaveListProjectOntologyVersions = `-- name: WeaveListProjectOntologyVersions :many
SELECT project_id, ontology_version_id, added_at, added_by_id, is_primary, usage_notes, version_number FROM weave_project_ontology_versions
WHERE project_id = $1
ORDER BY is_primary DESC, added_at ASC
`

func (q *Queries) WeaveListProjectOntologyVersions(ctx context.Context, projectID string) ([]WeaveProjectOntologyVersion, error) {
	rows, err := q.db.Query(ctx, weaveListProjectOntologyVersions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveProjectOntologyVersion{}
	for rows.Next() {
		var i WeaveProjectOntologyVersion
		if err := rows.Scan(
			&i.ProjectID,
			&i.OntologyVersionID,
			&i.AddedAt,
			&i.AddedByID,
			&i.IsPrimary,
			&i.UsageNotes,
			&i.VersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSamplePathElementFieldsForVersion = `-- name: WeaveSamplePathElementFieldsForVersion :many
SELECT DISTINCT wf.id, wf.semantic_id, wf.system_name, wf.ui_name
FROM weave_path_elements wpe
JOIN weave_fields wf ON wpe.field_id = wf.id
WHERE wpe.ontology_version_id = $1 AND wf.project_id = $2
LIMIT 10
`

type WeaveSamplePathElementFieldsForVersionParams struct {
	OntologyVersionID *string `json:"ontology_version_id"`
	ProjectID         string  `json:"project_id"`
}

type WeaveSamplePathElementFieldsForVersionRow struct {
	ID         string  `json:"id"`
	SemanticID *string `json:"semantic_id"`
	SystemName *string `json:"system_name"`
	UiName     []byte  `json:"ui_name"`
}

// Returns up to 10 field samples referencing the version; surfaced in 409 payloads.
func (q *Queries) WeaveSamplePathElementFieldsForVersion(ctx context.Context, arg WeaveSamplePathElementFieldsForVersionParams) ([]WeaveSamplePathElementFieldsForVersionRow, error) {
	rows, err := q.db.Query(ctx, weaveSamplePathElementFieldsForVersion, arg.OntologyVersionID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveSamplePathElementFieldsForVersionRow{}
	for rows.Next() {
		var i WeaveSamplePathElementFieldsForVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.SemanticID,
			&i.SystemName,
			&i.UiName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSetProjectPrimaryOntology = `-- name: WeaveSetProjectPrimaryOntology :exec
UPDATE weave_project_ontology_versions
SET is_primary = true
WHERE project_id = $1 AND ontology_version_id = $2
`

type WeaveSetProjectPrimaryOntologyParams struct {
	ProjectID         string `json:"project_id"`
	OntologyVersionID string `json:"ontology_version_id"`
}

func (q *Queries) WeaveSetProjectPrimaryOntology(ctx context.Context, arg WeaveSetProjectPrimaryOntologyParams) error {
	_, err := q.db.Exec(ctx, weaveSetProjectPrimaryOntology, arg.ProjectID, arg.OntologyVersionID)
	return err
}

const weaveUpdateProjectOntologyVersion = `-- name: WeaveUpdateProjectOntologyVersion :one
UPDATE weave_project_ontology_versions
SET is_primary = $3,
    usage_notes = $4
WHERE project_id = $1 AND ontology_version_id = $2
RETURNING project_id, ontology_version_id, added_at, added_by_id, is_primary, usage_notes, version_number
`

type WeaveUpdateProjectOntologyVersionParams struct {
	ProjectID         string  `json:"project_id"`
	OntologyVersionID string  `json:"ontology_version_id"`
	IsPrimary         *bool   `json:"is_primary"`
	UsageNotes        *string `json:"usage_notes"`
}

func (q *Queries) WeaveUpdateProjectOntologyVersion(ctx context.Context, arg WeaveUpdateProjectOntologyVersionParams) (WeaveProjectOntologyVersion, error) {
	row := q.db.QueryRow(ctx, weaveUpdateProjectOntologyVersion,
		arg.ProjectID,
		arg.OntologyVersionID,
		arg.IsPrimary,
		arg.UsageNotes,
	)
	var i WeaveProjectOntologyVersion
	err := row.Scan(
		&i.ProjectID,
		&i.OntologyVersionID,
		&i.AddedAt,
		&i.AddedByID,
		&i.IsPrimary,
		&i.UsageNotes,
		&i.VersionNumber,
	)
	return i, err
}
