// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weave_projects.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const weaveCountProjects = `-- name: WeaveCountProjects :one
SELECT COUNT(*) FROM weave_projects
WHERE
    ($1::text = ''
     OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $1::text || '%')
     OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $1::text || '%')
     OR system_name ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR owner_id = $2::text)
    AND ($3::text = '' OR created_by_id = $3::text)
    AND ($4::text = ''
         OR EXISTS (SELECT 1 FROM weave_project_actors wpa
                    WHERE wpa.project_id = weave_projects.id
                      AND wpa.actor_id = $4::text
                      AND wpa.role = 'owner'))
`

type WeaveCountProjectsParams struct {
	Search        string `json:"search"`
	OwnerID       string `json:"owner_id"`
	CreatedByID   string `json:"created_by_id"`
	InstitutionID string `json:"institution_id"`
}

func (q *Queries) WeaveCountProjects(ctx context.Context, arg WeaveCountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, weaveCountProjects,
		arg.Search,
		arg.OwnerID,
		arg.CreatedByID,
		arg.InstitutionID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const weaveCreateProject = `-- name: WeaveCreateProject :one
INSERT INTO weave_projects (
    id, system_name, ui_name, description,
    status, namespace, parent_project_id, owner_id, staging_id, visibility, created_by_id, is_master_weave
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, created_at, updated_at, system_name, ui_name, description, status, namespace, parent_project_id, staging_id, owner_id, visibility, deprecated, license, readme, topics, base_url, created_by_id, version_number, enforce_concept_lists, is_master_weave
`

type WeaveCreateProjectParams struct {
	ID              string  `json:"id"`
	SystemName      *string `json:"system_name"`
	UiName          []byte  `json:"ui_name"`
	Description     []byte  `json:"description"`
	Status          string  `json:"status"`
	Namespace       *string `json:"namespace"`
	ParentProjectID *string `json:"parent_project_id"`
	OwnerID         string  `json:"owner_id"`
	StagingID       *int64  `json:"staging_id"`
	Visibility      string  `json:"visibility"`
	CreatedByID     *string `json:"created_by_id"`
	IsMasterWeave   bool    `json:"is_master_weave"`
}

func (q *Queries) WeaveCreateProject(ctx context.Context, arg WeaveCreateProjectParams) (WeaveProject, error) {
	row := q.db.QueryRow(ctx, weaveCreateProject,
		arg.ID,
		arg.SystemName,
		arg.UiName,
		arg.Description,
		arg.Status,
		arg.Namespace,
		arg.ParentProjectID,
		arg.OwnerID,
		arg.StagingID,
		arg.Visibility,
		arg.CreatedByID,
		arg.IsMasterWeave,
	)
	var i WeaveProject
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.Namespace,
		&i.ParentProjectID,
		&i.StagingID,
		&i.OwnerID,
		&i.Visibility,
		&i.Deprecated,
		&i.License,
		&i.Readme,
		&i.Topics,
		&i.BaseUrl,
		&i.CreatedByID,
		&i.VersionNumber,
		&i.EnforceConceptLists,
		&i.IsMasterWeave,
	)
	return i, err
}

const weaveDeleteProject = `-- name: WeaveDeleteProject :exec
DELETE FROM weave_projects WHERE id = $1
`

func (q *Queries) WeaveDeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, weaveDeleteProject, id)
	return err
}

const weaveGetProjectByID = `-- name: WeaveGetProjectByID :one
SELECT id, created_at, updated_at, system_name, ui_name, description, status, namespace, parent_project_id, staging_id, owner_id, visibility, deprecated, license, readme, topics, base_url, created_by_id, version_number, enforce_concept_lists, is_master_weave FROM weave_projects WHERE id = $1
`

func (q *Queries) WeaveGetProjectByID(ctx context.Context, id string) (WeaveProject, error) {
	row := q.db.QueryRow(ctx, weaveGetProjectByID, id)
	var i WeaveProject
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.Namespace,
		&i.ParentProjectID,
		&i.StagingID,
		&i.OwnerID,
		&i.Visibility,
		&i.Deprecated,
		&i.License,
		&i.Readme,
		&i.Topics,
		&i.BaseUrl,
		&i.CreatedByID,
		&i.VersionNumber,
		&i.EnforceConceptLists,
		&i.IsMasterWeave,
	)
	return i, err
}

const weaveGetProjectParentID = `-- name: WeaveGetProjectParentID :one
SELECT parent_project_id FROM weave_projects WHERE id = $1
`

// Returns the parent project's ID (nullable). Used by ResolvedOntologyVersions
// (parent-walk) and UpdateProjectOntologySettings (cycle detection, Task 15).
func (q *Queries) WeaveGetProjectParentID(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, weaveGetProjectParentID, id)
	var parent_project_id *string
	err := row.Scan(&parent_project_id)
	return parent_project_id, err
}

const weaveListChildProjects = `-- name: WeaveListChildProjects :many
SELECT id, created_at, updated_at, system_name, ui_name, description, status, namespace, parent_project_id, staging_id, owner_id, visibility, deprecated, license, readme, topics, base_url, created_by_id, version_number, enforce_concept_lists, is_master_weave FROM weave_projects
WHERE parent_project_id = $1
ORDER BY id ASC
`

func (q *Queries) WeaveListChildProjects(ctx context.Context, parentProjectID *string) ([]WeaveProject, error) {
	rows, err := q.db.Query(ctx, weaveListChildProjects, parentProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveProject{}
	for rows.Next() {
		var i WeaveProject
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.Namespace,
			&i.ParentProjectID,
			&i.StagingID,
			&i.OwnerID,
			&i.Visibility,
			&i.Deprecated,
			&i.License,
			&i.Readme,
			&i.Topics,
			&i.BaseUrl,
			&i.CreatedByID,
			&i.VersionNumber,
			&i.EnforceConceptLists,
			&i.IsMasterWeave,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListMasterWeaves = `-- name: WeaveListMasterWeaves :many
SELECT id, ui_name, system_name, description, namespace
FROM weave_projects
WHERE is_master_weave = true AND deprecated = false
ORDER BY COALESCE(ui_name->>'en', system_name, id) ASC, id ASC
`

type WeaveListMasterWeavesRow struct {
	ID          string  `json:"id"`
	UiName      []byte  `json:"ui_name"`
	SystemName  *string `json:"system_name"`
	Description []byte  `json:"description"`
	Namespace   *string `json:"namespace"`
}

// Master weaves only, ordered alphabetically by English UI name then id.
// Used by the parent-project picker so master weaves float to the top.
func (q *Queries) WeaveListMasterWeaves(ctx context.Context) ([]WeaveListMasterWeavesRow, error) {
	rows, err := q.db.Query(ctx, weaveListMasterWeaves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveListMasterWeavesRow{}
	for rows.Next() {
		var i WeaveListMasterWeavesRow
		if err := rows.Scan(
			&i.ID,
			&i.UiName,
			&i.SystemName,
			&i.Description,
			&i.Namespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveListProjects = `-- name: WeaveListProjects :many
SELECT id, created_at, updated_at, system_name, ui_name, description, status, namespace, parent_project_id, staging_id, owner_id, visibility, deprecated, license, readme, topics, base_url, created_by_id, version_number, enforce_concept_lists, is_master_weave FROM weave_projects
WHERE
    ($1::text = ''
     OR EXISTS (SELECT 1 FROM jsonb_each_text(ui_name) jt WHERE jt.value ILIKE '%' || $1::text || '%')
     OR EXISTS (SELECT 1 FROM jsonb_each_text(description) jt WHERE jt.value ILIKE '%' || $1::text || '%')
     OR system_name ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR owner_id = $2::text)
    AND ($3::text = '' OR created_by_id = $3::text)
    AND ($4::text = ''
         OR EXISTS (SELECT 1 FROM weave_project_actors wpa
                    WHERE wpa.project_id = weave_projects.id
                      AND wpa.actor_id = $4::text
                      AND wpa.role = 'owner'))
ORDER BY
    CASE WHEN $5::text = 'ui_name' AND NOT $6::boolean THEN ui_name->>'en' END ASC NULLS LAST,
    CASE WHEN $5::text = 'ui_name' AND $6::boolean THEN ui_name->>'en' END DESC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND NOT $6::boolean THEN system_name END ASC NULLS LAST,
    CASE WHEN $5::text = 'system_name' AND $6::boolean THEN system_name END DESC NULLS LAST,
    CASE WHEN $5::text = 'updated_at' AND NOT $6::boolean THEN updated_at END ASC,
    CASE WHEN $5::text = 'updated_at' AND $6::boolean THEN updated_at END DESC,
    id
LIMIT $8::integer OFFSET $7::integer
`

type WeaveListProjectsParams struct {
	Search        string `json:"search"`
	OwnerID       string `json:"owner_id"`
	CreatedByID   string `json:"created_by_id"`
	InstitutionID string `json:"institution_id"`
	SortBy        string `json:"sort_by"`
	SortDesc      bool   `json:"sort_desc"`
	ResultOffset  int32  `json:"result_offset"`
	ResultLimit   int32  `json:"result_limit"`
}

func (q *Queries) WeaveListProjects(ctx context.Context, arg WeaveListProjectsParams) ([]WeaveProject, error) {
	rows, err := q.db.Query(ctx, weaveListProjects,
		arg.Search,
		arg.OwnerID,
		arg.CreatedByID,
		arg.InstitutionID,
		arg.SortBy,
		arg.SortDesc,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeaveProject{}
	for rows.Next() {
		var i WeaveProject
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SystemName,
			&i.UiName,
			&i.Description,
			&i.Status,
			&i.Namespace,
			&i.ParentProjectID,
			&i.StagingID,
			&i.OwnerID,
			&i.Visibility,
			&i.Deprecated,
			&i.License,
			&i.Readme,
			&i.Topics,
			&i.BaseUrl,
			&i.CreatedByID,
			&i.VersionNumber,
			&i.EnforceConceptLists,
			&i.IsMasterWeave,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weaveSetProjectIsMasterWeave = `-- name: WeaveSetProjectIsMasterWeave :exec
UPDATE weave_projects SET is_master_weave = $2, updated_at = NOW()
WHERE id = $1
`

type WeaveSetProjectIsMasterWeaveParams struct {
	ID            string `json:"id"`
	IsMasterWeave bool   `json:"is_master_weave"`
}

// Super-admin-only toggle. Service enforces the role gate.
func (q *Queries) WeaveSetProjectIsMasterWeave(ctx context.Context, arg WeaveSetProjectIsMasterWeaveParams) error {
	_, err := q.db.Exec(ctx, weaveSetProjectIsMasterWeave, arg.ID, arg.IsMasterWeave)
	return err
}

const weaveUpdateProject = `-- name: WeaveUpdateProject :one
UPDATE weave_projects SET
    ui_name = $2, description = $3, system_name = $4, status = $5,
    namespace = $6, parent_project_id = $7, visibility = $8,
    is_master_weave = $9,
    updated_at = NOW()
WHERE id = $1 RETURNING id, created_at, updated_at, system_name, ui_name, description, status, namespace, parent_project_id, staging_id, owner_id, visibility, deprecated, license, readme, topics, base_url, created_by_id, version_number, enforce_concept_lists, is_master_weave
`

type WeaveUpdateProjectParams struct {
	ID              string  `json:"id"`
	UiName          []byte  `json:"ui_name"`
	Description     []byte  `json:"description"`
	SystemName      *string `json:"system_name"`
	Status          string  `json:"status"`
	Namespace       *string `json:"namespace"`
	ParentProjectID *string `json:"parent_project_id"`
	Visibility      string  `json:"visibility"`
	IsMasterWeave   bool    `json:"is_master_weave"`
}

func (q *Queries) WeaveUpdateProject(ctx context.Context, arg WeaveUpdateProjectParams) (WeaveProject, error) {
	row := q.db.QueryRow(ctx, weaveUpdateProject,
		arg.ID,
		arg.UiName,
		arg.Description,
		arg.SystemName,
		arg.Status,
		arg.Namespace,
		arg.ParentProjectID,
		arg.Visibility,
		arg.IsMasterWeave,
	)
	var i WeaveProject
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.Namespace,
		&i.ParentProjectID,
		&i.StagingID,
		&i.OwnerID,
		&i.Visibility,
		&i.Deprecated,
		&i.License,
		&i.Readme,
		&i.Topics,
		&i.BaseUrl,
		&i.CreatedByID,
		&i.VersionNumber,
		&i.EnforceConceptLists,
		&i.IsMasterWeave,
	)
	return i, err
}

const weaveUpdateProjectAbout = `-- name: WeaveUpdateProjectAbout :one
UPDATE weave_projects SET
    license = $2, readme = $3, topics = $4, base_url = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, created_at, updated_at, system_name, ui_name, description, status, namespace, parent_project_id, staging_id, owner_id, visibility, deprecated, license, readme, topics, base_url, created_by_id, version_number, enforce_concept_lists, is_master_weave
`

type WeaveUpdateProjectAboutParams struct {
	ID      string          `json:"id"`
	License string          `json:"license"`
	Readme  json.RawMessage `json:"readme"`
	Topics  []string        `json:"topics"`
	BaseUrl string          `json:"base_url"`
}

func (q *Queries) WeaveUpdateProjectAbout(ctx context.Context, arg WeaveUpdateProjectAboutParams) (WeaveProject, error) {
	row := q.db.QueryRow(ctx, weaveUpdateProjectAbout,
		arg.ID,
		arg.License,
		arg.Readme,
		arg.Topics,
		arg.BaseUrl,
	)
	var i WeaveProject
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
		&i.UiName,
		&i.Description,
		&i.Status,
		&i.Namespace,
		&i.ParentProjectID,
		&i.StagingID,
		&i.OwnerID,
		&i.Visibility,
		&i.Deprecated,
		&i.License,
		&i.Readme,
		&i.Topics,
		&i.BaseUrl,
		&i.CreatedByID,
		&i.VersionNumber,
		&i.EnforceConceptLists,
		&i.IsMasterWeave,
	)
	return i, err
}
