package hub

import (
	"context"
	"time"
)

// ProjectIntegration is one persisted (project, integration, config) row.
// A project can have multiple configs for the same integration (e.g. two
// different 3M instances) — ConfigID is a ULID generated by the service
// layer, Label is the operator-facing display name shown next to action
// buttons when more than one config is enabled for an integration.
//
// Config holds the merged user-supplied values; secret fields named by
// the integration's SecretFields() carry AES-GCM ciphertext rather than
// plaintext. The service layer is responsible for encrypting on the way
// in and decrypting on the way out — Store deals only in stored bytes.
type ProjectIntegration struct {
	ProjectID         string
	IntegrationID     string
	ConfigID          string
	Label             string
	Enabled           bool
	Config            map[string]any
	SecretRef         string
	ManagedInstanceID string // empty for manual configs; FK to arches_instances when "managed" source is selected
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Store is the persistence contract for the integrations hub. The pgx +
// sqlc implementation lives in store_postgres.go; tests inject an
// in-memory fake.
type Store interface {
	// Get returns the row for (projectID, integrationID, configID), or
	// (nil, nil) if no row exists. Treat (nil, nil) as "never configured".
	Get(ctx context.Context, projectID, integrationID, configID string) (*ProjectIntegration, error)

	// ListForProject returns every row a project has touched (enabled
	// or not), ordered by (integration_id, config_id).
	ListForProject(ctx context.Context, projectID string) ([]*ProjectIntegration, error)

	// ListConfigsForIntegration returns the configs for a single
	// (project, integration) — the per-integration card in the settings
	// UI reads from this when expanding the config list.
	ListConfigsForIntegration(ctx context.Context, projectID, integrationID string) ([]*ProjectIntegration, error)

	// ListEnabledForProject returns only rows whose enabled flag is
	// true. Used by surfaces (e.g. DerivativesCap.IntegrationActions)
	// that want to short-circuit when nothing is wired up.
	ListEnabledForProject(ctx context.Context, projectID string) ([]*ProjectIntegration, error)

	// Upsert writes the row. The caller has already encrypted secret
	// fields in pi.Config and assigned pi.ConfigID.
	Upsert(ctx context.Context, pi *ProjectIntegration) (*ProjectIntegration, error)

	// Delete removes the row by full triple. Other configs under the
	// same (project, integration) survive.
	Delete(ctx context.Context, projectID, integrationID, configID string) error
}
