package project

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/pletka-io/pletka/pkg/auth"
	overridepkg "github.com/pletka-io/pletka/pkg/weave/override"
)

// entityTypeModel and entityTypeCollection name the two entity types a
// pattern's presence endpoint covers — mirrors the (unexported, ad hoc)
// literals saveOverrides already switches on in override_write.go.
const (
	entityTypeModel      = "model"
	entityTypeCollection = "collection"
)

// presenceRequest is the heartbeat body the editor posts every 20s while
// open, and once more (best effort) on unmount/pagehide with state "left".
//
// SessionID identifies one open browser tab, generated by the editor at
// load time and stable for that tab's lifetime — never derived from the
// schema or a URL, since it has no server-side meaning until the first
// beat. It exists so one curator with two tabs open is tracked as one
// editor with two live sessions (see override.Presence), not two editors,
// and so closing one tab doesn't drop the other. An empty SessionID on a
// "left" request means "every session this actor holds for this entity",
// not "no session" — see decodePresenceRequest and override.Presence.Leave.
type presenceRequest struct {
	State     string `json:"state,omitempty"`
	SessionID string `json:"session_id,omitempty"`
}

// presenceResponse always carries a non-nil Editors slice so the JSON body
// is "editors":[] rather than "editors":null when there is no one else.
type presenceResponse struct {
	Editors []overridepkg.Editor `json:"editors"`
}

// decodePresenceRequest decodes body into a presenceRequest. A body that is
// empty before a single byte is read — the shape of a browser
// pagehide/unload beacon sent with no payload — is not an error: it
// decodes to {"state":"left"} with no session id, which
// override.Presence.Leave treats as "drop every session this actor holds"
// (fix round 1, finding 5). Refusing an empty beacon with a 400 would
// leave a curator who genuinely navigated away marked present for up to
// the full TTL, since the browser gives no second chance to retry a
// pagehide beacon.
func decodePresenceRequest(body io.Reader) (presenceRequest, error) {
	var req presenceRequest
	err := json.NewDecoder(body).Decode(&req)
	if errors.Is(err, io.EOF) {
		return presenceRequest{State: "left"}, nil
	}
	return req, err
}

// ModelOverridesPresence handles POST
// /projects/{projectID}/models/{modelID}/overrides/presence.
func (h *Handler) ModelOverridesPresence(w http.ResponseWriter, r *http.Request) {
	h.overridesPresence(w, r, entityTypeModel, chi.URLParam(r, "modelID"))
}

// CollectionOverridesPresence handles POST
// /projects/{projectID}/collections/{collectionID}/overrides/presence.
func (h *Handler) CollectionOverridesPresence(w http.ResponseWriter, r *http.Request) {
	h.overridesPresence(w, r, entityTypeCollection, chi.URLParam(r, "collectionID"))
}

// overridesPresence is a notice, never a lock: it records that the caller
// is editing (entityType, entityID) and reports who else is, or — for
// {"state":"left"} — drops the caller's own session(s). It gates on
// exactly the same project -> CanEdit -> entity-ownership order as
// saveOverrides (see override_write.go), in that order, deliberately: this
// endpoint discloses other actors' ids, names and edit start times, so the
// edit check must run before the entity-ownership lookup, not after it —
// otherwise a non-editor could tell "entity belongs to this project" (200,
// empty list) apart from "entity doesn't" (404) purely from the status
// code (fix round 1, finding 4). Unlike the save, failing the edit check
// is not an error here: the caller gets {"editors":[]} back and nothing is
// recorded for them, exactly like a viewer just watching (fix round 1,
// finding 1).
func (h *Handler) overridesPresence(w http.ResponseWriter, r *http.Request, entityType, entityID string) {
	ctx := r.Context()
	projectID := chi.URLParam(r, "projectID")
	if projectID == "" || entityID == "" {
		writeError(w, http.StatusBadRequest, "projectID and entityID are required")
		return
	}

	project, err := h.svc.Get(ctx, projectID)
	if err != nil || project == nil {
		writeError(w, http.StatusNotFound, "project not found")
		return
	}

	actorID := auth.FromContext(ctx).ActorID
	if actorID == "" || !h.svc.CanEdit(ctx, project) {
		// Anonymous, session-lapsed, or a viewer without edit rights.
		// Runs BEFORE the entity-ownership lookup below on purpose (see
		// doc comment above) — a non-editor never reaches it, so they
		// can never distinguish a real entity id from a wrong one by
		// status code.
		writeJSON(w, http.StatusOK, presenceResponse{Editors: []overridepkg.Editor{}})
		return
	}

	switch entityType {
	case entityTypeModel:
		model, err := h.weave.Models().GetByID(ctx, entityID)
		// Same ownership rule as saveOverrides: another project's model
		// or collection is "not found" here, never a different error.
		if err != nil || model == nil || model.ProjectID != projectID {
			writeError(w, http.StatusNotFound, "model not found")
			return
		}
	case entityTypeCollection:
		collection, err := h.weave.Collections().GetByID(ctx, entityID)
		if err != nil || collection == nil || collection.ProjectID != projectID {
			writeError(w, http.StatusNotFound, "collection not found")
			return
		}
	}

	req, err := decodePresenceRequest(r.Body)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid presence payload")
		return
	}

	if req.State == "left" {
		h.presence.Leave(entityType, entityID, actorID, req.SessionID)
		writeJSON(w, http.StatusOK, presenceResponse{Editors: []overridepkg.Editor{}})
		return
	}

	// A Handler built as a bare struct literal, which several tests in this
	// package do, has no clock. Fall back rather than panic, the same way
	// the registry's methods tolerate a nil receiver.
	now := time.Now()
	if h.clock != nil {
		now = h.clock()
	}
	h.presence.Beat(entityType, entityID, actorID, req.SessionID, now)
	others := h.presence.Others(entityType, entityID, actorID, now)
	editors := make([]overridepkg.Editor, len(others))
	for i, o := range others {
		editors[i] = overridepkg.Editor{
			ActorID: o.ActorID,
			Name:    h.actorDisplayName(ctx, o.ActorID),
			Since:   o.Since,
		}
	}
	writeJSON(w, http.StatusOK, presenceResponse{Editors: editors})
}

// actorDisplayName resolves actorID's display name for the presence
// response. domain.WeaveStore has no dedicated actor-lookup method
// (no Actors() in the interface) — the nearest equivalent is the auth
// store's actor-profile join, which works for any actor id, not just the
// caller's own. Falls back to the actor id itself when the lookup errors,
// finds nothing, or the display name is blank.
func (h *Handler) actorDisplayName(ctx context.Context, actorID string) string {
	profile, err := h.weave.Auth().GetProfileByActorID(ctx, actorID)
	if err != nil || profile == nil || profile.DisplayName == "" {
		return actorID
	}
	return profile.DisplayName
}
