package testdb

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/pletka-io/pletka/pkg/database/sqlcgen"
	"github.com/pletka-io/pletka/pkg/service/gitmaterializer"
	weaveontology "github.com/pletka-io/pletka/pkg/weave/ontology"
)

// Synthetic fixture project ids hydrated into every template clone. They are
// generated by test/fixturegen and committed in the pletka-fixtures submodule
// under test/fixtures/<id>. They carry no customer PII or real project
// identities.
const (
	// FixtureSingle is a self-contained project with one linked vendored
	// ontology, a display category, and a few crm: fields. Store/CRUD/path
	// tests point here.
	FixtureSingle = "FXSINGLE"
	// FixtureParent is the inheritance parent FixtureChild links.
	FixtureParent = "FXPARENT"
	// FixtureChild links FixtureParent (primary, draft inheritance) and drives
	// the inheritance, search-across-parent, bundle, and vendored-parent
	// restore paths.
	FixtureChild = "FXCHILD"

	// fixtureOwnerID is the synthetic organization actor that owns every fixture
	// project. It must match the owner baked into the snapshots by
	// test/fixturegen: project snapshots reference the owner by id but do not
	// carry the actor row itself, so the template seeds it before hydration.
	fixtureOwnerID = "FXORG"
)

// hydrateFixtureOrder lists the fixture snapshots to load into the template, in
// dependency order: a parent must be hydrated before any child that inherits
// it (hydrateProjectInheritanceTx requires the parent row to exist), so
// FixtureParent precedes FixtureChild.
var hydrateFixtureOrder = []string{FixtureParent, FixtureChild, FixtureSingle}

// fixturesRoot resolves the test/fixtures submodule directory relative to the
// module root, walking up from this source file to the go.mod (go test runs in
// the package dir, so a relative path is not reliable). The bool is false when
// the module root or the submodule directory cannot be located — e.g. a build
// with -trimpath, or a checkout that has not fetched the submodule.
func fixturesRoot() (string, bool) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", false
	}
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			root := filepath.Join(dir, "test", "fixtures")
			if info, err := os.Stat(root); err == nil && info.IsDir() {
				return root, true
			}
			return "", false
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

// ontologyVendorImporter adapts the ontology Service to
// gitmaterializer.VendoredOntologyImporter. It mirrors pkg/app's
// NewOntologyVendorImporter; the logic is duplicated here (rather than imported)
// because internal/testdb is imported by slice tests, and pulling in pkg/app —
// which assembles every slice — would form an import cycle in those test
// builds. gitmaterializer deliberately does not depend on the ontology slice,
// so the adapter has to live on the wiring side.
type ontologyVendorImporter struct{ svc *weaveontology.Service }

// ImportVendoredOntology imports one vendored ontology manifest through the
// ontology service. Idempotent per manifest.Ontology.VersionID.
func (a ontologyVendorImporter) ImportVendoredOntology(ctx context.Context, imp gitmaterializer.VendoredOntologyImport) error {
	root := imp.Manifest.Ontology
	var files []string
	if imp.Manifest.Sources != nil {
		files = imp.Manifest.Sources.Files
	}
	return a.svc.ImportVendoredVersion(ctx, weaveontology.VendoredOntologyImportRequest{
		OntologyID:    root.OntologyID,
		VersionID:     root.VersionID,
		VersionString: root.Version,
		Slug:          root.Slug,
		Title:         root.Title,
		Kind:          root.Kind,
		Namespace:     root.Namespace,
		Prefixes:      root.Prefixes,
		BaseDir:       imp.RootDir,
		Files:         files,
		Imports:       imp.Manifest.Imports,
	})
}

// newHydrator builds a Materializer wired with the ontology importer — the same
// wiring production restore uses — so vendored ontologies in a snapshot are
// hydrated through the ontology slice.
func newHydrator(pool *pgxpool.Pool, baseDir string) *gitmaterializer.Materializer {
	importer := ontologyVendorImporter{
		svc: weaveontology.NewService(weaveontology.NewPostgresStore(pool), nil, nil),
	}
	return gitmaterializer.NewMaterializer(pool, baseDir, nil).WithOntologyImporter(importer)
}

// hydrateFixtures loads the curated fixture snapshots into the freshly migrated
// template database, before any per-package clone is cut, so every clone
// inherits the same seed data. dsn points at the building template DB. It opens
// (and closes) its own pgx pool so no session outlives the build — the template
// promotion rename refuses to proceed while a session is connected.
//
// A missing submodule directory is reported as an error: under REQUIRE_DB the
// caller turns that into a hard failure, otherwise the whole DB suite is
// skipped (see skipOrFail).
func hydrateFixtures(ctx context.Context, dsn string) error {
	root, ok := fixturesRoot()
	if !ok {
		return fmt.Errorf("fixtures submodule not present; run `git submodule update --init test/fixtures` (or, if it is empty, `make build-test-snapshot`)")
	}

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return fmt.Errorf("open pool for hydration: %w", err)
	}
	defer pool.Close()

	if err := seedFixtureOwner(ctx, pool); err != nil {
		return err
	}

	for _, id := range hydrateFixtureOrder {
		snapshotDir := filepath.Join(root, id)
		if info, err := os.Stat(snapshotDir); err != nil || !info.IsDir() {
			return fmt.Errorf("fixture snapshot %s missing at %s; run `make build-test-snapshot`", id, snapshotDir)
		}
		// A fresh, per-project base dir keeps the materializer's scratch state
		// isolated between snapshots.
		mat := newHydrator(pool, filepath.Join(os.TempDir(), "testdb-hydrate", id))
		if _, err := mat.HydrateProjectSnapshot(ctx, snapshotDir); err != nil {
			return fmt.Errorf("hydrate fixture %s: %w", id, err)
		}
	}
	return nil
}

// seedFixtureOwner creates the synthetic owner organization the fixture
// snapshots reference. Snapshots restore projects, ontologies, and inheritance
// but not the owning actor, so it must exist before HydrateProjectSnapshot runs.
func seedFixtureOwner(ctx context.Context, pool *pgxpool.Pool) error {
	q := sqlcgen.New(pool)
	if _, err := q.WeaveCreateActor(ctx, sqlcgen.WeaveCreateActorParams{
		ID:          fixtureOwnerID,
		Type:        "organization",
		DisplayName: "Fixture Org",
		Slug:        "fixture-org",
		Role:        "",
		Visibility:  "private",
	}); err != nil {
		return fmt.Errorf("seed fixture owner actor: %w", err)
	}
	return nil
}

// HydrateSnapshot loads a fixture snapshot into pool under a fresh target id,
// on top of the template baseline, and returns the restore plan. It is the
// parallel-safe way for a test to get an isolated extra copy (asID) of a
// fixture (name is one of the Fixture* ids) without colliding with the
// template-seeded copy.
func HydrateSnapshot(t *testing.T, pool *pgxpool.Pool, name, asID string) *gitmaterializer.RestorePlan {
	t.Helper()
	root, ok := fixturesRoot()
	if !ok {
		t.Skip("test/fixtures submodule not available")
	}
	snapshotDir := filepath.Join(root, name)
	if info, err := os.Stat(snapshotDir); err != nil || !info.IsDir() {
		t.Fatalf("fixture snapshot %s missing at %s; run `make build-test-snapshot`", name, snapshotDir)
	}
	mat := newHydrator(pool, t.TempDir())
	plan, err := mat.HydrateProjectSnapshotAs(context.Background(), snapshotDir, asID)
	if err != nil {
		t.Fatalf("hydrate fixture %s as %s: %v", name, asID, err)
	}
	return plan
}
